### ISSUE TITLE
Incorrect permissions assigned on cloning a resource

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#10302]
## Expected Behavior
When a resource is cloned, it should be copied with its permissions. (only the owner changes to the person who has performed the action)

## Actual Behavior
Permissions are altered.
- Anyone is set to None
- The owner of the original resource is copied in the new resource as the manager

## Steps to Reproduce the Problem

  1. View a resource from another user (not admin) with anyone= View permission.
  2. Clone the resource
  3. Notice the permissions of the cloned resource

## Specifications

  - GeoNode version: 4.0.x
  - Installation type (vanilla, geonode-project):
  - Installation method (manual, docker):
  - Platform:
  - Additional details:

**Comment by mattiagiupponi** [comment]
@marthamareal does this happen also on master demo? 
Can you please try with a non-dataset resource, like a document? on master, is the new importer to clone the resource so it behaves differently than the default flow

**Comment by marthamareal** [comment]
@mattiagiupponi tested this on development.demo as labels reflect. I have not tested it with master.

**Comment by mattiagiupponi** [comment]
ok the issue is also on master -> https://master.demo.geonode.org/catalogue/#/document/3144

**Comment by mattiagiupponi** [comment]
@marthamareal @giohappy 
Analyzing better the issue, this looks like the wanted workflow for a cloned dataset.
This check to remove the anonymous user from the cloned resource:
https://github.com/GeoNode/geonode/blob/bd25b23a96c77b4fe4eac9d0c8e2a5d870edd3fb/geonode/resource/manager.py#L514-L524

Was discussed and approved in this issue: https://github.com/GeoNode/geonode/issues/8565 where:
- the cloned resource must be private
- the cloned resource should have the permissions of the original resource

Should this behavior change? if yes, can the expected behaviour be specified better?
