### ISSUE TITLE
osgeo4w / stand alone windows installer

### ISSUE THREAD

**Issue by jj0hns0n** [GeoNode/geonode#1039]
Would be nice to have GeoNode installable via osgeo4w or via a standalone installer based on osgeo4w

**Comment by nathanhilbert** [comment]
@jj0hns0n has there been any progress on this?  I was going to take a look using NSIS during the sprint.

Some thoughts around the stand-alone install.  

 - I'll be working on one for a base production install using the script [here](https://bitbucket.org/nathanhilbert/geonodewininstall) the next few days.  I think a dev version would be a lot easier.
 - Boundlessgeo seems to have a good installer for their suite, but I can't find anything in their github.  Maybe someone could chime in from Boundless? I'll be using QGIS as an example https://github.com/qgis/QGIS/tree/master/ms-windows minus all of the C++ compiles.
- Need to check how  wheels are used by pip in relation to compiled deps for Geonode.

**Comment by jj0hns0n** [comment]
@nathanhilbert not sure if there has been any progress. You should check in with someone like @bmmpxf who should be able to point you in the right direction.

**Comment by nathanhilbert** [comment]
First dirty dev environment installer for Windows.
https://s3.amazonaws.com/geonodedeps/Geonode_Dev.exe
Requires Java to be installed.
Uses an isolated python environment by setting environment variables through batch files.
To dos include:
 - Verify that eggs are loading correctly when code is in the egg folder in site-packages.  Virtualenv has some special handlers that loads eggs.
 - Create icons and shortcuts
 - Warn users that if they try to install this to any directory with spaces, it will not run because of the paths when running geoserver
 - Verify that Java is installed before installing
 - Do the above items using the (NSIS script)[http://nsis.sourceforge.net/Main_Page)

Where is the best place to document this build process?

**Comment by nathanhilbert** [comment]
Curious if anyone has any experience in standalone python installs or portable virtualenvs.  See notes below of my approaches so far.

For the Geonode_Dev_2.4.exe it installs a dev environment with a sort of standalone python install.  It is stable and you can give it a try.  I need a better way of dealing with python.  It currently does everything that we need except “pip uninstall” uninstalls from the standalone and “pip install” installs to the base system python install.  This could be solved by putting a –target flag on pip install with the absolute path, but that seems annoying.  I was playing around with virtualenvs last week using the –relocatable flag, but that didn’t work.  I might use the approach of replacing all of the absolute paths in the virtualenv with the current directory, which I have done in the past, but that is not ideal for the build process.  Any suggestions would be appreciated.

**Comment by ingenieroariel** [comment]
I have some experience in portable python envs. What shell are you using?
do we have an opportunity to use a custom shell for Django/GeoNode stuff
(since we want management commands to work and be able to use pip with the
right path). That approach would let us customize the path before launching
that shell and perhaps even use one that is friendly for unix users (cd,
cat, autocomplete, pipe support).

In any case it is great that you are moving this forward, kudos!

**Comment by ingenieroariel** [comment]
Another question, have you looked into wheels instead of eggs to avoid eggs
pitfalls?

http://pythonwheels.com/

**Comment by nathanhilbert** [comment]
Yeah started using Wheels: https://github.com/GeoNode/geonode/pull/2030 but realized that not every project has wheels https://github.com/GeoNode/geonode/issues/2075 in their pypi.  

I forgot to mention another direction of initializing a fresh virtualenv and running through the script in a batch script during the Windows install.  This is probably the best option, but the most work for my use case.  

I'm just using the straight Windows command.  I assume you're thinking of something like MinGW for an alternative shell.  Although good for development, probably isn't ideal for serving a production application.  I think I'm accomplishing the same direction here https://github.com/GeoNode/geonode/blob/master/scripts/ms-install/package/prefix_env.bat

**Comment by amrabdelaziz91** [comment]
@nathanhilbert  I'm curious to know if Boundless' geoserver can be configured to be used with geonode on windows , It would be really useful.

**Comment by nathanhilbert** [comment]
@amrabdelaziz91 I'm guessing you're asking because you have Opengeo Suite installed, and want to interface with the existing geoserver.  There are some custom libraries for authentication in the GeoNode Geoserver build, so an OpenGeo Suite install of geoserver would not work without these libraries to the best of my knowledge.
