### ISSUE TITLE
Configure user notifications off by default

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#10716]
At this moment new users are configured to receive any notification generated by the system.
The proposal is to disable the notifications by default, as requested by several users.

**Comment by t-book** [comment]
Very good @giohappy . my +1

**Comment by marthamareal** [comment]
@giohappy Do you mean having these set to false by default?


![Image](https://user-images.githubusercontent.com/20810749/223060981-c894b985-2a2d-4f3e-bf31-9f64a4e30eb3.png)

**Comment by giohappy** [comment]
yes @marthamareal

**Comment by marthamareal** [comment]
@giohappy The notifications being set to true relates to the pinax module and how we create the Notifiction types.

1. when we are creating the Notification types [here](https://github.com/GeoNode/geonode/blob/master/geonode/notifications_helper.py#L63), we do not specify the default value, hence pinax will user its default set [here](https://github.com/pinax/pinax-notifications/blob/master/pinax/notifications/models.py#L40).
2. When creating the notification settings, the default on/off on the notification media is False(0) however, the comparison made [here](https://github.com/pinax/pinax-notifications/blob/master/pinax/notifications/hooks.py#L36) by pinax initially is true since 0<=2 hence setting notifications to true by default.

**Comment by giohappy** [comment]
@marthamareal do we have a solution to set the to false by default?

**Comment by marthamareal** [comment]
@giohappy One of the solutions would be:
- provide a default=0 when creating Notification types [here](https://github.com/GeoNode/geonode/blob/master/geonode/notifications_helper.py#L63).
- and also a migration to update the existing Notification types' defaults from 2 to 0

**Comment by giohappy** [comment]
ok @marthamareal you can proceed.

**Comment by marthamareal** [comment]
@giohappy, since the creation of notification settings with send option turned on also depends on the `PINAX_NOTIFICATIONS_BACKENDS` set here, I have updated the spam_sensitivity of email backends to 3  to be greater than the default of the NoticeType (2) in order to have the notifications turned off by default.
