### ISSUE TITLE
Improve B/R procedures

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#10792]
In the B/R code there are many points that may be improved, since they could lead to random issues.

- Tables could be retrieved in a single step, closing the connection as soon as the needed data is retrieved: https://github.com/GeoNode/geonode/blob/e66877a0bcd8b1e9278202e4e6fe7a4665517f12/geonode/br/management/commands/utils/utils.py#L254-L293
- The tables are dumped in binary format, so it is dependent on the PG version, and furthermore files can not be easily inspected:
https://github.com/GeoNode/geonode/blob/e66877a0bcd8b1e9278202e4e6fe7a4665517f12/geonode/br/management/commands/utils/utils.py#L282-L283

- Transaction controls are badly implemented: if an operation fails, all the subsequand ones are automatically skipped by the dbms, so the commit/rollaback should be placed inside the loop:
https://github.com/GeoNode/geonode/blob/e66877a0bcd8b1e9278202e4e6fe7a4665517f12/geonode/br/management/commands/utils/utils.py#L300-L343

- When dealing with tables, if tables are in different schemas the procedure may break

- Password are visibile in the process list since they are part of the command line: https://github.com/GeoNode/geonode/blob/e66877a0bcd8b1e9278202e4e6fe7a4665517f12/geonode/br/management/commands/utils/utils.py#L282

- Logging 
  - is quite confused
  - uses `print` instead of logging
  - doesn't always say what is going to do, so for long tasks it seems it's freezed

- GWC layers are not recreated
  
## Specifications
  - GeoNode version: linked code is from 4.0.3

**Comment by etj** [comment]
@gannebamm can you pls report here any error you found in the BR procedures?

**Comment by Cornacap** [comment]
I checked with `docker logs -f django4geonode4_0` but could see anything concerning the backup nor the restore I did a minute before:

...
...
Found another file with the destination path 'img/bing_road_on_demand.png'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'img/bing_aerial_w_labels.png'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'img/bing_canvas_dark.png'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'css/site_base.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.

0 static files copied to '/mnt/volumes/statics/static', 3887 unmodified.
statics tasks done
****************************geoserver********************************
GeoServer is available for HTTP calls!
waitforgeoserver tasks done
********************geoserver fixture********************************
Setting GeoServer Admin Password...
Response Code: 200
GeoServer admin password updated SUCCESSFULLY!
geoserverfixture tasks done
Executing UWSGI server uwsgi --ini /usr/src/geonode4_0/uwsgi.ini for Production
-----------------------------------------------------
FINISHED DJANGO ENTRYPOINT --------------------------
-----------------------------------------------------
got command uwsgi --ini /usr/src/geonode4_0/uwsgi.ini
[uWSGI] getting INI configuration from /usr/src/geonode4_0/uwsgi.ini

**Comment by Cornacap** [comment]
That was show while I did the restore:
`root@vmgeonode:/var/lib/docker/volumes/geonode4_0-backup-restore# docker exec -it django4geonode4_0 sh -c 'SOURCE_URL=localhost TARGET_URL=localhost ./geonode4_0/br/restore.sh $BKP_FOLDER_NAME'
-----------------------------------------------------
STARTING geonode4_0 RESTORE Tue Mar 21 14:10:11 UTC 2023
-----------------------------------------------------
localhost --> localhost
-----------------------------------------------------
 1. BACKUP localhost
-----------------------------------------------------
-----------------------------------------------------
STARTING geonode4_0 BACKUP Tue Mar 21 14:10:11 UTC 2023
-----------------------------------------------------
Before proceeding with the Backup, please ensure that:
 1. The backend (DB or whatever) is accessible and you have rights
 2. The GeoServer is up and running and reachable from this machine
STARTED - 1/11
STARTED - 5/11
COMPLETED - 11/11
Dumping existing GeoServer Vectorial Data: ['gf_layer_details', 'gf_gfuser', 'gf_layer_attributes', 'gf_layer_styles', 'gf_gsuser', 'gf_gsinstance', 'gf_usergroup', 'gf_rule', 'gf_rule_limits', 'gf_adminrule', 'gf_user_usergroups', 'Berlin']
Dump Table: geonode4_0_data:gf_layer_details
Dump Table: geonode4_0_data:gf_gfuser
Dump Table: geonode4_0_data:gf_layer_attributes
Dump Table: geonode4_0_data:gf_layer_styles
Dump Table: geonode4_0_data:gf_gsuser
Dump Table: geonode4_0_data:gf_gsinstance
Dump Table: geonode4_0_data:gf_usergroup
Dump Table: geonode4_0_data:gf_rule
Dump Table: geonode4_0_data:gf_rule_limits
Dump Table: geonode4_0_data:gf_adminrule
Dump Table: geonode4_0_data:gf_user_usergroups
Dump Table: geonode4_0_data:Berlin
CommandError: No installed app with label 'dialogos'.`

**Comment by etj** [comment]
@Cornacap pls remove `dialogos` from your `docker-settings.ini` as reported in https://github.com/GeoNode/geonode-project/issues/414

**Comment by Cornacap** [comment]
@etj I did so and restarted Geonode, but it doesn't show effect:
- same hint for dialogos
- Backups with Hashtags
- no Restore

**Comment by Cornacap** [comment]
Sorry, I cannot find any *.zip in the geonode directories.
