### ISSUE TITLE
circleCI tests faling

### ISSUE THREAD

**Issue by mattiagiupponi** [GeoNode/geonode#10887]
On master CircleCI build is failing due to a test:

```python
======================================================================
FAIL: test_geoserver_proxy_strip_paths (geonode.geoserver.tests.test_helpers.HelperTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/src/geonode/geonode/decorators.py", line 54, in wrapper
    return func(*args, **kwargs)
  File "/usr/src/geonode/geonode/geoserver/tests/test_helpers.py", line 235, in test_geoserver_proxy_strip_paths
    self.assertEqual(response.status_code, 200)
AssertionError: 401 != 200
```

## Specifications

  - GeoNode version: 4.0.x, 4.1.x, master
  - Installation type (vanilla, geonode-project): vanilla
  - Installation method (manual, docker):
  - Platform: CircleCI
  - Additional details: CircleCI build can be found here https://app.circleci.com/pipelines/github/GeoNode/geonode

**Comment by giohappy** [comment]
@mattiagiupponi is it only failing on CI?

**Comment by mattiagiupponi** [comment]
Si @giohappy, on a local environment works as expected

**Comment by giohappy** [comment]
ok, the issue with that test is that:

1. it's testing a WFS request but it's using the `gs_layers` url (`/gs/rest/layers`). It should use `ows_endpoint` instead
2. It has given false positives until now because `gs_layers` was open without authentication. The recent changes to the GS REST API security configuration don't allow unauthenticated calls to that endpoint, making that (currently wrong) test fail.

The test must be fixed. The other request in the same test should also be reviewed. It makes a `DescribeFeatureType` request with an `image/png` output format, which is clearly wrong (an image output for such a request is meaningless).
It it was meant to test an error from Geoserver, it shouldn't test the 200 response code, because Geoserver always returns 200 for OWS services, even when the response is an error.

**Comment by giohappy** [comment]
fixed in https://github.com/GeoNode/geonode/commit/fa2c6da13a87a44d012b7b68e109b4d800471d82
