### ISSUE TITLE
Setting GeoServer password fails

### ISSUE THREAD

**Issue by apexys** [GeoNode/geonode#11184]
Hi GeoNode-team,

I tried setting the passwords for the admin account and the geoserver admin account as described in https://docs.geonode.org/en/master/install/basic/index.html#update-the-passwords-and-keys-on-env-file

When running `docker compose up` however, I encountered the following message:
![image](https://github.com/GeoNode/geonode/assets/3950769/d4d1855a-f6ad-4760-86de-1c84f81ee9b2)

If I tried to upload any datasets, the upload would fail with a message in the uploader UI reporting an authentication issue.

I was able to log into the geoserver with the default credentials (admin and geoserver).
When I change the password in the geoserver, the GeoNode installation works as expected.

Am I doing something wrong when changing the passwords?

Thanks in advance!

**Comment by phardy-egis** [comment]
I noticed that I had also to change admin password on geoserver admin interface prior changing it into the `.env` file.

**Comment by giohappy** [comment]
I confirm this misbehavior. We will have to investigate why the credentials set in the .env file are not correctly picked during the initial startup.

**Comment by ridoo** [comment]
This warning is placed directly under the [password update](https://docs.geonode.org/en/master/install/basic/index.html#update-the-passwords-and-keys-on-env-file) documentation. This is at least confusing, as the startup is actually trying to set a password at GeoServer.

![image](https://github.com/GeoNode/geonode/assets/881756/5621980d-c77a-4e0e-8c7c-f77458d82b91)

**Comment by giohappy** [comment]
This should be covered in https://github.com/GeoNode/geonode/pull/11308 where the updating of Geoserver password will be disabled.

**Comment by ridoo** [comment]
@giohappy  this decision maybe set already. However, I got this to work with a combination of `.env` and overridden geonode settings:

In the `.env` file one only have set the password of your choice:
```
GEOSERVER_ADMIN_PASSWORD="my new password"
```

After the default `geonode.settings` module, the following parameters have to be reset, e.g. by overloading the settings via `DJANGO_SETTINGS_MODULE`:

```
# The password currently set on the GeoServer, or the default
OGC_SERVER_DEFAULT_PASSWORD = "geoserver"
```

Here's why:

https://github.com/GeoNode/geonode/blob/c7d496462de7d67f2f3ee14db9e55bc392e1b9ce/geonode/settings.py#L1006-L1008


The parameters to set the GeoServer's credentials override the default ones, which are used here:

https://github.com/GeoNode/geonode/blob/c7d496462de7d67f2f3ee14db9e55bc392e1b9ce/tasks.py#L569-L575


You can also see that the username of GeoServer admin cannot be changed via GeoNode.

**Comment by giohappy** [comment]
@ridoo the problem is that it will work only the very first time, when the default password of Geoserver is known.
We could move the

**Comment by giohappy** [comment]
@ridoo the problem is that it will work only the very first time, when the default password of Geoserver is known. I see managing the "old" and the "new" Geoserver passwords too much convoluted.

We could move `geoserverfixture` inside the initialization block, which will run only the very first time.

https://github.com/GeoNode/geonode/blob/d95db9f511849c7369fc19f88d0af4cc488be6df/entrypoint.sh#L56-L61

In that case, the default `geoserver` password could be hard coded and kept aligned to the default security configuration we get from the [Geoserver data dir](https://github.com/GeoNode/geoserver-geonode-ext/tree/2.23.0/data).

@afabiani opinions?

**Comment by afabiani** [comment]
In my [proposal ](https://github.com/GeoNode/geonode/pull/11308/files#diff-6f9d41d046756f0ddc2fcee0626bdb50100d12b88f293734eff742818e03efa2L64-L65) I actually removed it completely since it is possible that we have an existing GeoServer with a different password already. The correct way to do that would be actually to generate and provide to GeoNode the GeoServer `MASTER PASSWORD` wich could be used to reset the admin one or to find a way to inject the encoded password into the GeoServer data dir (the latter working only if GeoNode is able to access the shared `GEOSERVER_DATA_DIR`).

Having the code trying to set the password only at `initialization` time is feasable but does not guarantee that the password will be reset anyway.

My opinion honestly is that the admin password should be correctly set into the `.env` file without making GeoNode trying to set up it atumatically.
