### ISSUE TITLE
Docker compose tags images with the wrong version

### ISSUE THREAD

**Issue by ridoo** [GeoNode/geonode#11364]
## Expected Behavior

Docker compose tags the built images with the right version.

## Actual Behavior

Version 4.1.1 tags the built images with 4.0

https://github.com/GeoNode/geonode/blob/e2d11053cd58fd733d67659bc714dfb273633471/docker-compose.yml#L6

## Steps to Reproduce the Problem

  1. Check out the tag 4.1.1
  2. Build via docker-compose
  3. Check the tagged Version

(or just [check the docker-compose file](https://github.com/GeoNode/geonode/blob/4.1.1/docker-compose.yml#L6)) 

## Specifications

  - GeoNode version: 4.1.1
  - Installation type (vanilla, geonode-project): vanilla
  - Installation method (manual, docker): docker
  - Platform: linux
  - Additional details:

**Comment by giohappy** [comment]
@ridoo you're right, the tag wasn't updated
Starting from 4.2.0 things will change, since we [will be using a published base](https://github.com/GeoNode/geonode/blob/master/docker-compose.yml#L6) image rather than building locally.

The GeoNode image will still [build locally](https://github.com/GeoNode/geonode-project/blob/master/docker-compose.yml#L29) for GeoNode Projects of course.

I don't think there's much we can do about this issue at the moment.

**Comment by ridoo** [comment]
Alright, just wanted to mention. I will close this issue then.

**Comment by ridoo** [comment]
@giohappy one question though.

It seems you plan to tag your GeoNode image with a Ubuntu version (geonode/geonode:latest-ubuntu-22.0) rather than a GeoNode version. Is this correct? 🧐

**Comment by giohappy** [comment]
>It seems you plan to tag your GeoNode image with a Ubuntu version (geonode/geonode:latest-ubuntu-22.0) rather than a GeoNode version. Is this correct?

Both. For GeoNode 4.2.0 it will be `geonode/geonode:4.2.0-ubuntu-22.0`
