### ISSUE TITLE
Metadata upload is broken

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#11467]
- upload shapefile + metadata --> ok
 - edit / upload metadata --> error

 ![image](https://github.com/GeoNode/geonode/assets/717359/9082d1f9-6be6-4958-adf2-6b674a09c166)

![image](https://github.com/GeoNode/geonode/assets/717359/8ef497a7-fb07-4401-aa34-96e8a061c1a6)

**Comment by mattiagiupponi** [comment]
@giohappy @etj The implementation of the two handlers that will be able to ingestion SLD files and XML files are available in the geonode-importer repo at this links:

https://github.com/GeoNode/geonode-importer/issues/200
https://github.com/GeoNode/geonode-importer/issues/201

Since the call will be async, the FE part needs to be fixed since rely on the legacy progress check (is not using the executionrequest).
To be decided how to approach it

**Comment by giohappy** [comment]
https://github.com/GeoNode/geonode-mapstore-client/issues/1559 has been created to estimate the implementation of a new UI for this.

We will have to wait for an assessment from the FE team.

**Comment by mattiagiupponi** [comment]
Fixed by this https://github.com/GeoNode/geonode/issues/12049
