### ISSUE TITLE
Metadata not included in layer zip downloads

### ISSUE THREAD

**Issue by jj0hns0n** [GeoNode/geonode#1240]
Currently metadata associated with a layer is _not_ included in layer zip downloads (either from the layer download or map download pages). It should be included. This will require some work on the java side.

**Comment by ingenieroariel** [comment]
Since GeoServer has a link to the CSW catalog, it could fetch the information and add it to the zip. The downside is that it would need to be accepted by the upstream geoserver community.

**Comment by ingenieroariel** [comment]
Many people at the sprint expressed interest in having something like this.

**Comment by tomkralidis** [comment]
Sounds like we have both short term and long approaches.  Data without metadata is like a shapefile without a projection ;)

**Comment by ischneider** [comment]
Unless something has changed, shapefile -> zip export is being done in the geoserver-geonode-ext: 
https://github.com/GeoNode/geoserver-geonode-ext/blob/master/src/main/java/org/geonode/process/batchdownload/shp/ShapeZipWriter.java

**Comment by capooti** [comment]
thanks @ischneider 
then we will try to modify the java plugin, unless you are volunteering to fix this :)

**Comment by jj0hns0n** [comment]
@ischneider Isnt this only used by the batch map download? I believe we are just using the normal shape zip wfs output format for a single layer.

**Comment by ischneider** [comment]
@jj0hns0n I could be mistaken. It could be a means to implement the desired functionality, especially if the metadata for each layer is desired in the map download.

**Comment by pjdufour** [comment]
I've tried downloading the ISO metadata and manually "attaching" to a shapefile via renaming to the same name as a shapefile, so I can view the metadata in ArcMap/ArcCatalog.  I'm running into issues.  Immediately below is what's previously worked for me (for ISO metadata written by hand).

```xml
<MD_Metadata xmlns="http://www.isotc211.org/2005/gmd" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gts="http://www.isotc211.org/2005/gts" xmlns:srv="http://www.isotc211.org/2005/srv" xmlns:gml="http://www.opengis.net/gml" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
...
```
This is what currently comes out of GeoNode
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- pycsw 1.10.0 -->
<csw:GetRecordByIdResponse xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:inspire_common="http://inspire.ec.europa.eu/schemas/common/1.0" xmlns:rim="urn:oasis:names:tc:ebxml-regrep:xsd:rim:3.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:dct="http://purl.org/dc/terms/" xmlns:ows="http://www.opengis.net/ows" xmlns:apiso="http://www.opengis.net/cat/csw/apiso/1.0" xmlns:gml="http://www.opengis.net/gml" xmlns:dif="http://gcmd.gsfc.nasa.gov/Aboutus/xml/dif/" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:srv="http://www.isotc211.org/2005/srv" xmlns:ogc="http://www.opengis.net/ogc" xmlns:fgdc="http://www.opengis.net/cat/csw/csdgm" xmlns:inspire_ds="http://inspire.ec.europa.eu/schemas/inspire_ds/1.0" xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:os="http://a9.com/-/spec/opensearch/1.1/" xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope" xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:wrs="http://www.opengis.net/cat/wrs/1.0" xsi:schemaLocation="http://www.opengis.net/cat/csw/2.0.2 http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd">
  <gmd:MD_Metadata xsi:schemaLocation="http://www.isotc211.org/2005/gmd http://www.isotc211.org/2005/gmd/gmd.xsd">
...
```

They are very similar, but GeoNode only returns xml that starts with.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- pycsw 1.10.0 -->
<csw:GetRecordByIdResponse
```

Can CSW "unwrap" the top document node for us right now with the right URL or is this something we'd have to do manually or implement ourselves?

**Comment by tomkralidis** [comment]
@pjdufour is the use case clicking `Download Layer` or clicking `Download Metadata`?

For `Download Metadata` this is a direct CSW request which always returns the `csw:GetRecordById` wrapper (as per the specification).  Note that the next version of CSW (3.0.0) will return `GetRecordById` responses without the `csw:GetRecordById` wrapper.

pycsw implements a `GetRepositoryItem` request which returns the metadata as is with no wrapper ([example](http://demo.geonode.org/catalogue/csw?service=CSW&request=GetRepositoryItem&version=2.0.2&id=3591e1d5-8460-4dd3-9fae-9f1f4eb96025)), but this only returns the native format of the metadata as uploaded originally into GeoNode and there is no ability to transform between other metadata formats (in GeoNode our native metadata format is ISO, unless uploaded in another format).

IMO this is analogous to `Download Layer` offering, for example, GML, which returns a GML payload wrapped in a `wfs:FeatureCollection`.

We 

My vote here would be for `Download Layer` to be more abstract and package up both data and metadata without wrappers and deliver to the user.

**Comment by ingenieroariel** [comment]
+1 to Tom's suggestion.

**Comment by jj0hns0n** [comment]
Hi All, I'm working with some developers (@mmanga & @yusa55) who are planning to work on this issue. Ideally we would also package up the sld of the available styles with the metadata too. Looks like the code for this on the GeoServer/Java side is here https://github.com/geoserver/geoserver/blob/master/src/wfs/src/main/java/org/geoserver/wfs/response/ShapeZipOutputFormat.java ... @afabiani do you think you could help with some guidance on this?

Also, I noticed that the metadata links do not appear on the GeoServer side any longer. @tomkralidis any ideas what happened here? I suppose that means they wont show up in the GetCapabilities etc.

**Comment by afabiani** [comment]
Hello Jeffrey,
the ShapeZipOutputFormat is an output of a WFS request and therefore there
is no way currently of packaging the SLDs inside the zip.

You should use another way to package the zip and not go directly through
the WFS service.

One option could be passing through a WPS request. In particular here

https://github.com/geoserver/geoserver/tree/master/src/community/wps-download

there's an already working WPS Process allowing to package, filter and
download packaged GeoServer layers with a lot of options.
Moreofer the process alredy package the SLDs inside the final zip archive.

Now, another matter must be taken into account in order to improve the
GeoNode download.

The WPS Processed can be executed synchronously or asynchronously. It would
be very nice to allow GeoNode schedule layer downloads trough a WPS async
request and notify the user whenever the file is ready.

As a final notice the
https://github.com/geoserver/geoserver/tree/master/src/community/wps-download
module also allows to send emails to the users with the download link.


==
GeoServer Professional Services from the experts! Visit
http://goo.gl/NWWaa2 for more information.
==

Ing. Alessio Fabiani
@alfa7691
Founder/Technical Lead

GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39  331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

**Comment by jj0hns0n** [comment]
Thanks for the insight @afabiani

This WPS extension looks like just what we may need/want! The only
documentation I see is here
http://docs.geoserver.org/latest/en/user/community/wps-download/index.html
and it doesnt mention anything about including the SLD. I do see some code
in here that looks like it does do something with the SLD.
https://github.com/geoserver/geoserver/blob/master/src/community/wps-download/src/main/java/org/geoserver/wps/gs/download/DownloadUtilities.java
Is there somewhere I can look to try to figure out how to use this. Seems
we may just need to add some code to this DownloadUtilities.java to package
up the Metadata as well as the SLDs and we would be in good shape.

If I understand correctly, we would need to modify the geonode-geoserer-ext
build to package up this extension and modify the front end to deal with
downloading from here vs the WFS. Do I have that right?

**Comment by afabiani** [comment]
Hello Jeffrey,
I'm afraid there isn't much more documentation around, but at least you can
find some good examples in the test case

https://github.com/geoserver/geoserver/blob/master/src/community/wps-download/src/test/java/org/geoserver/wps/gs/download/DownloadProcessTest.java

You are right, the idea would be to enable this extension on the
geonode-geoserver-ext and then on GeoNode simply send WPS Execute Requests
via HTTP instead of WFS HTTP GetFeature ones to GeoServer.

In order to package the metadata also, we may need to improve a bit the
method or envisage another passage in GeoNode. If I correctly understood
GeoNode downloads the metadata from PyCSW, is it right? Or you envisage to
package just the Layer metadata from GeoServer?


==
GeoServer Professional Services from the experts! Visit
http://goo.gl/NWWaa2 for more information.
==

Ing. Alessio Fabiani
@alfa7691
Founder/Technical Lead

GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39  331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

**Comment by jj0hns0n** [comment]
Yes, the idea would be to get the actual metadata from pycsw. The links
_should_ be added as metadata links in GeoServer but for some reason they
no longer seem to be. I asked @tomkralidis to look into this.

So we would have to modify this WPS process to grab this via HTTP and I
guess have some option to specify which format if there are several.

Sounds like we have a basic plan here now. @pcorti @ingenieroariel @simod
@pjdufour any thoughts/comments?

**Comment by ingenieroariel** [comment]
I am okay with this approach. Although my preference would be to have
pre-made downloadable packages that are only updated when the data or style
changes.

Would WPS be able to respect the security options?

-a

**Comment by jj0hns0n** [comment]
@ingenieroariel I think your suggested approach could work ... but probably
not until we have transaction and catalog listeners more fully implemented
later this year (under other work being done). In that case, we could
trigger an asynchronous re-generation when something changed and put the
files off somewhere for download later.

Im not sure about the security options. @afabiani any ideas on that?

**Comment by afabiani** [comment]
I'm not sure how currently GeoNode performs the request to the WFS.

Theoretically if the credentials are passed to GeoServer through the
request, the layer permissions are applied to the catalog.

If the request is sent using administrator credentials, well, in this case
you don't have any problem with layer permissions.

==
GeoServer Professional Services from the experts! Visit
http://goo.gl/NWWaa2 for more information.
==

Ing. Alessio Fabiani
@alfa7691
Founder/Technical Lead

GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39  331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.
