### ISSUE TITLE
Changes to dataset's title and abstract are not reflected into the Geoserver layer

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#12441]
## Expected Behavior
When the metadata for a dataset are saved the title and abstract of the Geoserver layer should be updated

## Actual Behavior
When the metadata for a dataset are saved the title and abstract of the Geoserver layer are not updated

## Steps to Reproduce the Problem

  1. Open the Metadata Edit page of a dataset
  2. Change contents for the title and/or the abstract fields
  3. Update metadata
  4. Open Geoserver and verify that the layer's title and abstract fields are not updated

**Comment by mkrueger-dev** [comment]
This issue seems to occur again in version 5.0.x. 

I updated the metadata (abstract) of a layer in the development demo (https://development.demo.geonode.org) via the metadata editor. Corresponding metadata in GeoServer however wasn't updated.

However updating layer metadata via xml upload persists in the GerServer backend.

**Comment by giohappy** [comment]
This looks like a regression.
We will investigate the issue.
