### ISSUE TITLE
via REST API uploaded documents to not get proper permissions

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#12616]
## Expected Behavior

**edit: clarifications**

If I **as a normal registered user** upload a document via the REST API it belongs to my user and I can delete it. It should show this:

<img width="1126" alt="firefox_RrCcekaJKe" src="https://github.com/user-attachments/assets/0cafbe08-aef7-4b02-b9f1-70ad587644ea">

## Actual Behavior

I **as a normal registered user** am unable to delete it. It does not show delete:
![grafik](https://github.com/user-attachments/assets/7abf62f2-d24c-4ce2-be2a-e90fd41c58f8)

**as admin I am able to delete the ressource**

## Steps to Reproduce the Problem

- **create a new user (registered user)**
- **use this new user account to upload a document via REST API like:**

```python
import requests
url = "https://stable.demo.geonode.org/api/v2/documents"
payload = { 'title' : 'test upload of document via rest api' }
files = [ ('doc_file', ('test.txt', open('./test.txt', 'rb'), 'text/plain')) ]
headers = { 'Authorization' : 'Basic ...' } # replaced "..." with the output of $(echo -n user:password | base64) with my credentials
response = requests.request ("POST", url, data=payload, headers=headers, files=files)
```

Open https://stable.demo.geonode.org/catalogue/#/documents

**log in as user (not admin!)**

See the delete option is missing on the new document:

## Specifications

  - GeoNode version: stable.demo (4.4.0.dev0)
  - Additional details:

**Comment by gannebamm** [comment]
@ahmdthr please take a look at this. Since I tested both development and stable demo it should not be linked to your latest PR https://github.com/GeoNode/geonode/pull/11872

**Comment by ridoo** [comment]
@ridoo Test REST API upload `v4.3.1`

**Comment by gannebamm** [comment]
additional specification to reproduce: You shall use a 'normal' user to upload. Admin /superuser will work.

**Comment by mattiagiupponi** [comment]
Hi @gannebamm did your team had time to check this issue? otherwise i can give a check on it

**Comment by gannebamm** [comment]
@ridoo , @kilichenko-pixida please check this. As stated a normal registered user shall be used NOT an admin user.

**Comment by kilichenko-pixida** [comment]
@gannebamm yes, I was able to reproduce it and ran into the same problem on the non-admin user after an API upload

**Comment by giohappy** [comment]
@gannebamm are you going to take care of this?

**Comment by gannebamm** [comment]
> @gannebamm yes, I was able to reproduce it and ran into the same problem on the non-admin user after an API upload 
> 
> 

@kilichenko-pixida please debug into the process and take a look at the permission granting process to identify the issue.

@giohappy we will try

**Comment by kilichenko-pixida** [comment]
The issue was indeed due to improper permissions handling. Both in `DocumentUploadView` that handles UI requests and in `DocumentViewSet` that handles API there is a call to `set_permissions` method and in both cases all permissions are being removed. 

The difference, however, is that in UI code, after all permissions have been removed, there is also a `resource_manager.update` call which actually includes calling `set_default_permissions` method which restores default values. 

See [PR #10](https://github.com/Thuenen-GeoNode-Development/geonode/pull/10) for the suggested fix.

I see setting permissions to None on the API side was first introduced in [7f56ebe](https://github.com/Thuenen-GeoNode-Development/geonode/commit/7f56ebee55f55b945180fc3eb6c32ca563bc48be), though I don't know whether it was a simple oversight or there quite possibly was a good reason for it that I do not understand. 

On the UI side, this permission workflow was implemented as part of big changes in [f760e0f ](https://github.com/Thuenen-GeoNode-Development/geonode/commit/f760e0fc03baacb949650e6ada248ff8b9fd4c91) from 2021.

**Comment by gannebamm** [comment]
@kilichenko-pixida please provide a PR for master, too. @giohappy please use some of our booked time to answer the questions above to make sure the PR fits the quality critera.

**Comment by kilichenko-pixida** [comment]
@giohappy here is the PR: https://github.com/GeoNode/geonode/issues/12616 , I already sent the signed license agreement to info@osgeo.org, but I guess approval is pending. Thank you.
