### ISSUE TITLE
Remote Service layers not added to new MAP

### ISSUE THREAD

**Issue by matthewhanson** [GeoNode/geonode#1607]
When creating a map from a Remote Services layer, the title shows up in the left Layers pane, but is not visible on the map.

Furthermore, the available layers when adding a layer here (GeoExplorer) do not show any Remote Services, only actual Layer objects.     If one wants to add a remote service layer you have to add the complete URL again in GeoExplorer.  Obviously not ideal.

**Comment by capooti** [comment]
I have tested it with the mapserver end point that was posted it in list a while back ago:
http://maps.iguess.tudor.lu/cgi-bin/mapserv?map=/srv/mapserv/MapFiles/RO_localOWS_test.map&SERVICE=WMS&REQUEST=GetCapabilities&version=1.3.0

Everything is working properly, specifically:
* layers are correctly registered
* layer title is correct and layer is visible in map
* it is possible to add other registered layer by choosing from the correct item in the "View available data from" list

@matthewhanson if you have an endpoint that is not behaving properly, please could you post it here therefore we could debug what is wrong?
Otherwise please close this.

**Comment by capooti** [comment]
oh I figure out after some more testing.
It seems that under same circumstances the remote service disappear from the remote server list.
Looking into this tomorrow.
