### ISSUE TITLE
Update GeoNetwork 2.10.3 csw backend auth to use Spring Security

### ISSUE THREAD

**Issue by senoadiw** [GeoNode/geonode#1867]
Greetings,

Referring to this post: https://groups.google.com/forum/#!topic/geonode-users/8QNCfRVlWbA Geonode 2.4b4 is unable to login with GeoNetwork 2.10.3 since they have updated to use Spring Security. Changing the login and logout url with "geonetwork/j_spring_security_check" and "geonetwork/j_spring_security_logout" in /usr/local/lib/python2.7/dist-packages/geonode/catalogue/backends/generic.py does not appear to fix the issue.

As a workaround which version of GeoNetwork still works with the old auth method?

Regards,

SN

**Comment by jj0hns0n** [comment]
@senoadiw I think almost all new instances of geonode are using pycsw rather than geonetwork. You can see how geonode is trying to login to geonetwork here https://github.com/GeoNode/geonode/blob/master/geonode/catalogue/backends/generic.py#L75 It would be great to have an integration test that verified that this now worked with current geonetwork. Perhaps we could ask the @GeoCat folks for help.
