### ISSUE TITLE
Remove geoserver_save signals and rely on something else

### ISSUE THREAD

**Issue by simod** [GeoNode/geonode#2015]

**Comment by ischneider** [comment]
Heh, looked again recently at these functions and saw (in the docstring of `geoserver_post_save`) 
`Save keywords to GeoServer`
And then looked at the next 320 lines of code that do all manner of things.

I've often wondered about a better approach since this has been problematic for some time. Even if it all worked correctly, doing work when a field that's not related to geoserver changes is a problem.

One might be to have the signal (or other triggering code) to look at the changes that occurred in the model and fire the appropriate responses and only those (a response being an action taken on the basis of a data change - e.g. keywords changed in model so update in geoserver). The response handlers would be/use some object to support sharing the catalog or other 'expensive' objects worthy of caching throughout the process.

By breaking these apart, it would be much easier to test handler behavior, especially with handlers that compute the change but don't actually apply it.
