### ISSUE TITLE
Uploader / Report Projection Error and Hardcode Projection

### ISSUE THREAD

**Issue by pjdufour** [GeoNode/geonode#2173]
Sometimes an upload stalls silently without an error because it cannot decode the .prj file for a shapefile.  For example, the first block below works but the second block does not.  They both represent EPSG:4326 (WGS 84), but QGIS, ArcGIS, GeoNode, and other programs are not consistent in how they write the .prj file.  Currently, I just manually copy over the .prj before uploading.

First, users should be able to hardcode in the EPSG code when uploading and pass it to the importer like they do for charset.  Second, users should be shown the importer error when there is one and the import should be cleaned out.

**Works**
GEOGCS["WGS 84", DATUM["World Geodetic System 1984", SPHEROID["WGS 84", 6378137.0, 298.257223563, AUTHORITY["EPSG","7030"]], AUTHORITY["EPSG","6326"]], PRIMEM["Greenwich", 0.0, AUTHORITY["EPSG","8901"]], UNIT["degree", 0.017453292519943295], AXIS["Geodetic longitude", EAST], AXIS["Geodetic latitude", NORTH], AUTHORITY["EPSG","4326"]]

**Doesn't Work**
GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433],METADATA["World",-180.0,-90.0,180.0,90.0,0.0,0.0174532925199433,0.0,1262]]

**Comment by ingenieroariel** [comment]
This is a great idea. A dropdown menu from geoserver compatible EPSG codes
may be better than pasting the prj in most cases, don't you think?

**Comment by pjdufour** [comment]
So where would you get the list of supported SRS codes come from?  There is a GeoServer page under "Demos" in the web UI (https://github.com/geoserver/geoserver/blob/2.6.x/src/web/demo/src/main/java/org/geoserver/web/demo/SRSListPage.java) but I can't find a REST endpoint easily.

What's the difference between REST vs. importer uploaders for this?  Is REST core geoserver and importer an extension, is that right?  It seems significant (https://github.com/GeoNode/geonode/pull/2155).

**Comment by ingenieroariel** [comment]
Importer used to be something totally separate, but it is now part of all
geoservers. I believe we should do the same for both backends and that we
can create a REST endpoint for GeoServer to give us such list.

-a

**Comment by pjdufour** [comment]
If they are both core, what's the difference between REST and importer then?

**Comment by ingenieroariel** [comment]
In the past one was core and the other wasn't. Today GeoServer has two
different methods to configure things. Each with pros and cons.

**Comment by afabiani** [comment]
The importer is able to recognize automatically if it is able or not to decode the srs WKT. If not the plugins puts the Importer Session in "NO_CRS" state allowing GeoNode to recognize it and present to the user a page where he can specify a valid CRS.

For the REST part would be nice to have a way to try to decode the CRS code using the same GeoServer approach (or maybe exposing the GeoServer Reprojection Console via the REST API) and fall back to the CRS selection if it is not able to recognize it.

In general in both cases (REST and Importer) the GeoNode uploader should be improved in order to provide more feedbacks to the users (especially in case of errors) and avoid to hang silently whenever something goes wrong, or in other words be a little more robust.

**Comment by jj0hns0n** [comment]
Im going to move this to 2.7 as we will be switching to the new django-osgeo-importer and can deal with that there.
