### ISSUE TITLE
updatelayers does not sync styles, thumbnails (and maybe other stuff)

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#2177]
This could be solved by adding a layer.save() in gs_slurp, for example here as I did for now to fix it:

https://github.com/GeoNode/geonode/blob/master/geonode/geoserver/helpers.py#L450

we will need to discuss if there is a better approach, as this way layer is saved twice even when it is uploaded the first time.

**Comment by capooti** [comment]
also, it does not sync detail_url, which cause a lot of issues.
I would be +1 now to add the layer.save() line again, until we don't find a better approach.

**Comment by afabiani** [comment]
I confirm the bug is still present in the master branch

![image](https://cloud.githubusercontent.com/assets/1278021/8826732/cfb7ffc4-3088-11e5-95be-3e3dd97dd540.png)

**Comment by capooti** [comment]
yes this has not been fixed

**Comment by mikefedak** [comment]
Ran into this yesterday on a machine running 2.4. Changed the urls in the django settings as well as the proxy url in geoserver and then ran updatelayers. Thumbnails were not updated. Went into postgres and updated it manually.

**Comment by ingenieroariel** [comment]
In the sprit of explicit is better than implicit, I propose to just add the calls to the right methods to sync styles.

If we need to do a sync style I think it is better to call that function directly instead of relying on layer.save(). the .save() function does a lot more than it should (generating a lot of network calls when all we want to do is save an object to a database).

**Comment by simod** [comment]
This looks fixed,
my test:
- drop db and thumbnails
- create db
- run updatelayers

new thumbs are generated and the styles are available in style manage.
Closing it
