### ISSUE TITLE
Leaflet layer preview support

### ISSUE THREAD

**Issue by jmwenda** [GeoNode/geonode#2267]
Issues when one changes the settings.py file to use leaflet rather than geo_ext fails to render the the tiles within the leaflet interface. Several 404's due to missing leaflet libraries, i.e http://demo.geonode.org/layers/defs/EPSG[OBJECT OBJECT].js and http://spatialreference.org/ref/epsg/[OBJECT OBJECT]/proj4js/. Might need an upgrading of the proj4js library. Additionally errors with the leaflet library spewing errors on Invalid LatLng objects.

**Comment by ismailsunni** [comment]
Any update / solution about this issue?

**Comment by ismailsunni** [comment]
I am digging into this issue and I found the problem. 

Django-leaflet takes SRID value from setting, see https://github.com/makinacorpus/django-leaflet/blob/master/leaflet/__init__.py#L84, and expect an integer (like `3857`). And this will be used in here (https://github.com/makinacorpus/django-leaflet/blob/master/leaflet/templates/leaflet/js.html#L8)

And in the geonode, there is in setting set the SRID value, but as a dictionary. See https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L690

I tried to remove it, but geonode needs it as a dictionary, see https://github.com/GeoNode/geonode/blob/master/geonode/context_processors.py#L82

My suggestion would be change the name from SRID to something else, if geonode still need to use django-leaflet. Or remove django-leaflet and use native leaflet.

**Comment by simod** [comment]
good catch, we need to rename SRID to something else.
@pjdufour ok for you?

**Comment by ismailsunni** [comment]
hi @simod

I have another solution to this problem. I put 
```
LEAFLET_CONFIG = {
    'SRID': 3857
}
```
in my `local_settings.py`. By doing this, the django-leaflet won't try to get the SRID value from the settings, and set it to `None` since 3857 is the default leaflet SRID. See https://github.com/makinacorpus/django-leaflet/blob/master/leaflet/__init__.py#L92
We can set it to other value if we need, and it will still work.

In my opinion, this is better than renaming while waiting the django-leaflet to update their code.
