### ISSUE TITLE
Resource owner should be mandatory

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#2270]
I have realized that resource owner is not mandatory:
https://github.com/GeoNode/geonode/blob/master/geonode/base/models.py#L239

though, when editing the metadata and removing the owner, the resource.save() method seems not to let this happening.

I would suggest to set this field as mandatory, as it could lead to problems in the future.
As it is a schema change, I guess we should set the milestone to 2.5?

**Comment by vdeparday** [comment]
I think, on our side, in the near future, we will work on a settings to
make it mandatory in order to ensure that each layer has an owner with a
valid email address.
As for the default, I am not sure if it should be mandatory or not by
default or what the community thinks on that. I saw your other PR fixing an
issue to make it optional too.

**Comment by capooti** [comment]
hi @vdeparday, I think maybe you are referring to a PR where the user is enforced to specify the metadata author and point of contact?
We could extend the same for the owner, but I was considering to make this mandatory also at DB level, not just delegating to the django application.
