### ISSUE TITLE
GNIP - Portals/Collections

### ISSUE THREAD

**Issue by sbenthall** [GeoNode/geonode#258]
http://github.com/GeoNode/geonode/wiki/GNIP-13---Collections

> It is proposed to add new functionality to GeoNode that allows Data Layers and Maps to be grouped together into 'Collections' that have a their own pages in GeoNode and some metadata.

In discussion, dwins has suggested this could be a 1.2 feature but that depends on additional constraints.

**Comment by jj0hns0n** [comment]
Punting to 2.5 ... I would like to merge the contrib module I have in my contrib_refactor branch https://github.com/jj0hns0n/geonode/tree/contrib-refactor/geonode/contrib/portals

**Comment by JJediny** [comment]
Related GNIP was proposed in Geonode 2015 Summit User Survey. Seems the underlying purpose is to provide a project-level categorization of all content unique to whatever project. Might be worth thinking about this differently; that instead of 'creating' portals to silo content that instead add the functionality to geonode_projects with a simple django app (controlled only in admin to add/manage content tags) to apply a high-level category or tag that acts as an appended/additional search filter (foreign key table) to resourcebase. The only thing this would do is tie into the header as pull down menu options under Layers/Maps/Documents which would globally filter search results when rendered to view. Agree on punting to 2.5+

**Comment by jj0hns0n** [comment]
@simod we should be able to do the minimum to get the UI up for this using the new collections work you did recently?

**Comment by jj0hns0n** [comment]
@simod what is the status of the collections work now? I think it should be possible to merge it right?
