### ISSUE TITLE
Thumbs are not correctly updated when changing or modifying the Layer Style

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#2652]

**Comment by capooti** [comment]
I would say it is a bug @simod

**Comment by simod** [comment]
Not sure, a thumbnail can be set manually with edit layer, which is also the only way to get the background. The option to have the whole process automatic I see it more as a feature request and would require the server side logic to fetch osm tiles (or other sources?)

**Comment by capooti** [comment]
@simod when uploading a new layer a thumbnail with the default style is correctly generated. I think it would be expected that when changing the default style of the layer the thumbnail would be updated accordingly

**Comment by simod** [comment]
totally agree, but I'd expect as well that if I have created a thumbnail with the background, the new one also has it otherwise I'll have to go and set it manually. What I mean is that imho is not a bug preventing to do something, is just that the process is not automatic. If you change the style, you have also to regenerate the thumbnail. But definitely we should fix this in the next releases.
