### ISSUE TITLE
Thumbnail Exception Handling

### ISSUE THREAD

**Issue by pjdufour** [GeoNode/geonode#2667]
We should add `try` `except` to catch any IO exceptions when creating/deleting thumbnails.  For example at:

https://github.com/GeoNode/geonode/blob/master/geonode/base/models.py#L678

IO permissions exceptions with thumbnails currently block saving layer metadata.  Should be more resilient.

**Comment by capooti** [comment]
+1

**Comment by capooti** [comment]
This breaks also updatelayers in the case where the webserver user hasn't the right permissions on the file system (read this many times on mailing list)

**Comment by harts-boundless** [comment]
Makes sense. 2c on approach -

Some code may want to try to save a thumbnail, and actually detect in the code that it was not saved if something weird happens. That argues in favor of making changes at affected call sites, rather than swallowing up the exceptions in save_thumbnail itself. There are only a few call sites in GeoNode itself, and probably not all of those are currently causing problems, so this approach would be feasible.

Other than that: when the exception is suppressed, there should still be a way to detect the problem other than just that thumbnails are not working. Error logging, perhaps. Then it falls to admins to pay attention to their logs. When as usual they don't, users will see a site where thumbnails don't work and tend to assume that it is GeoNode that is broken.

If permissions are the main failure mode seen in practice, then it might be nice to check permissions at startup and perhaps fail to start with a clear error message, so that the admin has a reason to notice and specific instructions on what to do, instead of just leaving the deployment in a broken state. While this would leave permissions issues that arose after the app already started up, those should be comparatively rare and it should be less of a big deal that the only way the error is exposed is through logs.
