### ISSUE TITLE
Default_oauth_apps for Geoserver

### ISSUE THREAD

**Issue by waybarrios** [GeoNode/geonode#2773]
@afabiani  `redirect_uris` corresponds to `GEOSERVER_LOCATION`or `GEOSERVER_PUBLIC_LOCATION`? 

````

[
{
    "model": "oauth2_provider.application",
    "pk": 1001,
    "fields": {
        "skip_authorization": true,
        "redirect_uris": "http://localhost:8080/geoserver",
        "name": "GeoServer",
        "authorization_grant_type": "authorization-code",
        "client_type": "confidential",
        "client_id": "Jrchz2oPY3akmzndmgUTYrs9gczlgoV20YPSvqaV",
        "client_secret": "rCnp5txobUo83EpQEblM8fVj3QT5zb5qRfxNsuPzCqZaiRyIoxM4jdgMiZKFfePBHYXCLd7B8NlkfDBY9HKeIQPcy5Cp08KQNpRHQbjpLItDHv12GvkSeXp6OxaUETv3",
        "user": [
            "admin"
        ]
    }
}
]
````

source:
https://github.com/GeoNode/geonode/blob/master/geonode/base/fixtures/default_oauth_apps.json

**Comment by afabiani** [comment]
Hi @waybarrios, since the fixtures are used to setup only the initial environment, GeoNode by default declares both local and public GeoServer location as http://localhost:8080/geoserver

In case you need to add more locations for your GeoServer instances, you can both:

1. Add those later on via GeoNode ADMIN Dashboard (see doc @ http://docs.geonode.org/en/latest/tutorials/admin/geoserver_geonode_security/index.html#django-oauth-toolkit-admin-setup)

2. Modify or add more "redirect_uris" (comma separated) to the fixture above **before** running "paver sync"

**Comment by waybarrios** [comment]
Hi @afabiani I just downloaded Geoserver.war from http://build.geonode.org/geoserver/latest/geoserver-2.9.x-oauth2.war But I noticed I can't access using default credentials, I mean `username:admin` `password:geoserver`

**Comment by afabiani** [comment]
I will check it. Thanks for noticing.

**Comment by afabiani** [comment]
@waybarrios I just updated the GeoServer Data Dir, the issue should be fixed now.

WAR and Zip updated on build.geonode.org.

Please make sure your GeoServer Data Dir is updated with the latest one

http://build.geonode.org/geoserver/latest/data-2.9.x-oauth2.zip

Thanks,
-A.

**Comment by capooti** [comment]
@waybarrios we can close this I assume?

**Comment by waybarrios** [comment]
for sure @capooti
