### ISSUE TITLE
Request key internal error when trying to define a new Remote Service

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#2903]
GeoNode throws a Python exception about not being able to retrieve "request" key when defining a new Remote Service.

**Comment by capooti** [comment]
Looking into this today

**Comment by capooti** [comment]
Running **the 2.6.x branch** I see several problems from the beginning, and cannot replicate @afabiani one.

First problem:
trying to create a service for the geonode demo WMS, I first get this error:
FailedRequestError at /services/register/ No store found named: geonode-demo Request Method: POST Request URL

If I press another time on the button, don't get errors when creating it, but when accessing the service page I get this error:
AttributeError at /services/2/
'Service' object has no attribute 'layer_set'
which is not a good thing because it looks like the model is missing the layers FK...

At this point, the code for services seems to be very outdated and untested, as far as I can see... I see that there are just 2 tests, which is not a good thing.

I am going to file tickets for every issue (including tests lack) and then from there we can tackle the problems. @afabiani could you please check if you still get that error? In case not we can close this one I think.

**Comment by afabiani** [comment]
closing
