### ISSUE TITLE
Google Maps Base Layer Error

### ISSUE THREAD

**Issue by gnatih** [GeoNode/geonode#3055]
As suggested in the documentation pages, I have added the following to local_settings.py

```
GOOGLE_API_KEY = "XXX"

MAP_BASELAYERS = [{
    "source": {"ptype": "gxp_olsource"},
    "type": "OpenLayers.Layer",
    "args": ["No background"],
    "name": "background",
    "visibility": False,
    "fixed": True,
    "group":"background"
}, {
    "source": {"ptype": "gxp_osmsource"},
    "type": "OpenLayers.Layer.OSM",
    "name": "mapnik",
    "visibility": True,
    "fixed": True,
    "group": "background"
}, {
    "source": {"ptype": "gxp_googlesource", "apiKey": GOOGLE_API_KEY},
    "group":"background",
    "name":"SATELLITE",
    "visibility": False,
    "fixed": True
}]
```

Doing this results in the maps viewer showing '`Google Maps API Error: MissingKeyMapError`' in the Javascript console. Does using Google maps as base map even work?

I am working with the latest Geonode code (from Github - v2.6c1)

**Comment by gnatih** [comment]
Bing maps also do not work.

**Comment by karakostis** [comment]
Bing maps work for me as:

`{
    "source": {
       "ptype":"gxp_bingsource",
       "apiKey": '########'
     },
    "title": "Satellite Bing Map",
    "group":"background",
    "name":"Aerial",
    "visibility": False,
    "fixed": True
}`

**Comment by capooti** [comment]
For Google Maps I believe this is what is needed to do:
http://stackoverflow.com/questions/32698848/openlayers-2-13-1-with-google-maps

Remember to update map base layers for existing maps after you changed the MAP_BASELAYERS setting. There is the fix_baselayers command for this purpose

**Comment by gnatih** [comment]
@capooti Thanks for the hint! 

However geonode (or geoexplorer) loads up google maps using the google script loader. To resolve the problem, I added the api key into static_root/geoexplorer/script/GeoExplorer.js (it is minified, yes). 

If somebody could enlighten me on how to rebuild this file from source, may be this can be used as a bug fix for loading google maps.

**Comment by afabiani** [comment]
Hi Jayesh,

basically you need to publish a new version of this package

https://github.com/GeoNode/django-geoexplorer

on Pipy containing the updated versions of GeoExplorer-debug.js and
GeoExplorer.js

*How to update and compile GeoExplorer*
*----------------------------------------------------------------*

You need to clone the following repository

https://github.com/geosolutions-it/geoexplorer/tree/geonode-geoexplorer


> *WARNINGS:*1. Be sure to checkout the correct branch
> *geonode-geoexplorer*2. Be sure after cloning to synchronize
> subrepositories *git submodule update --recursive*


The following command should allow you to do everything automatically

git clone --recursive -b geonode-geoexplorer
https://github.com/geosolutions-it/geoexplorer.git

After cloning the repository and the submodules, you can modify and update
the source files.

When you finished just run

cd geoexplorer
ant war

This will create the two Javascript files above into the subfolder

build\geoexplorer\WEB-INF\app\static\script

*GeoExplorer.js*
*GeoExplorer-debug.js*

*Few Notices:*
In order to make it work on Windows running a Java8 compiler I had to
modify the following files:

build.xml[19]

    <condition property=*"git.cmd"* value="git" else="git">
        <os family="windows"/>
    </condition>

to

    <condition property=*"git"* value="git" else="git">
        <os family="windows"/>
    </condition>

externals/ringojs-fork/build.xml[63]

    <target name="compile" depends="init">
        <mkdir dir="${classes}"/>
        <javac srcdir="${src}"
            target=*"1.5"*
            destdir="${classes}"
            debug="${debug}"
            deprecation="${deprecation}"
            optimize="${optimize}"
            includeAntRuntime="false">
                <compilerarg value="-Xlint:unchecked"/>
                <classpath refid="classpath"/>
                
                <compilerarg value="-Xbootclasspath/p:${lib}/js.jar"/>
        </javac>
    </target>

to

    <target name="compile" depends="init">
        <mkdir dir="${classes}"/>
        <javac srcdir="${src}"
            target=*"1.8"*
            destdir="${classes}"
            debug="${debug}"
            deprecation="${deprecation}"
            optimize="${optimize}"
            includeAntRuntime="false">
                <compilerarg value="-Xlint:unchecked"/>
                <classpath refid="classpath"/>
                
                <compilerarg value="-Xbootclasspath/p:${lib}/js.jar"/>
        </javac>
    </target>

Regards,

Alessio Fabiani

==
GeoServer Professional Services from the experts! Visit http://goo.gl/it488V
for more information.
==

Ing. Alessio Fabiani

@alfa7691
Founder/Technical Lead


GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39 331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

AVVERTENZE AI SENSI DEL D.Lgs. 196/2003

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.

The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

**Comment by gnatih** [comment]
Thanks @afabiani. How does Geonode pick up these updated files, or I will have to move them to the static_root folder manually?

**Comment by afabiani** [comment]
GeoNode picks those files from the "django-geonode" Python package.

If you want to contribute back your code to the community, you/we need to
update the version of that package.

Regards,

Alessio Fabiani

==
GeoServer Professional Services from the experts! Visit http://goo.gl/it488V
for more information.
==

Ing. Alessio Fabiani

@alfa7691
Founder/Technical Lead


GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39 331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

AVVERTENZE AI SENSI DEL D.Lgs. 196/2003

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.

The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

**Comment by gnatih** [comment]
@afabiani Submitted a PR https://github.com/geosolutions-it/gxp/pull/1 to add missing Google Maps API key.

**Comment by afabiani** [comment]
Cool thanks Jayesh,
will merge ASAP.

Regards,

Alessio Fabiani

==
GeoServer Professional Services from the experts! Visit http://goo.gl/it488V
for more information.
==

Ing. Alessio Fabiani

@alfa7691
Founder/Technical Lead


GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39 331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

AVVERTENZE AI SENSI DEL D.Lgs. 196/2003

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.

The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

**Comment by afabiani** [comment]
Udated

https://pypi.python.org/pypi/django-geoexplorer/4.0.9

will update the version on GeoNode master too.

Regards,

Alessio Fabiani

==
GeoServer Professional Services from the experts! Visit http://goo.gl/it488V
for more information.
==

Ing. Alessio Fabiani

@alfa7691
Founder/Technical Lead


GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39 331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

AVVERTENZE AI SENSI DEL D.Lgs. 196/2003

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.

The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.
