### ISSUE TITLE
GeoNode works one day and not the next. HTTP ERROR 401

### ISSUE THREAD

**Issue by TheFuzzyMenace** [GeoNode/geonode#3107]
Getting this error now. Seems like everyday it is something. I have not gotten this to work even once:
----------------------------
Tried to make a GET request to http://localhost:8080/geoserver/rest/workspaces/default.xml but got a 401 status code:   

HTTP ERROR 401

Problem accessing /geoserver/rest/workspaces/default.xml. Reason: 
    No AuthenticationProvider found for org.springframework.security.authentication.UsernamePasswordAuthenticationToken
---------------------------

**Comment by afabiani** [comment]
Please, report stacktrace of your UWSGI / HTTPD error logs. Most probably you are having configuration issues with that causing concurrent exceptions.

I'm guessing you are using Vagrant on an Apple?

@simod do you remember this same behavior with WSGI Application? What was the issue?

**Comment by simod** [comment]
@TheFuzzyMenace please use first the mailing list geonode-users@lists.osgeo.org to ask for support rather than opening tickets. Moreover as Alessio says it is in general a good rule to attach some more info to the error report and although I understand there might be a bit of frustration when dealing with FOSS, being polite on the official channels will help you in getting better and faster support.
The error can be related to Apache2, a restart of it could help but may be something else, so please attach a stacktrace in the mailing lists thread.
