### ISSUE TITLE
Use app_directories static/template instead of filesystem to make override easier from apps

### ISSUE THREAD

**Issue by olivierdalang** [GeoNode/geonode#3520]
Hi,

Filesystem loaders take precedence over app loaders both for static and templates.

This makes it impossible to override a staticfile/template from an app, preventing from adding new features in a modular fashion (e.g. an app that adds a new tab next to the about menu in `base_site.html`).
One has to manually add the static/templates folders to the `STATICFILES_DIRS`/`TEMPLATES['DIRS']`, making activating/disabling that app error prone (you can't just comment out the app in `INSTALLED_APPS`).

Unfortunately just changing the load order of STATICFILES_FINDERS (to put the AppDirectoriesFinder before the FilesystemFinder, and same idea for templates) doesn't work (didn't dig, but if doing so, at least one app overrides `base_site.html`)

But the fix should still be relatively easy (not tested though): we'd need to create a new app (e.g. `geonode.overrides`) loaded at the very top of `INSTALLED_APPS`. Then, just move everything from `geonode/templates` to `geonode/overrides/templates` and everything from `geonode/static` to `geonode/overrides/static`. Then remove `_DEFAULT_STATICFILES_DIRS` and `TEMPLATES['DIRS']` from `settings.py`.

If this seems reasonable, I'd be happy to open a PR.

Thanks for Geonode :-)

EDIT: all of this is only a problem when using geonode the geonode-project way

**Comment by olivierdalang** [comment]
And just in case, this is my current workaround (append to your `settings.py`):

```python
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Because of https://github.com/GeoNode/geonode/issues/3520 we need to manually add our templates/static folders so that they can override static files/templates
TEMPLATES[0]["DIRS"] = [os.path.join(BASE_DIR, app,'templates') for app in SPCNODE_APPS] + TEMPLATES[0]["DIRS"]
STATICFILES_DIRS = [os.path.join(BASE_DIR, app,'static') for app in SPCNODE_APPS] + STATICFILES_DIRS
```

**Comment by afabiani** [comment]
Hi,
not sure I understood what you want to do. In the most recent versions of
GeoNode we enabled all pages to inherit from

https://github.com/GeoNode/geonode/blob/master/geonode/base/templates/geonode_base.html


Whenever you need to add a contrib app willing to extend the base page, you
can just override the "geonode_base.html" in order to have such changes
reflected everywhere and load your contrib app as last one in the
INSTALLED_APPS

e.g.:
https://github.com/geosolutions-it/geonode/blob/afg_risks_contrib/geonode/contrib/risks/templates/geonode_base.html

adds a new Tab to the whole GeoNode portal when enabling the "risks"
contrib module.




Regards,

Alessio Fabiani

==
GeoServer Professional Services from the experts! Visit http://goo.gl/it488V
for more information.
==

Ing. Alessio Fabiani

@alfa7691
Founder/Technical Lead


GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39 331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

AVVERTENZE AI SENSI DEL D.Lgs. 196/2003

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.

The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

**Comment by simod** [comment]
@olivierdalang you can also consider using the geonode-project which is used to extend/override geonode and does something similar to what you suggested https://github.com/GeoNode/geonode-project

**Comment by olivierdalang** [comment]
@afabiani 
Thanks for that info. I wasn't aware of that (currently using 2.6) and it indeed makes some overrides possible. Actually this is using the same fix I described (moving the files from filesystem template folder to an app templates folder).

But the issue remains for all other templates/static files in `geonode/static` and `geonode/templates`. For instance, to override `geonode/templates/about.html` or `geonode/static/geonode/img/logo.png`.

Of course there are possible workarounds, but it's much more involved.

@simod 
Thanks for that too. I'm indeed using the geonode-project as inspiration. It its `settings.py` you see 
```
# Additional directories which hold static files
STATICFILES_DIRS.append(
    os.path.join(LOCAL_ROOT, "static"),
)
```
which is precisely the hack I mentioned to make that override happening (but working for one app only).  
The django way would be to simply have your templates/static folders in your apps module and let each app override any template/staticfile depending on their order in INSTALLED_APPS.

Actually it's pretty clear : file system directories is meant for django projects, but geonode should also work as a django app.

**Comment by afabiani** [comment]
@olivierdalang nevertheless if you would like to submit a PR (based on master branch) I will be happy to test it.

Also on the issue it would be good to summarize some use cases to reproduce the behavior in order to add also testes to the PR accordingly.

**Comment by francbartoli** [comment]
@olivierdalang can you explain better what the geonode-project is missing for that overriding problem?
Sorry but the limitation you mentioned is not quite clear to me. I think we can have within a GN project 2 different apps which override 2 different templates just simply extend them as long as follow the same original path
