### ISSUE TITLE
Quick installation documentation is obsolete

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#3552]
We need to upgrade this documentation, which still refers to Ubuntu 14.04 and GeoNode 2.4
http://docs.geonode.org/en/master/tutorials/install_and_admin/quick_install.html

**Comment by DarnelleF** [comment]
attempting to install  from [this](http://docs.geonode.org/en/master/tutorials/install_and_admin/geonode_install/create_geonode_db.html) on ubuntu 16.04.02
first off i cloned from master since the github link included in the requirement.txt wasnt connecting

and running paver hard_reset  results in this error
`pavement.py line 45`
`no module named my_geonode.settings`

**Comment by t-book** [comment]
@afabiani  I think this is finished as well. I´ve tested it some time ago and if I remember correctly all installed quick nice and smoothly. Docs says 16.04 as well ;)
