### ISSUE TITLE
Add status message on GeoNode session "access_token" validity

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#3563]
OAuth2 access_tokens currently have a timeout. Once their validity expires, protected layers are no more accessible by the logged in user, unless he logs out and in again.

It would be very helpful to let GeoNode check for access_token validity periodically and send a warning message to the user.

GeoNode should also provide a small button to refresh it and either generate a new one or extend its validity.

**Comment by t-book** [comment]
+1 
- Addition: If last_activity < allowed_inactive_time (timeout),
 log-out user and redirect to login page with some message what happend.

**Comment by capooti** [comment]
I think this is not trivial and has caused headaches to many users for one of our instance. What is the OAuth2 access_token timeout? Isn't it possible to just logout the user when the token expires?

**Comment by capooti** [comment]
Instead than sending the warning, wouldn't be possible to have Django automatically request a new token if the other is expired?

**Comment by afabiani** [comment]
There should be a way to refresh the tokens. Nevertheless, GeoNode should somehow open a pop-up coherently asking the user to refresh the session under a certain time IMHO.
As soon as I'm able to find some time and resource to dig more into this I'll propose a more detailed solution.

**Comment by capooti** [comment]
Sound great! thanks @afabiani

**Comment by capooti** [comment]
This is really causing confusion to users, as when the token epires:
* private layers become not accessible
* data editing stops working
* style editing stops working

Looking at https://django-oauth-toolkit.readthedocs.io/en/latest/settings.html#authorization-code-expire-seconds I am confused about ACCESS_TOKEN_EXPIRE_SECONDS and AUTHORIZATION_CODE_EXPIRE_SECONDS. I believe that increasing ACCESS_TOKEN_EXPIRE_SECONDS should help, while I am unsure of AUTHORIZATION_CODE_EXPIRE_SECONDS which is recommended to be set at 600 seconds.

According to this: https://github.com/jazzband/django-oauth-toolkit/issues/93
we should be able to set ACCESS_TOKEN_EXPIRE_SECONDS to a very high value to solve this issue.

Any thoughts on this?
For now I am trying to increase ACCESS_TOKEN_EXPIRE_SECONDS to a very high value and let's see if this helps.

**Comment by giohappy** [comment]
Generally having an automic token refresh mechanism would be the best option. This is supported by oauth toolkit and by default REFRESH_TOKEN_EXPIRE_SECONDS is set to None, which means that the refresh token can be always used to obtain a fresh access token.
GeoNode could refresh the token transparently whenever a request is submitted with an expired access token.

The AUTHORIZATION_CODE_EXPIRE_SECONDS shouldn't be changed, and must be kept low. It's the max time an oauth client is allowed to exchange the initial authentication code for an access token, the initial handshake. This param doesn't affect the access token exipration.

Anyway, IMHO, we could also decide to remove the access token expiration. Many services do it, like Github. The token from Github never expires because it's considered an alternate method to user/pw authentication.
I think GeoNode should do the same.

**Comment by giohappy** [comment]
Generally having an automic token refresh mechanism would be the best option. This is supported by oauth toolkit and by default REFRESH_TOKEN_EXPIRE_SECONDS is set to None, which means that the refresh token can be always used to obtain a fresh access token.
GeoNode could refresh the token transparently whenever a request is submitted with an expired access token.

The AUTHORIZATION_CODE_EXPIRE_SECONDS shouldn't be changed, and must be kept low. It's the max time an oauth client is allowed to exchange the initial authentication code for an access token, the initial handshake. This param doesn't affect the access token exipration.

Anyway, IMHO, we could also decide to remove the access token expiration. Many services do it, like Github. The token from Github never expires because it's considered an alternate method to user/pw authentication.
I think GeoNode should do the same.

**Comment by capooti** [comment]
@giohappy thanks for the great analysis.
In our case increasing ACCESS_TOKEN_EXPIRE_SECONDS didn't improve the situation. I agree that AUTHORIZATION_CODE_EXPIRE_SECONDS should not be changed.
Looking at your explanation: so, django-oauth-toolkit doesn't have a setting to have the token never expire? For our case your solution seems good (custom token validator) as we don't use social logins.

**Comment by giohappy** [comment]
@capooti do you mean that incrising ACCESS_TOKEN_EXPIRE_SECONDS doesn't take any effect?

**Comment by giohappy** [comment]
the token expiration time from settings only affect logins through an oauth2 flow, i.e. when you connect from Geoserver GUI.
On the other hand GeoNode programmatically creates an access token on login from GeoNode itself, and assigns 1 day expiration which is fixed in the code: https://github.com/GeoNode/geonode/blob/master/geonode/base/models.py#L1467
We should have this time defined through settings, and we could decide to increase it to one year? 10 years? by default to simulate a never expiring token. Obviously having an everlasting token has its security downsides, so if we have the option to set it everybody is free to decrease or increase it.
What's your opinion @afabiani?

**Comment by afabiani** [comment]
@giohappy @capooti I just created a small patch accordingly to the Giovanni outcomes, which whom I agree.

https://github.com/GeoNode/geonode/pull/4164

Paolo you might also want to consider the use of IDTokens. Their are meant to reflect the concept of permanent tokens associated to users' identities

http://localhost:8000/en/admin/oauth2_provider/idtoken/add/
