### ISSUE TITLE
cart template is not working when using S3 storage with cloudfront

### ISSUE THREAD

**Issue by ewsterrenburg** [GeoNode/geonode#3738]
cart.js `(geonode/static/geonode/js/search/cart.js` is using a hard-coded, relative path to its templateUrl (`/static/geonode/js/templates/cart.html`).  As a result, the cart does not function when using S3 cloudfront for the static files.

```
    .directive('resourceCart', [function(){
      return {
        restrict: 'EA',
        templateUrl: "/static/geonode/js/templates/cart.html",
        link: function($scope, $element){
          // Don't use isolateScope, but add to parent scope
          $scope.facetType = $element.attr("data-facet-type");
        }
      };
    }])
```

I can make it work with a hard-coded url as follows:

```
    .directive('resourceCart', ['$sce', function ($sce){
      return {
        restrict: 'E',
        templateUrl: $sce.trustAsResourceUrl("https://d13ohp4r01gn9d.cloudfront.net/static/geonode/js/templates/cart.html")
      };
    }])
```
I'd have preferred to send a pull-request, yet Angular already gave me a headache figuring out how to use `$sce` (should this be `trustAsResourceUrl` or some of the other options?). I can see that some settings are made available in `search.js`, yet I fail to see how the `STATIC_URL` can be made available in `cart.js` to come up with a real solution...

**Comment by ewsterrenburg** [comment]
Hi Alessio,

Conceptually, it shouldn't be that hard: if STATIC_URL can be made available in the cart.js . I may look into this, yet at the moment, I'm not confident my javascript (and especially Angular) proficiency is good 
enough to provide a robust fix and pull-request, so for now I will most likely use the ugly work-around with a hard-coded url in the source.

With regard to reproducing and testing the issue: I started noticing this when starting to use Amazon Cloudfront as a CDN for the static files following  [this tutorial](https://medium.com/@jorlugaqui/django-django-compressor-s3-and-cloudfront-step-by-step-part-2-3abb1b6f9df2). However, you can easily reproduce and test it using another value for STATIC_URL then the standard **static**, for instance if you change it to:
`STATIC_URL = '/mystaticfiles/'`
you will lose the cart.

**Comment by ewsterrenburg** [comment]
Small addition to testing / reproducing:

Since Angular does not like urls from different locations, the `$sce.trustAsResourceUrl(` is required if static files are served from another domain.

**Comment by t-book** [comment]
Hi Erwin,

just thinking out loud. First I thought this could be a good use case for inline templates.

```
...
template:`
<div id="composerCart" class="panel panel-default">
  <div
    class="panel-heading"
    ng-bind="'Selected ' + (facetType | default_if_blank : 'objects') | title "></div>
  <div
    ng-show="!cart.getCart().items.length"
    class="panel-body">
    <p>Add {{ facetType | default_if_blank : 'objects' }} through the "checkboxes".</p>
  </div>
  <ul class="list-group">
    <li class="list-group-item clearfix" ng-repeat="resource in cart.getCart().items">{{ resource.title | limitTo: 25}}{{ resource.title.length > 25 ? '...' : '' }}<button class="btn btn-default btn-xs pull-right" ng-click="cart.removeItem(resource)"><i class="fa fa-remove fa-lg"></i></button></li>
  </ul>
</div>`
...
```
But this won´t work as we have to deal with Django template vars.
As there is no build step  (if so we could inject the correct path f.e. with webpack) a pattern that you sometimes find is that the var is populated somewhere in your html template for later access:


<pre>body data-static="{{ STATIC_URL }}" </pre>


And later in your js .. to dynamically build your URL.

<pre>
var static_dir = document.getElementsByTagName("body")[0].getAttribute('data-static');
</pre>

Not much, but if I find something else I´ll let you know !

Cheers,

Toni

**Comment by GeoTob** [comment]
This applies to a number of other files (not just cart) as well.

Running this snippet against 66e7985d86 fixes things for me, should be fairly simple to adapt to master.

```bash
# Add static base url as global variable (in case static files are on S3 or similar) at ln 206
sed -i "206i        var staticUrl = '{% static '' %}';" geonode/templates/base.html

# Replace js template loader directory
grep -l -r "baseUrl: siteUrl" geonode/static | xargs sed -i "s/baseUrl: siteUrl + 'static\//baseUrl: staticUrl + '/g"
sed -i 's/siteUrl + "static\//staticUrl + "/g' geonode/static/geonode/js/search/cart.js
```

**Comment by GeoTob** [comment]
The snippet above works against master currently, @afabiani I'm happy to open a PR if you like?

**Comment by t-book** [comment]
@GeoTob Do you have the possibility to test this on docker + dev setup (paver) as well?

**Comment by GeoTob** [comment]
@t-book definitely works on docker, which is what I'm developing against (in fact, the snippet is part of my dockerfile). Can't get the local dev setup to work though, and not sure if I'll have much time to try this week. Still, a PR against master is easy enough if someone else can pick up the testing.

**Comment by t-book** [comment]
@GeoTob thanks! I can check manual install and django runserver for you.

**Comment by GeoTob** [comment]
@t-book PR is up

To test, collect static assets and have Django serve them -- all should work as expected. Then configure Geonode to use different storage provider, repeat and all should continue to work. I have a dev environment online using this patch, can share instructions in a private channel.

**Comment by GeoTob** [comment]
@t-book  So the PR works fine against 2.8.x, but not with Mapstore2. In my initial excitement 

> definitely works on docker, which is what I'm developing against

I had completely forgotten to turn off the `DEBUG` flag when testing with master.

The main reason it's not working against master is that django-mapstore2-client has multiple issues around static file paths:

1. It's using `{{ STATIC_URL }}` in templates instead of `{% static 'filename' %}`. The former is just a django setting, the latter actually queries the storage provider for the correct url.
2. The js has multiple hard-coded references to `/static/mapstore/XYZ` which makes dynamic url generation extremely hard. 
3. The js also loads some things through the geonode proxy (e.g. `mapstore/dist/../MapStore2/web/client/translations/data.en-US`).
4. There are a few other hard references to URLs in django-mapstore2-client that may cause headaches further down the track, such as using `printUrl: "{{ SITEURL }}gs` when geoserver_url can be different and configured through env variables.

In terms of progress:
(1) Is fairly easy to fix by loading the `static` template tag in all templates and replacing `{{ STATIC_URL }}` with the correct tag.
(2) Is harder to fix as the `django-mapstore2-client` repo doesn't include the js source for me to inspect. The only sensible way I can think of is adding a redirect from `/static` to `StorageProvider.url` to Geonode's urls.py. Not particularly elegant unfortunately, but it works in this case and may help against future django extensions hard-coding static URLs.
(3) One can add the StorageProvider host to `PROXY_ALLOWED_HOSTS` dynamically. However I'm now seeing receiving 404s from the internal proxy when the remote file clearly exists (I can access the remote url just fine).
(4) Haven't even looked at yet.

I'm going to stop here for tonight because this is turning into a fairly major issue, much of which is probably better raised against the `django-mapstore2-client` project. There's also a question here around whether this behaviour is desired at all, or if the project maintainers are happy with a tight coupling of the various components (and it's consequently OK to hardcode url paths).

You may want to test this against 2.8, though not sure there's much point given its imminent deprecation :-)

**Comment by GeoTob** [comment]
Some progress here:

I have a working fork of `django-mapstore2-client` at https://github.com/GeoTob/geonode-mapstore-client/pull/1/files, which essentially uses Django's static url provider to generate static URLs.

I've also added a redirect from `/static` to `StorageProvider.url` into the settings. This is for those URLs in the JavaScript that depend on static files at `/static`. There has to be a better way to set up the js though this though, maybe by using a global `staticUrl` variable set by Django?

The only thing not yet working is print, but we'll get to the bottom of that.

**Comment by afabiani** [comment]
Currently if not possible to tweak the templates somehow, I guess the best option would be to set global JS variables.
