### ISSUE TITLE
Metadata fields exceeded limit error on update

### ISSUE THREAD

**Issue by NyakudyaA** [GeoNode/geonode#3828]
# Problem
I have installed Geonode using the rancher [recipe](https://www.geo-solutions.it/blog/one-click-geonode-with-rancher-and-docker/).

Version installed
![build](https://user-images.githubusercontent.com/2510900/41234178-c38047f0-6d8b-11e8-9aa7-512f7c6a5bdd.png)

I have uploaded data with associated metadata but when I try to update some fields/text in the metadata I encounter an
![error_maximum_limit](https://user-images.githubusercontent.com/2510900/41234503-aa0d8d18-6d8c-11e8-908b-3e05222e1e8d.png)
 error message.

How is the metadata upload saved in the database during layer upload but updating the data results in errors?
**Dataset:**
[nfepa_rivers.zip](https://github.com/GeoNode/geonode/files/2090163/nfepa_rivers.zip)

**Comment by afabiani** [comment]
Hi,
whenever you provide an XML along with the spatial data, it is preserved as is.

If you want to update metadata through the GeoNode interface, you should fulfill its limitations.

Otherwise you can continue updating the metadata by modifying and uploading again the XML file

![image](https://user-images.githubusercontent.com/1278021/41338243-e1b891de-6ef1-11e8-96db-40fe19a65ee7.png)
