### ISSUE TITLE
Where did 2.8.0 branch go? 

### ISSUE THREAD

**Issue by lhcramer** [GeoNode/geonode#3907]
MapStory relies on the 2.8.0 branch which seems to have been deleted. Can someone please advise?

**Comment by afabiani** [comment]
@lhcramer accordingly to the last PSC meeting 2.8.0 branch should not exist anymore, since it is referenced by the 2.8 tag instead https://github.com/GeoNode/geonode/releases/tag/2.8

It was deleted by @francbartoli a couple of days ago.

That said, it would be better if you can move to branch 2.7.x for the development. If not possible or if you need some time to switch, I guess we can restore the branch temporarily.
Please let me know.

**Comment by lhcramer** [comment]
I will reach out to you (@afabiani) and @francbartoli via email shortly. We have a temporary solution but would like to make sure we are following community guidelines going forward. Thanks for the quick response. I'll go ahead and close this issue so it's not cluttering your backlog. 

Thanks Again.
