### ISSUE TITLE
Zoom level in layers

### ISSUE THREAD

**Issue by rodrigodinizrosa** [GeoNode/geonode#3923]
Hey guys, in my site: http://novoiede.fjp.mg.gov.br/layers/geonode:mg_distrito_2018_fev

The zoom is always in 19 and showing the center of the world, in my case i need to see Brazil. 

All my config in geoserver reviewed, but i can't find a way to solve this issue.

**Comment by afabiani** [comment]
@rodrigodinizrosa is this happening on this layer only? Probably GeoNode was not able to set correctly the layer bounding box and CRS on the DB.

Login as Administrator, go to /admin/layers/layer/ and search for the layer name.

Click on layer id and check that bbox and CRS are coherent

See the example below.

![image](https://user-images.githubusercontent.com/1278021/45827685-44157100-bcf7-11e8-89e8-7b1f4b21afa1.png)

**Comment by rodrigodinizrosa** [comment]
Hello @afabiani. Thanks for the feedback. We changed to the Wsg4 standard, we checked every box - and everything is ok, but it did not work.

We changed the metadata region in the geoserver too and reviewed the tile caching and grids subset, but unfortunately it did not work.

Could you guide us?

**Comment by rodrigodinizrosa** [comment]
Here, i share a photo of our page configuration:

https://drive.google.com/file/d/1QVuNMxOhHpLS7uv99Aun4F6FiYGazC_W/view?usp=sharing

Many thanks

**Comment by afabiani** [comment]
@rodrigodinizrosa any chance to perform an update to the new geonode code? There should be a fix allowing you to solve this issue.

After having updated your codebase with master branch, you will need to run several management command in order to align your datasets:

`DJANGO_SETTINGS_MODULE=<yours.settings> python manage.py set_all_layers_metadata`
`DJANGO_SETTINGS_MODULE=<yours.settings> python manage.py collectstatic`

**Comment by rodrigodinizrosa** [comment]
Sure @afabiani. I will procede to update version and test it. After that i bring with  feedback. 

Many thanks.

**Comment by rodrigodinizrosa** [comment]
hey @fabiani - i proceeds with update and works fine! Thanks for the assistance.
