### ISSUE TITLE
GNIP Make GeoFence efficient for GeoNode instances with a large number of layers

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#3944]
After testing GeoFence with a GeoNode instance with a very large number of layers (about 25,000) and users (for a total of more than 700,000 GeoFence data rules) it came out that GeoFence performances are heavily affected.

There are 2 major issues in such a scenario: 

1) setting the permissions for a single layer from the GeoNode "set permissions" widget become very slow (up to 2/3 minutes in our tests)

2) every time an action that changes the GeoNode permission system happens (a layer upload, a layer creation, setting the permissions for a specific layer), this will invalidate the GeoFence cache and the GeoNode user has to wait for GeoFence to re-generate the whole cache - which typically slows down with the increase of the layers number (up to 4 minutes in our tests)

After some debugging and some discussion with @afabiani on the #geonode gitter channel, these are our findings in order to mitigate the two issues:

1) instead than setting the GeoFence permissions using the GeoFence REST API, use a direct connection to the database. We have a prototype of this here (will work only for GeoFence on PostGIS, not on GeoFence for H2 which is the default): https://github.com/GeoNode/geonode/blob/3f62d58a533a806c06ae86b5e6fb6c9327808426/geonode/security/utils.py#L315

2) Asynchronous GeoFence rules propagation. Unfortunately the GeoFence cache invalidation cannot be avoided and cannot be done on a layer by layer basis. Therefore a solution would be to "buffer" the cache invalidation calls and run them asynchronously instead of sending them synchronously every time there is a permission change on a layer.

**Comment by afabiani** [comment]
Just few clarification and updates on this, following @capooti proposal and @olivierdalang observations.

* The idea is to make this optional. Of course, this is still a proposal, so technical details must still come. First implementation examples from @capooti show the possibility of controlling the GeoFence rules backend and switch between REST APIs and direct DB access. Don't how much work would be to make the DB backend configurable. A first implementation using PostGIS would be the best choice anyway.

* A lot of work has been done on Dockerization, both on GeoNode and GeoNode Project recently. Right now the docker setup supports Celery and Async mode by default. It can be controlled through env variables.

About the latest observations from @olivierdalang basically your idea could be feasible but will force you to hide GeoServer/QGis instances behind a proxy. Also forcing people to use nginx could not be an option. My feeling is that we are very far from having a fully "proxified backend for OWS services, and also it is not really an option for enterprise setups which might need GeoServer/QGis Server endpoints accessible even without passing through GeoNode. Probably an option to evaluate could be to write some "mods" for nginx/apache2 allowing the web server to perform A&A through GeoNode, something similar to a CAS. Nevertheless, I still think this is a bit out of the scope of GeoNode. This is something that should concern DevOps and System Administrators. We have sample infrastructures which use Keycloak as external Auth system along with separate clusters of GeoNode and GeoServer. So, this is feasible, but it is not a concern of the application.

GeoServer proxy on GeoNode is at a good stage, it still needs some improvements. Currently, it is able to expose Basic Auth in order to retrieve the user A&A and filter the layers accordingly. However, as I said above, people still need to access GeoServer endpoints directly. GeoServer needs to know how to authorize layers independently from the proxy IMO.

**Comment by capooti** [comment]
@olivierdalang the idea is to use REST if GeoFence has a default configuration, therefore H2 (i.e. 'internal' in settings.GEOFENCE_URL) and use psycopg in the other case.

I like the idea of fully proxy GeoServer, we were already thinking about this in the past (/cc @ingenieroariel ), though as @afabiani says it is not trivial and there are a number of drawbacks.

For Celery: I would just add a django command and a Celery task which call the same function (for example in geoserver/utils.py). It will be up the admin the decision to schedule the task in Celery (if it is in his deployment) or the django management command in crontab.

**Comment by ahmednosman** [comment]
@olivierdalang idea as pointed out might have some drawbacks as pointed out by @afabiani however I believe the value of the implementation is enormous and outweights the drawbacks, in addition to the role of GeoNode it will also serve as an authentication endpoint for more GIS servers, you can expect adding a lot more servers like mapserver, mapnik and arcgis server and all being authenticated from the same end point. At the end it does not have to be an either or questions there could be more than one mode for authenticating geoserver
