### ISSUE TITLE
I can't download Windows Binary Installer

### ISSUE THREAD

**Issue by Baju3D** [GeoNode/geonode#4050]
I have tried downloading many times http://build.geonode.org/windows/GeoNode-2.6.x.exe but it didn't work. The server says connection timed out. Please help me.

**Comment by t-book** [comment]
Hi build.geonode.org does not exist anymore. Unfortunately I do not know of some other place where to get it. Unsure if this is still up to date: https://github.com/GeoNode/geonode-win-installer
It looks like the repository to build the installer.

**Comment by tjkautz** [comment]
Any change the Windows Binary Installer could be rebuilt since the Geonode Build server has been moved to the new server? We've tried to build the installer but have struggled a bit. The Windows Binary Installer was just so helpful and useful. If that is not possible, would be possible to get a more 'end-user' friendly readme for the compiler and manual install? Thank you!

**Comment by ahmednosman** [comment]
Try cartoview windows installer it contains geonode. An upgrade is coming
soon

**Comment by TimWanner** [comment]
until when can this upgrade be expected?

**Comment by simod** [comment]
We rely on cartoview for the installer
