### ISSUE TITLE
upload sld not working

### ISSUE THREAD

**Issue by konservasi** [GeoNode/geonode#4052]
I am using geonode 2.18rc1 with apt command. Right now, when I upload a sld, the upload succeed but I cant see the new files added in style section in geoserver. I have tried to used this fix https://github.com/GeoNode/geonode/commit/a74b3cb9114881c525ef271eda5ee86016e1afcf there is no luck. 

when I upload a sld in geoserver,there is no respond in style editor. When I copied xml files (from udig software) there is a error message "Field 'styleEditor' is required". I am confused that the styleEditor field is fill in xml files. 

need help. thanks before

**Comment by t-book** [comment]
Do you mean 2.8 instead of 2.18? The apt installation cannot be suggested at all by now. Currently there are no developers who care for this installation. I strongly recommend installing by 'source' by use of geonode project or by using the docker build. Regarding installing with geonode-project this video will guide you through the setup: https://vimeo.com/278003647 further find here an ansible playbook which installs the whole stack for production using geonode-project as well https://github.com/csgis/geonode_ansible

**Comment by konservasi** [comment]
I mean latest version of geonode,I am not sure what version is that. I am not familiar with docker. there are a lot of data there. there will be a lot of effort to reinstall the server and make docker installation
--
Sent from myMail for Android

**Comment by afabiani** [comment]
if you are using "master" branch, try to update it. In particular the last commit

https://github.com/GeoNode/geonode/commit/dbf42d6c73dfbe45a8b07e4ad20420d7492fddc3

should address this kind of issues.
