### ISSUE TITLE
GeoNode Proxy should be using OAUTH2 Bearer Header now

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#4168]
With the latest improvements to GeoServer 2.14.x + now the OAuth2 plugin supports Bearer AUTH Headers also.

The GeoNode Proxy should be updated in order to be now fully compliant with the protocol and allow authorized requests to pass through it.

The advantages are that the OWS endpoints will be fully supported from external clients, like QGIS as an instance, with Basic Auth also.

**Comment by capooti** [comment]
@afabiani I see latest build of https://build.geo-solutions.it/geonode/geoserver/latest/geoserver-2.14.x.war is from 19-12-2018. Does this work with that version?

**Comment by giohappy** [comment]
@capooti yes, I was testing it on the latest available build and I confirm it works

**Comment by frafra** [comment]
Wouldn't switch from `/geoserver` to `/gs` require a redirect for backwards compatibility?

**Comment by giohappy** [comment]
@frafra the two endpoints are used for different purposes. They're not alternatives.

1.  /geoserver can be used to access the web UI
2. /geoserver can also be used instead of /gs in case of public layers, because in this case you don't need the proxy for aithentication. 

The latest point is not managed automatically, but it could be in the future (switching the links to /geoserver or /gs based on layers permissions), but it can be used now if you now this. This avoids hitting the GN proxy when not strictly required.

**Comment by frafra** [comment]
Oh, ok, thank you @giohappy.

**Comment by giohappy** [comment]
Just to give you some more context @frafra initially the public location was /geoserver (except for Geoserver REST API requests, that needed to be forwarded with a privileged user) because we only supported Bearer token auth. Having a bearer token was enough because Geoserver is able to verify and get the user identity through its oauth2 extension for GeoNode. 

The problem was that Basic Auth wasn't possible, for example from QGIS, because in that case you needed a Geoserver user instead of a GeoNode user. So we decided to proxy all the requests through GeoNode (/gs) so that WMS clients can use Basic Auth with GeoNode credentials.

This means that
- for public layers
- for requests containing a Bearer Authoriation header
- for requests containing the "access_token" query parameter

/geoserver endpoint can still be used, avoiding the path through GeoNode proxy.
