### ISSUE TITLE
Geofence permissions incorectly read and returns all layers in QGIS

### ISSUE THREAD

**Issue by NyakudyaA** [GeoNode/geonode#4275]
# Problem
I have setup geonode instance using docker and set up a user to access the layers.

The `testuser` belongs to a group `Geonode-editor`

![test-user](https://user-images.githubusercontent.com/2510900/53971411-91e72f80-4105-11e9-9bab-b896a30e712a.png)

I have edited the permision for the layers 
![lyr](https://user-images.githubusercontent.com/2510900/53971640-f5715d00-4105-11e9-9f5b-e3176b07d22d.png)

The second layer
![second-layer](https://user-images.githubusercontent.com/2510900/53971729-19cd3980-4106-11e9-9dd2-ca8172923808.png)

When accessed using the user `testuser` I can access the correct layers
![test-view copy](https://user-images.githubusercontent.com/2510900/53970953-834c4880-4104-11e9-821a-3d14b7170327.png)

I then get the access token for that layer and try to access it in QGIS

In QGIS I try to access the layers using the ows request and access token for the layer `testuser` has permisions against
![access-token](https://user-images.githubusercontent.com/2510900/53971932-88aa9280-4106-11e9-8ea2-c6ace922b929.png)

The end result is that I get access to all the layers regardless of `testuser` only having access to a single layer in Geonode.

# Solution
Make it happy

PS. I am using docker and master branch

**Comment by afabiani** [comment]
@NyakudyaA are you using access_token from the connected user?

Also, I kindly suggest to use the geonode proxy with basic auth

<geonode_host>/gs/ows
<geonode_host>/gs/wms
<geonode_host>/gs/wfs
<geonode_host>/gs/wcs

**Comment by NyakudyaA** [comment]
> @NyakudyaA are you using access_token from the connected user?

Yes I am using access token from the connected user.
> 
> Also, I kindly suggest to use the geonode proxy with basic auth
> 
> <geonode_host>/gs/ows
> <geonode_host>/gs/wms
> <geonode_host>/gs/wfs
> <geonode_host>/gs/wcs

I am using the request as specified in the metadata for that layer

Example 

http://localhost:80/gs/wms?layers=geonode%3Andvi_name&service=WMS&format=image%2Fpng&request=GetMap&height=550&width=330&bbox=301790.031250000000000%2C6402727.500000000000000%2C302500.062500000000000%2C6403908.000000000000000&srs=EPSG%3A32720&access_token=tKxKwkP27ADcLNarxc2YVls9zBNJ9f

**Comment by lolob** [comment]
@NyakudyaA  I'm also having the same problem too. Any tips?

**Comment by lolob** [comment]
> @NyakudyaA are you using access_token from the connected user?
> 
> Also, I kindly suggest to use the geonode proxy with basic auth
> 
> <geonode_host>/gs/ows
> <geonode_host>/gs/wms
> <geonode_host>/gs/wfs
> <geonode_host>/gs/wcs

@afabiani Could you share with me how to do it the above-mentioned? At the moment, if I use the `<geonode_host>/gs/ows` , qgis3.4 will pull all the public and private layers (suppose to be hidden). And, if I disabled the global service in geoserver settings, geonode failed to list and display my upload layers. Please guide. Thanks.

Geonode 2.10rc
Geoserver 2.14

**Comment by NyakudyaA** [comment]
> @NyakudyaA I'm also having the same problem too. Any tips?

@lolob I haven't found any workaround for now.

**Comment by afabiani** [comment]
@lolob @NyakudyaA I just tested a clean version of master branch and I cannot reproduce the issue.

Can you please explain what are you doing exactly?

This is what I did:

1) created a standard "test" user
2) uploaded a 4 shapefiles using "admin"

![image](https://user-images.githubusercontent.com/1278021/56644579-41f40600-667c-11e9-881e-4b72dd3bcfbb.png)

3) changed view permissions (WMS service) to one of them, "tasmania_boundaries"

![image](https://user-images.githubusercontent.com/1278021/56644644-618b2e80-667c-11e9-8f22-1ef55b9f6b89.png)

4) trying to connect through QGis

![image](https://user-images.githubusercontent.com/1278021/56644693-78ca1c00-667c-11e9-98c3-41dfba7fcbb8.png)

![image](https://user-images.githubusercontent.com/1278021/56644754-9e572580-667c-11e9-82d4-32e2edfdcddc.png)

![image](https://user-images.githubusercontent.com/1278021/56644777-ab741480-667c-11e9-8bf0-f6ffe98cf05a.png)

It might be an issue of the docker setup. I remember an old version having issues with HAYSTACK SEARCH.
The fact that you disabled one layer but the counter still saying "2 layers" available is suspicious.

The normal behavior when connecting with "test" user should be the following one:

![image](https://user-images.githubusercontent.com/1278021/56644926-f5f59100-667c-11e9-8dce-1b1330213826.png)

Maybe try to put the variable "HAYSTACK_SEARCH" to False and restart the docker composer.

**Comment by lolob** [comment]
@NyakudyaA I found the workaround. Feel very relieved. 
Thanks @afabiani.

These are my step! The objective is, I don't want anonymous for wfs.

**1.** Jump to step#3 in the tutorial (http://docs.geonode.org/en/master/tutorials/admin/geoserver_geonode_security/#django-oauth-toolkit-admin-setup). Create OAuth2 Application called "GeoServer" . Because I don't have it. 

![Screenshot 2019-04-24 at 5 01 33 PM](https://user-images.githubusercontent.com/15963902/56646764-ceb9b680-66b2-11e9-86bf-1c46f0029473.png)

**2.** Global service is enable . Click submit

![Screenshot 2019-04-24 at 5 06 53 PM](https://user-images.githubusercontent.com/15963902/56647076-6ae3bd80-66b3-11e9-880f-dee37b849077.png)

**3.** Create new service access rule . I don't want the ROLE_ANONYMOUS.

![Screenshot 2019-04-24 at 5 08 25 PM](https://user-images.githubusercontent.com/15963902/56647246-bb5b1b00-66b3-11e9-8139-4f48e3153b6d.png)

**4.** Go to GeoFence Admin Page. I check "Use GeoServer roles to get authorizations" and click submit.

![Screenshot 2019-04-24 at 5 12 51 PM](https://user-images.githubusercontent.com/15963902/56647671-69ff5b80-66b4-11e9-94ad-8edb7abbbd5b.png)

**5.** Go to page "Users, Groups, Roles" and click the "geonode REST role service". Just to make sure the Base Server URL is correct. Don't forget to click Save.

![Screenshot 2019-04-24 at 5 19 10 PM](https://user-images.githubusercontent.com/15963902/56648078-340ea700-66b5-11e9-9fac-71c4f9c38509.png)

**6.** Go to Geoserver Server Status page, clear the Resource Cache and reload the Configuration and catalog

**7.** Open QGIS3.4 . Add WFS layer. Then connect. A dialog will pop-up for username and password. I use my admin.

![Screenshot 2019-04-24 at 5 27 13 PM](https://user-images.githubusercontent.com/15963902/56648709-6076f300-66b6-11e9-894f-242c7ddcd384.png)

**8.** However, if one use OWS geonode proxy url (<geonode_host>/gs/ows ). No Access. Yes!

![Screenshot 2019-04-24 at 5 37 18 PM](https://user-images.githubusercontent.com/15963902/56649404-a4b6c300-66b7-11e9-866d-e3893ded872a.png)

**9.** My geonode also works the same way. Only the rightful owner has the permission of editing(wfs).

**Comment by afabiani** [comment]
@lolob thanks, those are also very useful info and steps we might include into the advanced documentation topics.
