### ISSUE TITLE
SITEURL not set in SPC

### ISSUE THREAD

**Issue by frafra** [GeoNode/geonode#4303]
After uploading a layer I see broken thumbnails: sometimes the URL is wrong, sometimes it is just a placeholder ("no image"). The path is correct, but hostname and port are wrong (localhost:8000).

I am using SPCGeonode. `HTTP_HOST` and `HTTP_PORT` are correctly set.

**Comment by francbartoli** [comment]
It should be also connected to https://github.com/GeoNode/geonode-project/issues/67

@frafra Can you check if you find the same error from logs?

**Comment by frafra** [comment]
@francbartoli I do not see that error.
I do not think they are not connected, at least not for the broken links.

The wrong URL is created and saved in the database using `SITEURL`: https://github.com/GeoNode/geonode/blob/master/geonode/base/models.py#L1154. It makes little sense to me to store the full path instead using a relative one and eventually computing the full one on the fly, so changing the `SITEURL` would not require to update the database, but that's another issue.

```
$ docker container exec $GEONODE_CONTAINER ./manage.py shell -c 'from django.conf import settings;print(settings.SITEURL)'
/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
JSONField implementation is: <class 'jsonfield.fields.JSONField'>
http://localhost:8000/
```

This happens because `SITEURL` value depends on `SITE_HOST_NAME` and `SITE_HOST_PORT` and `SITEURL` is not set.

`docker-entrypoint.sh` exports `SITEURL` and `exec` keeps the environment:

```
$ (export a=1; exec bash -c 'echo $a')
1
```

What about `uwsgi`? It keeps the environment. I do not know what else to look at the moment, but I find a workaround. Just set `SITEURL` in the compose file :-)

**Comment by francbartoli** [comment]
@frafra in my case I'm seeing that linked error from the celery log and the piece of code failing is right the task for the thumbnail

**Comment by frafra** [comment]
@francbartoli After applying the workaround, I got your error. I would keep this issue to fix the `SITEURL` problem.

**Comment by frafra** [comment]
@olivierdalang any idea about what could cause the problem?

**Comment by olivierdalang** [comment]
@frafra To keep settings DRY, SITEURL is determined in the entrypoints using the SPCgeonode HTTP[S]_HOST and HTTP[S]_PORT.

For Django : https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/django/docker-entrypoint.sh#L14-L24

For Geoserver : https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/geoserver/docker-entrypoint.sh#L19-L30

The issue arises when the host or port changes, since as you noticed, the full path for links/thumbnails/etc is stored in several places in the database.

This should be dealt with by those lines in the django entrypoint : 
https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/django/initialize.py#L116-L117

I'm not exactly sure why, but as far as I remember, `updatemaplayerip` wasn't enough, and `updatelayers` is commented out as it deletes thumbnails (even if customized). That may be the issue ?

Also I'm not sure if Geoserver also stores these URLs somewhere, in which case these lines should be moved to the end of the `django/initialize.py` script...

Anyway, those settings are a complete mess, and a proper fix would be for Geonode to work with relative URLs.

**Comment by gannebamm** [comment]
@frafra I do not see these errors anymore with current SPC docker setup. Can we close this issue?
