### ISSUE TITLE
tags do not support unicode text

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#4357]
If using unicode characters in tags the tags will get updated, but the metadata assistent form is not able to load anymore:
![unicode_tags_error](https://user-images.githubusercontent.com/6172324/56023870-264d3f00-5d0f-11e9-8d6a-1704b9f3bea5.gif)

**Comment by t-book** [comment]
Dear @gannebamm,

I think the error comes by typecasting to string

https://github.com/GeoNode/geonode/blob/509b3606ba2fbbb4c2242872d737b7b3edcde170/geonode/base/forms.py#L115

 i.tag.name is already returned as unicode maybe I miss something but I think it would be save to join without it which should fix it:

`vals = ','.join([i.tag.name for i in value])`

Unfortunately currently I do not have the time to test it thoroughly and hence will not suggest a PR as bug fix.

Further I've recognized when creating tags f.e. in Chinese or Hebrew those are displayed urlencoded which is unreadable for users. 

Without a closer look I can image to reasons for it. Either it’s because the js escaped tag is not unescaped and written as is to the database:
https://github.com/GeoNode/geonode/blob/49ce37c72e8887a96949e95e5abbc673419c246d/geonode/templates/metadata_form_js.html#L531
Or it’s happening as json_dump converts to string. 
https://github.com/GeoNode/geonode/blob/fb00670572efdb2c5f2139146ecdbe74a5c96a9a/geonode/views.py#L148
and as the object 
https://github.com/GeoNode/geonode/blob/master/geonode/base/models.py#L348
will use repr() it will return an urlencoded string. 
```
>>> test = {'論語'}
>>> print test
set(['\xe8\xab\x96\xe8\xaa\x9e'])
```

As said both only **vague assumptions**. This all needs more investigations but hopefully it helps to get this bug fixed.

Happy bug-hunting,

– Toni

**Comment by gannebamm** [comment]
@t-book Thanks for the code analysis!
I am currently busy and will focus on improving #4355  PR but after making that one 'mergable' I would like to work on this issue.

**Comment by gannebamm** [comment]
> Dear @gannebamm,
> 
> I think the error comes by typecasting to string
> 
> [geonode/geonode/base/forms.py](https://github.com/GeoNode/geonode/blob/509b3606ba2fbbb4c2242872d737b7b3edcde170/geonode/base/forms.py#L115)
> 
> Line 115 in [509b360](/GeoNode/geonode/commit/509b3606ba2fbbb4c2242872d737b7b3edcde170)
>  vals = ','.join([str(i.tag.name) for i in value]) 
> 
> i.tag.name is already returned as unicode maybe I miss something but I think it would be save to join without it which should fix it:
> 
> `vals = ','.join([i.tag.name for i in value])`
> 
> [...]
> Happy bug-hunting,
> 
> – Toni

I tested this little change and it worked. Thanks @t-book

**Comment by t-book** [comment]
Thanks @gannebamm so it would be interesting to know if this affects other parts like uploading of Metadata... In other words to be sure we do not break anything by fixing something ;)
