### ISSUE TITLE
geonode-oauth2/config.xml file not found

### ISSUE THREAD

**Issue by gvoltz** [GeoNode/geonode#4422]
I'm following the instructions on http://docs.geonode.org/en/master/tutorials/install_and_admin/setup_on_centos/install_geonode.html and don't see a config.xml file for the directory geonode-oauth2.

The directory is not included from the curl command of https://build.geo-solutions.it/geonode/geoserver/latest/

The instructions do a few 'sed' commands on the geonode-oauth2/config.xml file, and that file appears to not get generated during the deployment, nor do I see the instructions saying to make the file. I thought it may have meant to be included in the deployment of the .war file. 
![image](https://user-images.githubusercontent.com/47166887/58042317-5ce55900-7b08-11e9-93ba-f7af349be052.png)

Can someone share with me how /var/lib/tomcat/webapps/geoserver/data/security/filter/geonode-oauth2/config.xml
is generated, or point out to me any step I may have missed in the instructions?

_Extra information if it helps - Im running on a CentOS7 VM using VirtualBox._

Thanks in advance!

**Comment by t-book** [comment]
Hi @gvoltz the docs are unfortunately a bit outdated. Anyways the config.xml ships with the geoserver data directory. https://build.geo-solutions.it/geonode/geoserver/latest/data-2.15.x.zip 
You could also configure this via the geoserver gui. Let me know if you need more guidance.

**Comment by gvoltz** [comment]
The geoserver-2.15.x-oauth2.war file doesn't seem to deploy like geoserver-2.9.x-oauth2.war file does upon doing a curl of the url https://build.geo-solutions.it/geonode/geoserver/latest/{FILE} into /var/lib/tomcat/webapps

When I tried to `curl` the geoserver-2.15.x-oauth2.war and deploy it, I assumed that the directory and files would be generated as the geoserver-2.9.x-oauth2.war file does, but it doesn't. 

Earlier in the instructions I curled "https://github.com/GeoNode/geonode/archive/2.6.3.zip" and stored the contents in /opt/apps/geonode/geonode and get a python error when I run `python manage.py updatelayers` about a socket connection. Is this something to do with compatibility between the 2.6.3.zip file and  geoserver-2.15.x-oauth2.war file?

Also I should note i'm using python 2.7, is that an issue? I didn't see python 3 requirements listed and the instructions appear to be installing python 2.7 dependencies. 

Thanks again for the help!

**Comment by afabiani** [comment]
@gvoltz I'm not sure how you installed GeoNode, however after 2.9 the "geoserver" packages to be used are (depending on which version you want):

* https://build.geo-solutions.it/geonode/geoserver/latest/geoserver-2.14.x.war
* https://build.geo-solutions.it/geonode/geoserver/latest/geoserver-2.15.x.war

**Comment by BarrySteele** [comment]
The build.geo-solutions.it links do not work anymore unfortunately - I get 404 errors.

**Comment by afabiani** [comment]
Please use the following one:

https://artifacts.geonode.org/index.html

**Comment by BarrySteele** [comment]
Thx, Will do

**Comment by BarrySteele** [comment]
Thank you very much, that worked.

Stay well
Barry


Barry Steele
Customer Success Consultant
________________________________________
Geoscape Australia
Unit 6, 113 Canberra Ave Griffith ACT 2603
CanberraACT
(02) 6260 9000
***@***.***
www.geoscape.com.au
This message contains information that may be privileged or confidential and is the property of PSMA Australia Ltd trading as Geoscape Australia ABN 23 089 912 710. It is intended only for the person to whom it is addressed. If you are not the intended recipient, you are not authorised to read, print, retain, copy, disseminate, distribute, or use this message or any part thereof. If you receive this message in error, please notify the sender immediately and delete all copies of this message.  All outgoing emails and attached files are virus scanned, but we do not represent that this email and any attached files are free from computer viruses or other defects. Further, we do not accept any liability for any damage caused by this email or attachments. 
From: Alessio Fabiani ***@***.***>
Date: Thursday, 3 November 2022 at 01:25
To: GeoNode/geonode ***@***.***>
Cc: Barry Steele ***@***.***>, Comment ***@***.***>
Subject: Re: [GeoNode/geonode] geonode-oauth2/config.xml file not found (#4422)

Please use the following one:

https://artifacts.geonode.org/index.html
