### ISSUE TITLE
some links reference localhost instead of FQDN

### ISSUE THREAD

**Issue by koelslaw** [GeoNode/geonode#4471]
Platform: Amazon EC2 (ubuntu) - > Docker -> Geonode stuff
Cloned the geonode git repo.
Removed all but `docker-compose.yml` in that directory.
 ran ` docker-compose up --build` 
navigate to "example.com" and the index loads and then go to "upload layers" and it attempts `http://localhost/account/login/?next=http%3A//example.com/layers/upload` instead of the expected `http://example.com/account/login/?next=http%3A//example.com/layers/upload'`. I have logged into the container and edited the `../geonode/settings.py` file but it has not resolved. If I am understanding it right then it should be getting the hostname from the an entrypoint file but I cannot see where.

**Comment by afabiani** [comment]
Hi @koelslaw with docker you should override the env variable in order to provide the correct endpoints to GeoNode.

Please take a look at the new documentation we are preparing here
http://docs.geonode.org/en/new-docs/install/core/index.html#docker

and in particular to the following sections
http://docs.geonode.org/en/new-docs/install/core/index.html#override-the-env-variables-to-deploy-on-a-public-ip-or-domain

**Comment by koelslaw** [comment]
That worked! Thanks for the help! Keep up the good work.
