### ISSUE TITLE
Change display order of attributes in metadata breaks attribute table

### ISSUE THREAD

**Issue by impisnoth** [GeoNode/geonode#4505]
## Expected Behavior

After changing the display order of one attribute in the metadata the order in the popup should be displayed correctly.
 
## Actual Behavior

After changing the display order of one attribute in the metadata form the whole table disappears and attributes in popups are displayed wrongly.

## Steps to Reproduce the Problem

  1. Change the display order of one attribute in the metadata
  2. Save the metadata
  3. Refresh metadata and try to display a popup

## Specifications

  - GeoNode version: 2.10 rc5
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker and master.demo.geonode.org
  - Platform: OSX
<img width="811" alt="Screenshot 2019-06-13 at 15 59 25" src="https://user-images.githubusercontent.com/5585799/59438692-46bf7580-8df4-11e9-9149-880dba713ee2.png">
<img width="448" alt="Screenshot 2019-06-13 at 15 59 41" src="https://user-images.githubusercontent.com/5585799/59438693-47580c00-8df4-11e9-8a49-a75795444d5a.png">

  - Additional details:

**Comment by kikislater** [comment]
Please re-open : 
Uploading layer and clic on map, attribute table looks like that =>

![image](https://user-images.githubusercontent.com/13238064/74132580-4c2dc380-4c00-11ea-8286-f4114a38b73e.png)

Changing title in attribute table and it change display of attribute table : 

![image](https://user-images.githubusercontent.com/13238064/74132622-649dde00-4c00-11ea-9f1c-07521611c85c.png)

Tested on master demo geonode

**Comment by gannebamm** [comment]
I think mapstore2 let's you configure the get feature info - we should implement that for geonode, too.

**Comment by kikislater** [comment]
Ok ! 
Behaviour is why it changes ? 
Then we don't have this Feature Info form in standard Mapstore Geonode Info : 
![image](https://user-images.githubusercontent.com/13238064/74641400-a8599000-518a-11ea-8a01-e72274a0b535.png)

**Comment by afabiani** [comment]
The attributes template is injected by the django-mapstore-adapter into the map config dynamically.

It is computed from the order and labels of the attributes set on the layer metadata.
Whenever you add a label or change the order of the attributes from the metadata wizard, GeoNode will update the featureinfo template.

**Comment by kikislater** [comment]
> Whenever you add a label or change the order of the attributes from the metadata wizard, GeoNode will update the featureinfo template.

Ok thank you for your reply but just changing title in advanced edit mode change the feature info template ?! Is it a normal behaviour ?

Does standard Geonode is furnish with full mapstore or do we have too enable some modules or newer Mapstore version like @t-book do with : https://github.com/GeoNode/geonode/issues/5034
if yes where to enable feature info icon and GUI ?

**Comment by afabiani** [comment]
It is a "normal" behavior in the case you did not touch the attributes at all. It will probably change the template from plain/text to text/html.

This is something new, we should maybe discuss better how this should behave in the future.

Currently, the mapstore provided by GeoNode has local_configurations that disable or limit some of the standard mapstore functionalities. This is mostly because of the fact that everything you change from the map should be somehow intercepted and controlled by GeoNode too. For the same reason, it is dangerous to enable plugins that somehow modify the map configuration. It will be very possible that whenever you change something from GeoNode Layer metadata, the map configuration will be affected too (like in this case).

There are internal discussions here @ GeoSolutions on how to improve the integration between MapStore and GeoNode in order to fully transform GeoNode into MapStore storage. But for the moment we haven't allocated yet resources on that.

However, any user experience is very welcome. Let's open discussions on how to manage and improve this integration.
Easy tasks might also be developed through community contributions.

**Comment by kikislater** [comment]
Ok, so I think I found what is causing this behaviour !!! I found when I checked layers in Django admin under : admin/layers/attribute 
For layers with problems, I found that none of table fields have "visible"  box checked ... 

So going in Metadata and found this : 

![image](https://user-images.githubusercontent.com/13238064/74830709-2ce41400-532d-11ea-925e-38c42d8d1dd0.png)

In conclusion, it's more a user issue IMO than a geonode issue.

**Comment by gannebamm** [comment]
Would postpone this to get 3.0 faster. And I am not sure what exactly is to do to close this issue. If a feature info template should be configurable by GeoNode this issue title is misleading.
