### ISSUE TITLE
GWC does not create tiles

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#4612]
## Expected Behavior
An uploaded layer will automatically create a tiled layer in geoserver. The tiles will get dynamicly created by viewing them through e.g. GeoNodes mapping client (MapStore / GeoExt).

## Actual Behavior
The layer will get an cached layer but its dimensions are off and no tiles will be created.

## Steps to Reproduce the Problem

* upload shapefile (eg. someHydroData)
* open GeoServer Admin GUI
* look at gwc layer description
* check dimensions (all 0.0,0.0,-1.0,-1.0)
* delete old dimensions
* add new dimensnions, which will be dynamic
* save
* try to open layers panel in geoserver web gui

## result

the gui won´t get rendered. The error is:

Caused by: java.lang.IllegalArgumentException: Don't know how to handle resource SecuredFeatureTypeInfo[FeatureTypeInfoImpl[someHydroData0]] at org.geoserver.geofence.GeofenceAccessManager.buildAccessLimits(GeofenceAccessManager.java:500) at org.geoserver.geofence.GeofenceAccessManager.getAccessLimits(GeofenceAccessManager.java:304) at org.geoserver.geofence.GeofenceAccessManager.getAccessLimits(GeofenceAccessManager.java:288) at org.geoserver.security.ResourceAccessManager.getAccessLimits(ResourceAccessManager.java:47) at org.geoserver.security.ResourceAccessManagerWrapper.getAccessLimits(ResourceAccessManagerWrapper.java:225) at org.geoserver.security.CatalogFilterAccessManager.getAccessLimits(CatalogFilterAccessManager.java:63)

## Specifications

  - GeoNode version: 2.10rc
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Docker both
  - Platform: Ubuntu 18.04, Docker CE
  - Additional details: GeoServer::
    Version
    2.14.3
    Git Version
    a700a48f014f8051f98e2f3a2f9e8190e9df1c79
    Build-Datum
    20-Mar-2019 19:00
    GeoTools Version
    20.3 (rev c132dedeae6c497eb0f4d2603618989cc8745cd5)
    GeoWebCache Version
    1.14.0 (rev 1.14.x/775e94eb2ae59dd9b74aecc709b67d7b968a4317)

**Comment by afabiani** [comment]
@gannebamm it looks like the issue is caused by the default quota-store using H2. By disabling it, everything works fine again. 

![image](https://user-images.githubusercontent.com/1278021/60814506-04404d00-a196-11e9-9002-cd1956cf7fde.png)

It is an old issue which was supposed to be fixed on GeoServer, however, it looks like it is still there. Most probably caused by concurrent access from GeoFence.

Until we do not add more complex logic to SPCGeoNode in order to configure GeoFence and DiskQuota against a PostgreSQL DB connection, I will update the GeoServer Data dirs with DiskQuota disabled by default. This should fix the setup anyway.

Please, make a try by yourself and confirm. Close or reply to this issue accordingly.

**Comment by gannebamm** [comment]
disabling the disk quota fixes the wrong dimensions, yes. But on my setup using the postgresql container as pg backend for disk quota storage __does not__ fix the issue.
And - newcomer to gwc here - will disabling a quota for gwc disable the whole gwc? I can not see any stored tiles in the web admin of geoserver

**Comment by afabiani** [comment]
Hi @gannebamm we need to investigate why diskquota is breaking the GWC tiling defaults. It should be a GeoServer regression again.
About your question, nope, disabling diskquota does not affect GWC. You can easily verify this by looking at several response headers from GeoServer zooming in and out. Where data is present, the second time you'll get a "geowebcache = HIT" response, meaning that GeoServer is giving you back the cached tile.
