### ISSUE TITLE
Thumbnails are generated with a point style for line/polygon layers

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#5049]
## Expected Behavior

A thumbnail for a line or polygon layer should be generated with a correct line or polygon style.

## Actual Behavior

Under some circumstances (large GS with many layers?) I have seen this bug happening on different instances.

## Steps to Reproduce the Problem

Not reproducible using a standard GeoNode installation.

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: Ubuntu
  - Additional details:

**Comment by afabiani** [comment]
@capooti so, I took some time to try to understand the issue and the solution you are going to implement.

It seems to me that the PR actually is not related to the problem you are describing.

The thumbnails are generated using the current default style set into GeoServer, therefore this issue is a side effect of the fact that the layer in GeoServer is not correctly configured.

Most probably, by just using the "Manage Style" function and setting the correct default style, fixes the issue.

![image](https://user-images.githubusercontent.com/1278021/67274982-e4713280-f4c1-11e9-823e-bcfadba10e2c.png)

On the other side, it could be a "feature" to allow the thumbnail generator to take the "styles" parameter. But this topic must be further investigated.
I really don't think it is a good solution to just inject a default style to the request.
We could envisage a way to let the user select the style he would like to use to generate the thumbnail.

That said, this is not a "Major" issue and I disagree to include this one into the 2.10.1 release.
