### ISSUE TITLE
[Performance] Cache Busting mechanism to manage static resources cache

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#5348]
**Is your feature request related to a problem? Please describe.**
Currently, when redeploying/updating GeoNode statics, if the content was cached on client side, it won't be possible to refresh it unless asking to the user to clear the cache or start a new browser session.
We would like, in production, to be able to force statics to reload whenever those have been updated by GeoNode somehow.
Actually, Django allows configuring a `STATIC `and `MEDIA` storage called [`ManifestStaticFilesStorage`](https://docs.djangoproject.com/en/2.2/ref/contrib/staticfiles/#manifeststaticfilesstorage) allowing us to refresh the static and media contents if they gets updated.

**Comment by t-book** [comment]
@afabiani as a side effect:

It looks with ManifestStaticFilesStorage we could get rid of the appended version when importing js and css files `?v={{ VERSION }}`? Or at least use a hash instead of the version string? 

The problem with the appended version is security. It's advisable to not tell the world which exact software running online. ( This would imply to show the version for admins only in footer section)

Just an idea ... nothing urgent though

**Comment by afabiani** [comment]
@t-book sure, very good idea. Yes, I'll include that on the PR too.

**Comment by t-book** [comment]
thanks @afabiani !
