### ISSUE TITLE
Wrong User Analytics display in Year view

### ISSUE THREAD

**Issue by kikislater** [GeoNode/geonode#5364]
## Expected Behavior
Have statistics for current month

## Actual Behavior
No data whereas month view have data 

![image](https://user-images.githubusercontent.com/13238064/70046015-99792d80-15de-11ea-9f31-ec627719a56f.png)
![image](https://user-images.githubusercontent.com/13238064/70046033-a3029580-15de-11ea-8bef-53689834a69d.png)
![image](https://user-images.githubusercontent.com/13238064/70046063-b1e94800-15de-11ea-870f-160213777ffe.png)
![image](https://user-images.githubusercontent.com/13238064/70046086-bc0b4680-15de-11ea-9dee-59f19f4444bf.png)

## Steps to Reproduce the Problem

  1. Configure monitoring 
  2. Load data for 2 months
  3. Go to user analytic module

## Specifications

  - GeoNode version: 2.10.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): All
  - Platform: Linux
  - Additional details:

**Comment by travislbrundage** [comment]
The reason for this is somewhat complicated, but has to do with the time ranges.

For a year, I think the display is actually wrong. It is just starting on Jan 1st of the year and naively adding 31 days 12 times, which makes the brackets for each year a bit off. This gets worse throughout the year and by the end you have the "December" bracket going from Dec 7th to Jan 7th. I believe this is causing the issue displayed here, since Dec 1st is not in that bracket correctly in the year view.

However, it gets more nuanced when we break thing down further. For example, the week view starts on the previous Sunday and ends on the next Sunday, which sounds accurate.

The month view starts on the 1st of the month and naively adds 4 weeks, which causes it to spill over a bit. I think this is also wrong and should start on the 1st of the month and end on the last day of that month. The issue is that it causes the brackets to be slightly weird and uneven - it was doing 5 weeks for a consistent block of data for each bar graph element. The same for the year view, but with 12 blocks of 31 days.

This is the function that needs adjusting I believe: https://github.com/GeoNode/geonode/blob/master/geonode/monitoring/frontend/src/utils/TimeRangeUtils.js

Just leaving my update here based on what I have discovered. Here is what I would propose as a fix:
1) Year view will go from Jan 1st to Dec 31st, broken into 12 brackets which correspond to each months dates precisely. This will, however, be uneven blocks in terms of days.
2) Month view will go from the first date to the last date of the month into 5 brackets. There's no consistent way to break them, so I'll just start on the 1st of the month and advance 6 days at a time, which will cause the final bracket to be fewer days than the previous ones on months with fewer than 31 days.

I invite your feedback if you feel there is a better way to change it, otherwise, I will continue with that. :)

**Comment by giohappy** [comment]
@travislbrundage thanks for raising the issue. We're on that, along with other improvements to the monnitoring / analytics client. 
If you can wait for us to submit them please kepp this on hold.

**Comment by giohappy** [comment]
@travislbrundage please go ahead with the fixes. I would let @allyoucanmap review your PR if it's fine to you
