### ISSUE TITLE
Hierarchical keyword tree widget issues

### ISSUE THREAD

**Issue by dhlambert** [GeoNode/geonode#5419]
## Expected Behaviour
Hierarchical keyword tree widget expands keywords successfully when any part of the folder is clicked on.

**Note:** Autocomplete light is currently being upgraded to a new version which integrates with select2 widgets on frontend https://github.com/GeoNode/geonode/pull/5410.  Hierarchical keyword tree widget will also need to be fixed to work with select2 once #5410 has landed. The autocomplete light branch currently has this widget commented out:

## Actual Behaviour
Clicking a keyword doesn't open the hierarchy as expected - it only opens when clicking the very edge of the right side of the folder.

## Steps to Reproduce the Problem

1. Sign in as an admin user
2. Navigate to the django admin panel and add some hierarchical keywords with children like the following.
![image](https://user-images.githubusercontent.com/38519933/70873828-4e1a4280-2014-11ea-9f07-7d217be3f851.png)
3. Navigate to Documents (or other resource page)
4. Add a document (resource) and click into it
5. Click on "Edit Document"
6. Click the either Advanced Edit or the Wizard option
7. Find the Free-text Keywords field and expand the tree widget using the folder icon on the right of the input
8. Navigate to the parent keyword which was created earlier ie 'layer 1'
9.  Try click on the keyword such that it displays 'layer 2' - this behaviour only seems to work when clicking on the very edge of the right side of the folder. 
10. If 'layer 2' appears successfully try and click on 'layer 2' such that it displays 'layer 3' 

This should look as the following:
![image](https://user-images.githubusercontent.com/38519933/70876318-0f898580-201e-11ea-81b3-de6767141d94.png)

## Specifications

  - GeoNode version: 2.10 (master)
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: Ubuntu 18.04
  - Additional details:

**Comment by t-book** [comment]
This is caused by two problems.

## 1
The icons for tag/folder and expand overlap which you can see when applying some margin. (There are actually two icons)

```
span.expand-icon.fa.fa-folder {
    margin-right: 25px;
}
```

<img width="374" alt="Bildschirmfoto 2019-12-20 um 15 31 35" src="https://user-images.githubusercontent.com/20478652/71261664-3e656b80-233e-11ea-8d49-0ff9394df16c.png">

## 2

Both fa-tag and fa-folder use the same icon which is semantically wrong. Instead in IMHO fa-folder should be fa-plus

**Is** 
<img width="386" alt="Bildschirmfoto 2019-12-20 um 15 31 52" src="https://user-images.githubusercontent.com/20478652/71261704-5b01a380-233e-11ea-8c13-c02603e5a20e.png">
**should**
<img width="364" alt="Bildschirmfoto 2019-12-20 um 15 37 26" src="https://user-images.githubusercontent.com/20478652/71261835-a61bb680-233e-11ea-81b2-0c378d6dcfbc.png">
**to look like**
<img width="93" alt="Bildschirmfoto 2019-12-20 um 15 35 10" src="https://user-images.githubusercontent.com/20478652/71261850-addb5b00-233e-11ea-93c7-727dcd2dffb0.png">

**Comment by t-book** [comment]
@afabiani changed the milestone to 2.12.2 hope that is fine for you if not feel free to revert.
