### ISSUE TITLE
Unexpected error! when uploading a layer in Geonode

### ISSUE THREAD

**Issue by benardonyango** [GeoNode/geonode#5436]
I am trying to upload a layer in geonode but i get "Unexpected error" imediately after the " Performing Final GeoServer Config Step". I am using geonode version 2.10.1. **However, this happens to only one specific vector layer. I have uploaded some other vector layers without any errors.** 

I have checked the geonode error log and this is what i get

"2019/12/19 10:00:20 [error] 22758#22758: *77716 open() "/opt/geonode/geonode/static_root/proj4js/{'DETAIL': 'never'}.js" failed (2: No such file or directory), client: 41.191.225.194, server: ####.org, request: "GET /static/proj4js/%7B'DETAIL'%3A%20'never'%7D.js HTTP/1.1", host: "###", referrer: "https://###/layers/?limit=20"

Kindly assist in spotting where the issue is.

**Comment by t-book** [comment]
Dear @benardonyango from what I read the problem comes with your vector data. A  possible reason could be character encoding. If it would be of great help to get some demo data.

However, github should be used for bug tracking. For general help, I would kindly ask you to use the geonode user list at osgeo.

**Comment by benardonyango** [comment]
Okay @t-book . Let me close/remove the question and use the relevant platform.  I will check the character encoding.
