### ISSUE TITLE
Missing translation tags in layer_list and layer_detail

### ISSUE THREAD

**Issue by obersupermega** [GeoNode/geonode#6534]
## Expected Behavior
In all languages, the name and description of the data categories should be displayed in the appropriate language.

## Actual Behavior

(missing {% trans item.category__gn_description} in _resourcebase_snippet.html e.g.)

## Steps to Reproduce the Problem

  1. Change language, e.g. to french
  2. Go to layer list or go to layers detail page

![Bildschirmfoto von 2020-10-19 11-49-09](https://user-images.githubusercontent.com/47182599/96430683-c50b0380-1202-11eb-91fd-abc8e9e5d834.png)
![Bildschirmfoto von 2020-10-19 11-50-04](https://user-images.githubusercontent.com/47182599/96430686-c5a39a00-1202-11eb-8833-bed5e79ffe86.png)

## Specifications

  - GeoNode version: 3.x
  - Installation method: SPCGeoNode Docker
  - Platform: Ubuntu
  - Additional details:

**Comment by gannebamm** [comment]
I think since those Topic Categories are now part of the datamodel itself instead of pre-modelled the translation strings will vary. See e.G. http(s)://your.geonode.url/de/admin/base/topiccategory/

There you have the topic description and name as part of the database model. I am not sure how those would get translated. @t-book and @afabiani ? What is your suggestion?

**Comment by obersupermega** [comment]
That's right. But if the information is processed in _resourcebase_snippet.html you should still be able to translate the received variable as a string with "{% trans item.category__gn_description}" or a similar call. 
On index.html/iso_categories.html it works:
![Uploading pic1.png…]()

**Comment by obersupermega** [comment]
![screenshot](https://user-images.githubusercontent.com/47182599/96963648-44e9e400-1509-11eb-9654-794664f35f0b.jpg)

**Comment by gannebamm** [comment]
I've just got two infos:
First: https://github.com/gannebamm/geonode/commit/c7ea759aef12f9160b7e1439f0398a121c1f0eba#r43512134
The msgids are commented in some translation.po files, since they are no longer part of the html and therefore do not get create with the create_message django command (or get even commented out, like in the german one I've edited yesterday).
Second: The currently by fixtures inserted iso-category descriptions do sometimes differ from the msgids strings in the po files. Eg. the Oceans iso-cat must start with uppercase 'F' and end with a '.'. If these are changed in the django admin, the help text will get translated aswell. Ssee @obersupermega example above with france shortname but english description and mine:
![Screenshot from 2020-10-23 12-07-00](https://user-images.githubusercontent.com/6172324/97001696-55f61d80-1528-11eb-8171-3a6ee11e8e72.png)

**Comment by gannebamm** [comment]
See my draft PR: https://github.com/GeoNode/geonode/pull/6565

**Comment by gannebamm** [comment]
I tried to use {% trans ... } but it did not work as expected due to angular I think. Any hints are very much appreciated.
:point_up: [26. Oktober 2020 10:07](https://gitter.im/GeoNode/general?at=5f9691d73d172d78b39bc90d)

**Comment by gannebamm** [comment]
@afabiani @t-book The initial data json fixture is not matching with the .po file strings. There are two options:
a) change the po file msgid for all languages,
b) change the fixture

I have not enough experience to tell which of those options is better in terms of updateability and djangoness. See the fixture changes here:
https://github.com/gannebamm/geonode/commit/2819ea64797a3bd66cd6c85ab9ca59a65093c108

I´ve tested that locally and it does work fine for a new instance.

**Comment by afabiani** [comment]
@gannebamm the best option would be to change the fixture imho.

**Comment by gannebamm** [comment]
See my PR: https://github.com/GeoNode/geonode/pull/6565
Most of the issue is solved there.

**Comment by obersupermega** [comment]
Great job.But unfortunately, not all the passages are translated. Shall we reopen the issue?
![unequal](https://user-images.githubusercontent.com/47182599/98901044-52184400-24b3-11eb-9cac-75d53c2f3cfc.png)

**Comment by gannebamm** [comment]
Just for documentation purposes:
@obersupermega see my thoughts about that here https://github.com/GeoNode/geonode/pull/6565#issuecomment-724139507
In short: those are fetched from the (soon) old API and I would have to write a custom serializer for it - AFAIK. This is currently out of scope for me. Nevertheless the rest of the translations should get merged for 3.1 release.
