### ISSUE TITLE
new signup notification not sent with ACCOUNT_APPROVAL_REQUIRED=True

### ISSUE THREAD

**Issue by fpennica** [GeoNode/geonode#6909]
## Expected Behavior

With ACCOUNT_APPROVAL_REQUIRED=True a new signup notification is sent to staff users.

## Actual Behavior

The notification is not sent

## Steps to Reproduce the Problem

  1. set ACCOUNT_APPROVAL_REQUIRED=True in .env and enable email settings
  2. sign up for a new account
  3. notification is not sent to staff users

## Specifications

  - GeoNode version: 3.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): docker geonode-project (3.x)
  - Platform:
  - Additional details:

This is caused by `notify_admins_new_signup` calling `send_notification` with kwargs: https://github.com/GeoNode/geonode/blob/d7228886d8730254e2ef429762874b2d3e5005d0/geonode/people/signals.py#L114-L120

and `send_notification` requiring instead a specific set of args (with a 'resource') to do anything at all: https://github.com/GeoNode/geonode/blob/d7228886d8730254e2ef429762874b2d3e5005d0/geonode/notifications_helper.py#L88-L104

**Comment by giohappy** [comment]
The problems has been introduced with this https://github.com/GeoNode/geonode/commit/ebb302520fbc0f9cb5c7dbab05e697efde22743a

**Comment by giohappy** [comment]
@fpennica `send_notification` has changed meanwhile, and the notification works fine on 3.2.x which is the current active branch for the next release.
This issue is not relevant anymore so I'm going to close it.

https://github.com/GeoNode/geonode/blob/8462948d00585ed7c3b25081670ae9af0c43048b/geonode/notifications_helper.py#L87-L101
