### ISSUE TITLE
Metadata UI freezes on empty mandatory fields

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#7034]
## Expected vs actual Behavior

If a mandatory field is set as empty, and the "update" button is pressed, the UI freezes:
![image](https://user-images.githubusercontent.com/717359/110310192-88e60d00-8002-11eb-98a2-9c74f9182493.png)

Pls note that mandatory fields on UI are usually pre-filled, so this misbehaviour is normally triggered only if a user edit a mandatory field and empties it.

## Steps to Reproduce the Problem

  1. edit a layer/map/document
  2. empty a mandatory field (e.g. date)
  3. press the update button

## Specifications

  - GeoNode version: All

**Comment by etj** [comment]
Error still there:
1. edit a layer
1. in the first tab empty the date field
1. change tab 
1. press the update button
1. --> freeze with the same dialog as before

**Comment by mattiagiupponi** [comment]
Looks like that if you are not in the first tab some errors occur.
Chrome for example drop this error:
`An invalid form control with name='resource-date' is not focusable`
I'm going to investigate a little more

**Comment by mattiagiupponi** [comment]
This comment answer a bit to the problem https://stackoverflow.com/questions/7168645/invalid-form-control-only-in-google-chrome/7264966#7264966

So it looks like that if you change the tab with a 'required field', Django tries to show the classic popup "this field is required" but if fails because is not visible on the page

**Comment by mattiagiupponi** [comment]
> Error still there:
> 
> 1. edit a layer
> 2. in the first tab empty the date field
> 3. change tab
> 4. press the update button
> 5. --> freeze with the same dialog as before

@etj the fix is ready and available here https://github.com/GeoNode/geonode/pull/7071. In few words instead of the search only for visible required fields, now the JS will search for all fields required and this prevents the submission without filling required fields from the others tab.
The error on the console `An invalid form control with name='resource-date' is not focusable` is still present because Django still try to show the popup `This field is required even if the user is on another tab, but at least now the form will not freezing anymore
