### ISSUE TITLE
Error in preview 

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#7101]
## Actual Behavior vs Expected Behavior

If a required field is not filled, and the preview tab is clicked, an Error dialog pops up:

![image](https://user-images.githubusercontent.com/717359/111514093-b42ed180-8751-11eb-8d82-630a72a8fa99.png)

## Steps to Reproduce the Problem

The error is caused by an automatic update when the preview is requested.

  1. Edit or create a new metadata
  2. Make sure a required field is empty (e.g. remove the date)
  3. Click on the "Preview" tab.

## Specifications

  - GeoNode version: 3.2

**Comment by mattiagiupponi** [comment]
Analysis:
------------------
Looks like that when a required (via `Django` form, not from `UI` perspective) is defined and the user clicks on the preview page, the system will make a `POST` request and try to save the results.
Since the field is declared `required`, the form results invalid and the error is shown.

Fields Involved:
-----------------
The fields involved are defined here:

https://github.com/GeoNode/geonode/blob/c1007fc2cfac2b84a3361c2dad6c3137e538302a/geonode/base/models.py#L1177-L1187

Also, the Thesaurus could be required based on his configuration

Solution:
----------------
1) convert the Thesaurus values from required via Django form to required from UI perspective (so they can be empty)
2) If some of the required value is empty, on save the previous value is preserved

**Comment by etj** [comment]
If the existing procedure is "save and the switch to preview", I suggest to show any error that the save procedure would show and prevent switching to preview, if there are error in saving (such as missing fields)
