### ISSUE TITLE
Append data to an existing layer

### ISSUE THREAD

**Issue by chpicone** [GeoNode/geonode#7194]
**Is your feature request related to a problem? Please describe.**
We need to append data to an existing (vector) layer.
Users working on historical data need to continously add new records to the layer but they dont want to replace the  whole layer.

**Describe the solution you'd like**
We would like to have  in the "Edit Layer" form of an existing (vector) layer an "Append data" button like that:
![image](https://user-images.githubusercontent.com/2872823/112853799-816bce00-90ad-11eb-88ac-63c087fb305e.png)
When the user clicks this button we want a section to allow the user to select (or drop) the files of interest:
- shapefiles
- json
- csv
- kml/kmz
like that:
![image](https://user-images.githubusercontent.com/2872823/112854004-b5df8a00-90ad-11eb-928b-39955d8d1982.png)

For this purpose we still need to use import task provided by GeoServer but in APPEND way.
On the GeoNode side it is necessary (using ogr) to check the fieldset of the layer in input to check if it is compatible with the existing layer.

**Comment by t-book** [comment]
I like the idea as long as it ensured that incompatible data is caught and denied.

**Comment by mattiagiupponi** [comment]
> I like the idea as long as it ensured that incompatible data is caught and denied.

Hi, @t-book,
I agree with you, here you can find the checks added in order to maintain consistency the information added. Plus the checks are added also to the `layer_replace` functionality.

[Here ](https://github.com/GeoNode/geonode/blob/bbac4a8cc406e95d6f8d2fb817223b78c002ff15/geonode/layers/utils.py#L1110)you can find the checks added and [here ](https://github.com/GeoNode/geonode/blob/bbac4a8cc406e95d6f8d2fb817223b78c002ff15/geonode/layers/tests.py#L1708)the unit test.

In few words:
- check if you want to replace a raster with a vector and vice-versa
- check if the uploaded file has a valid format
- filename must be consistent
- check if the local geonode layer has geometry type and must be consistend
-  check if the layer in the catalog exists
- check that all the fields in the file that you are trying to upload are available in the gs layer

**Comment by t-book** [comment]
Great @mattiagiupponi 

> check if the local geonode layer has a geometry type and must be consistent

This is where I was mostly worried about. Nice feature, thanks!
