### ISSUE TITLE
Issues with layer style legends displayed when more than one style is selected

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#7236]
## Expected Behavior
When adding more than one style to a layer, I can see the legend of the current selected style.

## Actual Behavior
I see multiple legends. Moreover the title of the CSS ones report a long UUID as stated  form this issue [here](https://github.com/GeoNode/geonode/issues/7102#issuecomment-803847539)

## Steps to Reproduce the Problem

  1. Edit a Layer
  2. Add more than one style either from the map editor or "style manage" utility
  3. Go back to the layer detail page

![grafik](https://user-images.githubusercontent.com/6172324/111957351-328dc980-8aec-11eb-96cb-d759ccf96564.png)

## Specifications

  - GeoNode version: 3.2.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): any
  - Platform:
  - Additional details:

**Comment by gannebamm** [comment]
I still see the uuid in the legend title on master: https://master.demo.geonode.org/layers/geonode:background_layer_germany_epsg4326

**Comment by giohappy** [comment]
@gannebamm yes, this is quite problematic. I've spent time to investigate it. 

1 - When the Style Editor sends the first POST (through the geoserver_proxy view), GeoNode triggers the Geoserver post save signal https://github.com/GeoNode/geonode/blob/190e5f0939c3e89eca1d2dcd16f79cd867fba3a9/geonode/geoserver/helpers.py#L1082
This is where the new style is retrieved from Geoserver and saved in GeoNode.

**NOTE**: The style editor POSTs using the `name` parameter to set the style name in Geoserver, the one with the hash. This is of course needed to avoid writing styles with the same name.

2 - The style information is obtained from the gs_restconfig parsing. Both with CSS and SLD styles it seems that gs_restconfig doesn't populate the `sld_title` property. https://github.com/GeoNode/geonode/blob/190e5f0939c3e89eca1d2dcd16f79cd867fba3a9/geonode/geoserver/helpers.py#L1055

An example with a CSS style. Code posted by the Style Editor
```
"Lines 3"
@mode 'Flat';
@styleTitle 'Line 3';
@styleAbstract '';
 * {
	mark: symbol('shape://vertline');
	:mark { stroke: #ff338f; };
}
```

Output from Geoserver (/geoserver/rest/workspaces/geonode/styles/line_3___2964cfc0-a671-11eb-a607-47c492148453.sld)
```
<?xml version="1.0" encoding="UTF-8"?>
<sld:StyledLayerDescriptor xmlns:sld="http://www.opengis.net/sld" xmlns="http://www.opengis.net/sld" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" version="1.0.0">
   <sld:NamedLayer>
      <sld:Name>Default Styler</sld:Name>
      <sld:UserStyle>
         <sld:Name>Default Styler</sld:Name>
         <sld:Title>Line 3</sld:Title>
         <sld:FeatureTypeStyle>
            <sld:Name>name</sld:Name>
            <sld:Rule>
               <sld:PointSymbolizer>
                  <sld:Graphic>
                     <sld:Mark>
                        <sld:WellKnownName>shape://vertline</sld:WellKnownName>
                        <sld:Stroke>
                           <sld:CssParameter name="stroke">#ff338f</sld:CssParameter>
                        </sld:Stroke>
                     </sld:Mark>
                  </sld:Graphic>
               </sld:PointSymbolizer>
            </sld:Rule>
         </sld:FeatureTypeStyle>
      </sld:UserStyle>
   </sld:NamedLayer>
</sld:StyledLayerDescriptor>
```

gs_restconfig parsed information
![image](https://user-images.githubusercontent.com/571129/116065746-9bd2a080-a687-11eb-8067-037894f5c3b6.png)

As you can see the `sld_title` property is `None`, so it's not parsing the `UserStyle.Title` text element.

The same happens with an SLD

3 - In case of an SLD style it tries to parse the sld_title property if available, otherwise the style name is used. In case of a CSS it uses the style name directly
https://github.com/GeoNode/geonode/blob/190e5f0939c3e89eca1d2dcd16f79cd867fba3a9/geonode/geoserver/helpers.py#L1154
In both cases the end result is that the style name, the one with the hash, is used and stored.

In the end the problem is probably inside the parsing of the `sld_title` inside [geoserver-restconfig](https://github.com/GeoNode/geoserver-restconfig).

**Comment by giohappy** [comment]
It's confirmed that the solutions are two:

1 - Obtain the style from Geoserver REST API in SLD format and parse the title from the `UserStyle.Title` element. This works in all the practical cases, although a style could have in theory multiple User Styles. In these (rare!) cases we can decide to take the first UserStyle element.

2 - Use the style metadata info capacilities. If a PUT to Geoserver style REST API contains a metadata propert, this should be stored along with the style and be returned when requesting the XML for the style. In this case we could make the Style Editor send the title as a metadata info, and simply parse it inside geonode_restconfig.

We'll discuss the two options internally.

**Comment by giohappy** [comment]
The mid-term solution will probably be this: https://github.com/GeoNode/geonode-mapstore-client/issues/144

**Comment by giohappy** [comment]
This is the short-term solution: https://github.com/GeoNode/geonode/issues/7390

**Comment by marthamareal** [comment]
@giohappy  @afabiani On layers with no default style, multiple legends are displayed.
Example

![admin](https://user-images.githubusercontent.com/20810749/116209358-81153000-a74a-11eb-9c82-d8c29f41c054.png)

![layer](https://user-images.githubusercontent.com/20810749/116209393-8a060180-a74a-11eb-8a5c-d180fce99ccf.png)

This because the layer_detail template [loops](https://github.com/GeoNode/geonode/blob/master/geonode/layers/templates/layers/layer_detail.html#L608) through all legends returned by the [resource.get_legend](https://github.com/GeoNode/geonode/blob/master/geonode/base/models.py#L1425)

**Comment by giohappy** [comment]
@marthamareal can you give a look to this?

**Comment by giohappy** [comment]
Fixed through https://github.com/GeoNode/geonode/pull/7405
