### ISSUE TITLE
Thumbnail failure when data bbox extends beyond the area of use of EPSG:3857

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#7292]
The new thumbnail code employes the 4326 to 3857 transformation (through pyproj's Trnasformer) in several places. The trasnform fails silently since the `errcheck` parameter is False (by default). The returned wrong values are then used downstream leading to failures.

Thumbnails assume EPSG:3857 backgrounds and overlays to generate the output image. This means that nothing beyond the EPSG:3857 area of use can be rendered (the same as with map view's themselves). This menas that we can safely clamp any bbox calculation to the EPSG:3857 area of use:

```
>>> from pyproj.crs import CRS
>>> crs_3857 = CRS.from_user_input(3857)
>>> crs_3857.area_of_use()
AreaOfUse(west=-180.0, south=-85.06, east=180.0, north=85.06, name='World between 85.06°S and **85.06°N.')
```

Moreiver the transform should use `errcheck` and manage the exception (with some logging).

**Comment by bieganowski** [comment]
following an external discussion:
- `errcheck` is not implemented, since in `Transformer`s with `always_xy` the check is implemented incorrectly (exceeding dimension on latitude don't cause errors, while exceeding dimensions on longitude does).
- we may not crop the BBOX for all cases, since in many cases overflowing values are required (requests from the frontend, provided in the default CRS - `EPSG:3857` - have to be handled without cropping)
- backend implementation allows using different CRS for a thumbnail generation, but still operates on `EPSG:3857` to preserve the ration of an image

Implemented solution
- for generating a default thumbnail (thumbnail generated in `EPSG:3857`; BBOX retrieved from `layer.bbox` of an instance), cropping the BBOX to the `EPSG:3857`'s area of use was introduced to ensure correct CRS transformations
- for the default thumbnail's CRS (`EPSG:3857`), the flow for BBOXes provided in `EPSG:3857` was preserved
- for the default thumbnail's CRS (`EPSG:3857`), for BBOXes provided in CRSs different from `EPSG:3857` an additional check was introduced, forcing the crop of the overflowing coordinates to `EPSG:3857`'s area of use
- for forced thumbnail's CRS (different from `EPSG:3857`; by default used in layers from external services), and additional check was introduced, turning off thumbnail's ratio preservation, in case of receiving a BBOX in CRS different from `EPSG:3857`

**Comment by bieganowski** [comment]
following an external discussion:
expanding the BBOX to the desired ratio using linear transformation, implemented here:
https://github.com/GeoNode/geonode/blob/fa53409dcdb890e452555427c4eb2dd2f9e8cc4f/geonode/thumbs/utils.py#L101-L131
is valid for all `CRS`s and does not require additional transformations between the coordinate systems.
In scope of this issue, unnecessary checks and CRS casting removal should also be performed.
