### ISSUE TITLE
html body class translate

### ISSUE THREAD

**Issue by leandrobaronisuremptec** [GeoNode/geonode#7354]
## Expected Behavior
The language would not change the html class' names of the html page's code.

## Actual Behavior
The language changes the html class' name of html page's code.

## Steps to Reproduce the Problem

  1. Inspect the html code of layers list with geonode in English. class="layers explore ng-scope"
  2. Inspect the html code of layers list with geonode in Spanish. class="explora capas ng-scope"

## Specifications

  - GeoNode version: master demo https://master.demo.geonode.org/layers/?limit=5&offset=0

**Comment by giohappy** [comment]
Thanks @leandrobaronisuremptec I can confirm the issue.

**Comment by mattiagiupponi** [comment]
**Analysis:**
The issue is caused by this line `{% block body_class %}{% trans "layers explore" %}{% endblock %}`. With this line, at the language change, the class name will be translated.

**Solution:**
Remove the translation from the body_class tag
`{% block body_class %}layers explore{% endblock %}
`
