### ISSUE TITLE
Introduce the adoption of groups to define users permissions, and define add_resource permission for users

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#7355]
We want to improve the way permissions are managed in GeoNode, to make room for more advanced combinations of roles and permissions. The idea is to increase the usage of permissions to granularly drive the functionalities both in the backend and the client, sintead of simply relying on the "AnonymousUser" and the admin concepts.

We start by introducing the concpet of a "contributors" role (Django Group) which is assigned the base_addresourcebase. Every user will be assigned to the group by default, so that the current assumption that any registerd user can create resources is maintained.

The first usage of this permissions will be:

 - the client uses it to decide if the "Create ..." and "Save as..." should be visible for the user
 - replace the READ_ONLY checks in the backend to decide if resources can be created (the only case where they can't is when the read only mode is active)

More use cases to come, and more permissions will be added to the group and security checks will be done on top of these permissions.

## Expected Behavior
-  A `contributors` Django group is created and the `base_addresourcebase` permission is assigned to it. The creation of this group could follow the same approach that we're using to create (and assign) a user to the `anonymous` group, i.e. it's created the very first time we need it.
- Every user will be assigned, by default, to the `contributors` group.(except anonymous and admins)
- A new `People.perms` property will return all the set (unique list) of permissions from the user's groups, i.e. permissions will be the combination of all the group's (non-repeated) permissions the user is a member of. 

The returned permissions are a mapping from Django permissions to a new set of GeoNode constants that will be declared inside the `security` module.
The first constant will be:

`base_addresourcebase -> add_resource`

The same will be done along the way to convert all the GeoNode code to use constanst instead of the original Django / Guardian permission strings.

## Actual Behavior
- There is no contributor group and `base_addresorcebase`

## Steps to Reproduce the Problem

  1. New addition

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by gannebamm** [comment]
I like this as a foundation for more granular rights management but what is the difference between `contributors` and `registered_users`? We currently have those as group available if you decide to set the env var `AUTO_ASSIGN_REGISTERED_MEMBERS_TO_REGISTERED_MEMBERS_GROUP_NAME=True`

**Comment by giohappy** [comment]
@gannebamm we discussed this point, because it was also our concern. We arrived to the fullowing results:

 - the `GroupProfile` concept is geared toward grouping people in terms of "organizations", and this is how they are treated in GeoNode. The concept or roles and organizations are clearly different. In this sense the `Registered Members` group is a group of people to which you want to assign permissions *on resources* easily, without having to list the single users inside the permissions panel. 
 - In the future I would rename the `GroupProfile` to Organization, to make this clear, and I would also split it from Django Group. 
 - Django Group are instead sort of "roles", and this is how Django conceives groups. In fact Django admin provides the option to assign permissions to Groups by default.

So, in the end, we think that `Group` is the right way to manage permissions and assign permissions to users.
`GroupProfile` should be mentally translated to Organisation. 
`Registered members` is a special organisation to assign resource permissions to any registered member (which also inherits permissions from the `contributors` role)

Does it make sense?

**Comment by gannebamm** [comment]
Absolutly! This is one of the major issues in understanding the groups in geonode at the moment. Our users want to group (=organize) data and also provide access restrictions based on groups.

**Comment by giohappy** [comment]
@gannebamm in fact, when GorupProfile will be splitted from Groups and renamed to Organizzatos it willl make more sense. At that point the final step will be to model the assignment of Groups (ie roles) to Organizzatos and not only single users.

Finally we will have what customers really want :)

**Comment by giohappy** [comment]
An additional note, to keep track of the reasoning behind this proposal:

- I also considered the option to introduce a new Role model, to clarify this kindcof grouping, but I thought it would have added complexity without relevant benefits
- this proposed approach has one limitation. It assumes that permissions for a user is the union of its own and its groups. We don't have the means to consider the intersection instead, so we cannot restrict the permissions.
