### ISSUE TITLE
Fix some italian translations

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#7465]
- [x] Create Layer
    - Points, Lines, Polygons -> Punti, Linee, Poligoni
    - String, Integer, Double, Date -> Testo, Numero intero, Numero decimale, Data
 - [x] Service page > Edit Service Metadata --> Modifica metadati servizio
 - [x] Fix msgid_plural: gettext creates plural translations for Map/Maps, Layer/Layers, Document/Documents, etc. These translations are not correctly managed by the normal gettext translator (they need nbgettext), so {% tran %} tags fail to correctl translate the singular version (see image below for an example). Appraently it works for the pluaral stringa, but it's because probably the plural msgid is taken by default

![image](https://user-images.githubusercontent.com/571129/116895759-d1512e00-ac33-11eb-8bd5-2b30ee371181.png)

![image](https://user-images.githubusercontent.com/571129/116895780-d57d4b80-ac33-11eb-9f2c-9e0192b20381.png)

**Comment by giohappy** [comment]
@mattiagiupponi branch [ISSUE_7465](https://github.com/GeoNode/geonode/tree/ISSUE_7465) already contains the fixes for the first two points.

**Comment by gannebamm** [comment]
Maybe those were introduced by my latest translation fixes (#7413) and I did not spot them, sorry

**Comment by mattiagiupponi** [comment]
> Appraently it works for the pluaral stringa, but it's because probably the plural msgid is taken by default

@giohappy looks like that the plural does not work anyway. You see the translations "Documenti" only because is defined inside the `.po` file https://github.com/GeoNode/geonode/blob/cda6cc9f4e76d46bc64841a8e614ddd374200d78/geonode/locale/it/LC_MESSAGES/django.po#L1643-L1644
Layers and Maps works only because are defined here (plural):
https://github.com/GeoNode/geonode/blob/cda6cc9f4e76d46bc64841a8e614ddd374200d78/geonode/locale/it/LC_MESSAGES/django.po#L1637-L1641
Here singular:
https://github.com/GeoNode/geonode/blob/cda6cc9f4e76d46bc64841a8e614ddd374200d78/geonode/locale/it/LC_MESSAGES/django.po#L4977-L4978

So it looks like that the `msgid_plural` is not totally working as expected. Gonna investigate more

**Comment by giohappy** [comment]
@mattiagiupponi for sure having the msgid for plurals alone will hide the mosgid_plural mechanism. This should be avoided.
We can try removing the msgid that you reported.

**Comment by mattiagiupponi** [comment]
> @mattiagiupponi for sure having the msgid for plurals alone will hide the mosgid_plural mechanism. This should be avoided.
> We can try removing the msgid that you reported.

I'm going to remove the single translation, but i need also to change the `{% trans "Document-s/Layer-s/Map-s" %}` into `{% blocktrans count counter=1 %}Document/Layer/Map{% plural %}Documents/Layers/Maps{% endblocktrans %}` 
where:
- counter=1 -> singular
- counter=2 -> plural

in order to correclty use the `msgid_plural`
refs: https://docs.djangoproject.com/en/2.2/topics/i18n/translation/#std:templatetag-blocktrans & 
https://stackoverflow.com/questions/33220269/django-template-translation-zero-is-plural-in-fr

ps: block name will change in Django3. is renamed from `blocktrans` to `blocktranslate `

**Comment by giohappy** [comment]
I would get rid of msgid_plural for these labels. The pluralization facilities are never used inside templates.
BTW I don't know if Django forces the msgid_plural thing when running makemessages.

**Comment by giohappy** [comment]
@gannebamm apparently django (xgettext) adds the pluralization automatically (and independently from the [Plurals header](https://github.com/GeoNode/geonode/blob/master/geonode/locale/it/LC_MESSAGES/django.po#L50)). I searched everywhere it there was an option to disable it, even with a custom makemessages command, but it looks like no solution is available.

On the other side I don't like to use the `{% blocktrans count counter=1 %}` as a workaround for this, considering that pluralization mechanisms are used nowhere in GeoNode templates.

The only solution that I can see is to stop using makemessages and edit .po files only manually, with Poedit or similar tools.
Do you see other options @gannebamm?

**Comment by gannebamm** [comment]
Editing .po files manually and manually add new entries for new gettext is not a valid option IMHO.

tbh I did not completly understand the issue, yet. There should be the plural msgids, eg for german:
https://github.com/GeoNode/geonode/blob/master/geonode/locale/de/LC_MESSAGES/django.po#L2169-L2172

and for italian:
https://github.com/GeoNode/geonode/blob/master/geonode/locale/it/LC_MESSAGES/django.po#L2183-L2186

Those are not fetched correctly?

**Comment by giohappy** [comment]
See my first image @gannebamm. I expect it happens with german too: you will see Document/Map/etc. instead of the translated string. This happens because trans doesn't parse plurals. {% blocktrans count counter=1 %} must be used instead (counter=2 in case of the plural version). It's a it looks more a workaround then a solution, but if we want to keep using makemessages I fear there's no other way...

**Comment by t-book** [comment]
@giohappy 

> I searched everywhere it there was an option to disable it, even with a custom makemessages command, but it looks like no solution is available.

have you tried a header like:
`Plural-Forms: nplurals=1; plural=0;`

**Comment by giohappy** [comment]
I did @t-book but it doesn't same to have any effect.
As expected the issue happens also with german

![image](https://user-images.githubusercontent.com/571129/117118004-7f71ea80-ad90-11eb-8314-76e9b1618cf9.png)

**Comment by gannebamm** [comment]
I was not aware of that and it was working before I think? I will do some tests on my instance tomorrow.

**Comment by giohappy** [comment]
thx @gannebamm.
Please share your tests if you can.

**Comment by gannebamm** [comment]
You are right:
This seems ok, but if only 1 document will be fetched it displays the german plural 'Dokumente' instead of the singular.
![grafik](https://user-images.githubusercontent.com/6172324/117327085-87b24e80-ae92-11eb-9480-d44f0e198746.png)
Furthermore, the edit modal shows English strings as well:
![grafik](https://user-images.githubusercontent.com/6172324/117327270-b4fefc80-ae92-11eb-9969-0499d20b45cf.png)
But I also see loads of duplicates in the .po file. See:
![grafik](https://user-images.githubusercontent.com/6172324/117327489-f1caf380-ae92-11eb-8d99-098193e14df8.png)

**Comment by giohappy** [comment]
We'll need to open a new issue to fix the plurals thing....
