### ISSUE TITLE
UUID error when uploading layer metadata

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#7693]
## Expected Behavior

When uploading metadata for an existing layer, if the UUID in the xml is the same of the current layer, the system should not raise any error.

## Actual Behavior

This error is returned:
```
Unexpected error! - Unknwon Error Code. Contact the system administrator for more information regarding this error message. Additional info: [Client Error: Bad Request
The UUID identifier from the XML Metadata is already in use in this system.]
```

## Steps to Reproduce the Problem

  1. Download a metadata of a layer
  2. Edit the xml document (e.g.: change the title or the abstract)
  3. In the layer page in Geonode, click on "editing tools" -> "upload metadata"

## Specifications

  - GeoNode version: 3.2.x

**Comment by etj** [comment]
There was a previous discussion about this on #6704, but mainly aimed at metadata upload for new layers.

**Comment by gannebamm** [comment]
Hi @etj,
you are right. I will check if we have fixed this already since we proposed the UUID reading from XML files.

**Comment by gannebamm** [comment]
Ok, this is our _fix_. It will work, but is not very robust:
```
diff --git a/geonode/layers/utils.py b/geonode/layers/utils.py
index 225aaf3602c3d490113cec3529439427853962b2..c248941aa2bb5efff01172005ee9b80052099f3f 100644
--- a/geonode/layers/utils.py
+++ b/geonode/layers/utils.py
@@ -600,7 +600,7 @@ def file_upload(filename,
             defaults['metadata_xml'] = xml_file
 
         if identifier:
-            if ResourceBase.objects.filter(uuid=identifier).count():
+            if ResourceBase.objects.filter(uuid=identifier).count() and not (len(files) == 1 and files['xml']):
                 logger.error("The UUID identifier from the XML Metadata is already in use in this system.")
                 raise GeoNodeException(
                     _("The UUID identifier from the XML Metadata is already in use in this system."))
```

**Comment by afabiani** [comment]
@etj this was intentional in order to prevent people overwriting metadata of wrong resources.

Which is the proposal to avoid issues with that? How GeoNode should behave in this case?

**Comment by gannebamm** [comment]
For our fork the researchers sometimes modified the downloaded xml files and reuploaded those. They should overwrite the layers current metadata. The changes mentioned above will enable this behaviour. If someone uploads a geodataset and xml metadata the file count >1 and the upload will fail.

**Comment by mattiagiupponi** [comment]
I made some tests and some debug on this and looks like that the Upload metadata is not working as expected.

**Short story:**
looks like that the Upload Metadata function is creating a new layer with the metadata, instead of updating the existing one.

**Long story:**
The upload metadata `/layers/geonode:layername/metadata_upload` is handled by this function:

https://github.com/GeoNode/geonode/blob/e3ddf79532e89afe3f66924433510454c451081b/geonode/layers/views.py#L220

If we scroll down, we can see that the upload of the metadata file, is handled by the legacy `file_upload` with the `overwrite` param set as `FALSE`, and the `layer` instance is not passed

https://github.com/GeoNode/geonode/blob/e3ddf79532e89afe3f66924433510454c451081b/geonode/layers/views.py#L266-L276

Since in the XML file, there is a UUID (that is different from the one saved in the DB unless you are uploading the XML with the initial upload) in the `file_upload`, after extracting all the metadata, we arrive at this ELSE:
https://github.com/GeoNode/geonode/blob/e3ddf79532e89afe3f66924433510454c451081b/geonode/layers/utils.py#L607-L611

So since the UUID (hopefully) does not exist, a new layer is created with the metadata extracted by the parser.
And this is the results on the DB (base_resourcebase)

![image](https://user-images.githubusercontent.com/51856725/123133435-0289f580-d450-11eb-8a4c-7d0c06bb60c0.png)

During the development of the GNIP-89 this issue is already fixed since we remove the usage of `final_upload` and the function for upload the XML and sld has been refactored:

https://github.com/GeoNode/geonode/blob/fcb70d782c06418faf239afab8b5dbe926e77ec5/geonode/layers/views.py#L205-L216

Where we use the typename (coming from the FORM itself) to identify the layer and update his metadata:

https://github.com/GeoNode/geonode/blob/fcb70d782c06418faf239afab8b5dbe926e77ec5/geonode/layers/views.py#L256-L257

**Solutions**

We can merge only this functionality in GeoNode `master` and `3.2.x` in order to make the` upload metadata` works as expected

**Comment by etj** [comment]
Well, if we are only uploading metadata for a layer, I guess that the creation of a brand new layer is plainly wrong.

About handling the UUID, I'd propose this flow:
- If the fileIdentifier in the uploaded metadata doc exists:
  - if it's the same as the current layer, it's ok
  - if it's different, an error should be triggered
- if it does not exist, it's ok

Pls note that in the use case in which 
1. the metadata is downloaded, 
2. some fields are updated (not the UUID), 
3. and then the edited metadata is used in the same layer from which it comes from,
if we search for a layer with that UUID, we'll find at least one, that's the one we're going to update

**Comment by mattiagiupponi** [comment]
We decided to remove also this line in the metadata parsing

https://github.com/GeoNode/geonode/blob/21cb22f6ee56ecf06d5f92b1ccba37117a34ad86/geonode/layers/metadata.py#L67

This line prevents being able to upload an XML without the identifier, by creating one.
