### ISSUE TITLE
Metadata wizard: mandatory tag does not switch to green

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#7747]
## Expected Behavior
"Mandatory" label switch to green once the mandatory fields are filled in.

## Actual Behavior
"Mandatory" label does not switch to green once the mandatory fields are filled in:

![image](https://user-images.githubusercontent.com/571129/124772696-8a85fa00-df3c-11eb-921f-3f8169f6cbe0.png)

## Steps to Reproduce the Problem

  1. Open a layer
  2. Opend the advanced edit
  3. Quality statement is empty, but even if you populate it the tab remains red

The problem are the wysiwyg editors. Either we make it work for the wysiwyg editors too or, a quick and dirty solution, is setting a default value for those fields, as we're doing for the Abstract field.

**Comment by mattiagiupponi** [comment]
The issue, as you said, is caused by the `WYSIWYG` editor.
The label `Required` will be filled only when the metadata is saved. The problem here is caused by the nature of the `WYSIWYG` editor.
The test inside it is handled with an iframe:
![image](https://user-images.githubusercontent.com/51856725/124777327-6b896700-df40-11eb-87d1-79cbf587f360.png)

Even if we use a `default value to fill the text are, the issue will not be solved, because if you remove the value from it and since the text that is changing is inside an iframe, the `onChangeEvent` is not triggered and the completeness of the metadata will stay 100%.
From my point of view, we have two choices:
- remove the `WYSIWYG` editor and handle it like a normal text are (by renouncing to all of the related features)
- remove the text areas with the `WYSIWYG` editor from the required field

@giohappy @etj any thoughts?

**Comment by etj** [comment]
The idea was to remove the wysiwyg editor. AFAIK it was requested and implemented long ago, but it's giving more issues than benefits
Furthermore, text from that editor has to be normalized to be displayed and to be inserted into the XML metadata

**Comment by giohappy** [comment]
@mattiagiupponi we can manage the [native events](https://www.tiny.cloud/docs/advanced/events/) triggred by TinyMCE, by installing the callbacks inside the [setup](https://www.tiny.cloud/docs-3x/reference/Configuration3x/Configuration3x@setup/) option.

I've added the following line to the [TINYMCE_DEFAULT_CONFIG](https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L1553):

`"setup": 'function(editor) {editor.on("init", function(e) {console.log("The Editor has initialized.");});}'`

and I could see the log in the browser:

![image](https://user-images.githubusercontent.com/571129/124801376-13aa2a80-df57-11eb-9373-d00dc624b2a9.png)
