### ISSUE TITLE
GeoNode shows incorrect keywords

### ISSUE THREAD

**Issue by chpicone** [GeoNode/geonode#7750]
## Expected Behavior
With hierarchical keywords we want to correctly see the assigned keywords to a resource also if we assign to the resource just a leaf keyword.
Example of 3 levels keywords:
![image](https://user-images.githubusercontent.com/2872823/124906388-4c91e000-dfe7-11eb-8d4a-585929c1cc48.png) 
If we assign just the keyword KC to a resource we want to see it correctly assigned in the **keywords** section of the layers page.

## Actual Behavior
When we assign just the keyword KC and depending of the creation order of the keywords we cannot see the assigned keyword to the resource:
![image](https://user-images.githubusercontent.com/2872823/124903753-8f9e8400-dfe4-11eb-9b5e-6335f7752c44.png)

## Steps to Reproduce the Problem

  1. Create a 3 levels keywords (eg KA, KB, KC)  
![image](https://user-images.githubusercontent.com/2872823/124906388-4c91e000-dfe7-11eb-8d4a-585929c1cc48.png) 
  and assign just the keyword KC to a resource (R1) 
  2. Open the "Explore Layers" page and take a look on the **keywords** section.
  3. Depending on the order of creation of the keywords and the nodes hierarchy you cannot see the keyword

## Specifications

  - GeoNode version: 3.2.0
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual, GeoNode Docker
  - Platform: Ubuntu 18.04
  - Additional details:

**Comment by gannebamm** [comment]
Maybe related to: https://github.com/GeoNode/geonode/issues/6727 ?

**Comment by giohappy** [comment]
@gannebamm yes it's realted, by the way the issue here is about resources which have assigned child keywords but not their parents, and a problem when the parent is created after the children. Both break the method that collects the keywords for the resource and, consequently, their visualization.

The upcoming PR from @asgharsir will solve both the problems. The method will return the assigned keywords and all the parents tree of them. We're not going to assign the parents to the resource. They will be returned dynamicaly, so no need to keep track of changes (assign, unassign, etc.).
