### ISSUE TITLE
Separate upload execution from client actions and polling

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#7857]
The current upload procedure depends on the execution steps invoked by the client. The async nature of the upload API is only partial, meaning that without the active collaboration of the upload page it won't be finalized. Moreover, status polling from the client operates on the same execution endpoints, which leads to interference that can make [race conditions arise](https://github.com/GeoNode/geonode/blob/3.3.x/geonode/upload/models.py#L224-L231).

The [upcoming Resource Service API](https://github.com/GeoNode/geonode/pull/7829) will solve these issues, but for the time being we need to keep using the current upload mechanism (client and backend), also considering that the new RS is only available on master branch, and we want to fix these issue also on 3.3.x.

The key aspects to address are:

 - make the upload procedure independent from client requests, except when user input is required to proceed (e.g. when a dataaset is eligible to be configured as a time series). For this task a [Celery chain](https://docs.celeryproject.org/en/latest/userguide/canvas.html#chains) might be a good candidate
 - separate status polling code from execution code

This should also solve https://github.com/GeoNode/geonode/issues/7836

**Comment by afabiani** [comment]
So, after taking a look again at the workflow, currently we can get only two possible situations, both depending on the `Importer Session` state:

1. Wait for more inputs; no further processing needed until the user does not provide some inputs
2. Move to the `final_step`, which usually takes a lot of time because it needs to finalize the GeoServer configuration

That said, IMHO, we don't need to use a complex mechanism like Celery chain, just correctly setting the processing state of the `Upload` session and delegate the final execution to an async task will be sufficient.

We will also prevent the GUI to actively invoke the `final_step` of course.

**Comment by afabiani** [comment]
Please check the PR https://github.com/GeoNode/geonode/pull/7859

That one also replaces https://github.com/GeoNode/geonode/pull/7858
