### ISSUE TITLE
Wrong Zoom and Center attributes in ResourceBase and others

### ISSUE THREAD

**Issue by asgharsir** [GeoNode/geonode#7878]
`ResourceBase` doesn't have any zoom, but refers to `self.zoom`. This will impact any polymorphic expectations and impacts the methods: `set_center_zoom` and `set_bounds_from_bbox`.

`GXPMapBase` doesn't have any zoom attribute, but it also refers to `self.zoom` which is impacting `viewer_json`.

Importantly the problem was realized. But instead of fixing the bases, an __init__ is implemented on `GXPMap`. The purpose could be to customize the `GXPMap`, which is based on `GXPMapBase`. But in that case also:
- The `ResourceBase` and `GXPMapBase` are not corrected.
- Although some morphs of `ResourceBase` may not need `zoom, center_x, center_y` etc, but `Map` may always need them. So do we need to have these properties in `GXPMapBase` or in `GXPMap`?

Similar may be the case of the attribute `projection`, or any other,  but I have yet to see in detail.

Above is in all three branches: master, 3.3.x, and 3.2.x. and is potential source of any users/developers bugs.

**Comment by giohappy** [comment]
@asgharsir AFAICS `self.zoom` is not meant to be stored, it's only useful to make runtime calculations based on other model attributes. For example `self.zoom` is calculated from the `bbox_polygon` field. Methods connected to self.zoom are used while preparing the configuration for the map.

The whole thing about `GXPMapBase` and `GXPMap` should be reivewed, since these are models coming from very old versions of GeoNode (where GeoExt was used as the internal webgis client). I'm aware that this is confusing but it's sort of a rabbit hole, and for the moment we don't want to focus on this refactoring. There already enough moving parts right now! :)
