### ISSUE TITLE
Wrong URL inside Admin profile -> GeoServer Tab.

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#8051]
@drumbsd commented on [Mon Sep 06 2021](https://github.com/GeoNode/geonode-project/issues/230)

Hello, I'm using 3.3.x. If you login as admin inside geonode, goes on profile page, then click on GeoServer link you see that the code seems to use the **GEOSERVER_LOCATION** value instead of use **GEOSERVER_PUBLIC_LOCATION**

So the link is not working.

![image](https://user-images.githubusercontent.com/6428880/132230455-736f9370-25cd-47d1-b58f-34abdeae86a7.png)

![image](https://user-images.githubusercontent.com/6428880/132230356-faacd8b3-b921-48e8-b570-0d26fa935035.png)

**Comment by marthamareal** [comment]
@giohappy  the url in the link is defined [here](https://github.com/GeoNode/geonode/blob/master/geonode/people/templates/people/profile_detail.html#L178) which uses the GEOSERVER_LOCATION in the settings.
1. Should we edit the template to use the `GEOSERVER_PUBLIC_LOCATION`

2 . Also I get this error when I click on the link `The proxy service requires a URL-encoded URL as a parameter.` should it be fixed here? (what is the expected behavior?

**Comment by giohappy** [comment]
@marthamareal you simply have to use [GEOSERVER_WEB_UI_LOCATION](https://github.com/GeoNode/geonode/blob/d117d0889dae23ed6e5ff404750dee13b9e98dda/geonode/settings.py?plain=1#L988) as we do [inside the user dropdown](https://github.com/GeoNode/geonode/blob/d117d0889dae23ed6e5ff404750dee13b9e98dda/geonode/templates/base.html?plain=1#L420)

**Comment by giohappy** [comment]
@marthamareal I noticed that the problem is also visible in 3.2.x. So please backport to 3.2.x and port forward to master.
