### ISSUE TITLE
Move Maps API responsibilities from  geonode-mapstore-client to GeoNode

### ISSUE THREAD

**Issue by italogsfernandes** [GeoNode/geonode#8394]
# Move Maps API responsibilities from  geonode-mapstore-client to GeoNode

## Overview

* To create/update a map by API, the geonode api calls the mapstore-client [perform_create](https://github.com/GeoNode/geonode-mapstore-client/blob/master/mapstore2_adapter/plugins/serializers.py#L228) and [perform_update](https://github.com/GeoNode/geonode-mapstore-client/blob/master/mapstore2_adapter/plugins/serializers.py#L243), so the client handles the creation and calls different parts of geonode in order to do it.
* They are highly coupled (in a complicated mix of responsibilities).
* Because of that, some legacy code from `GPX*` classes and others are still being called, blocking the drop of this code.

**Comment by italogsfernandes** [comment]
@giohappy 
Some questions arrived to me during the development:

- The geonode mapstore client uses [utils.resolve_object](https://github.com/GeoNode/geonode/blob/master/geonode/utils.py#L1035) to get the map instance, but the instance is already retrieved by the [MapViewSet.get_object](https://github.com/GeoNode/geonode/blob/master/geonode/maps/api/views.py#L73). In this case, I'm not sure whether is needed to re-retrieve using `resolve_object` or not, it seems that the `resolve_object` handles some permissions that I don't know if they are already being handled by the [MapViewSet permissions](https://github.com/GeoNode/geonode/blob/master/geonode/maps/api/views.py#L49) or not.
    - If needed, I think the best approach would be to create a permission class handling the permission part of the `resolve_object`.
    - During the refactor, I removed the `resolve_object` call to get the instance, should I add it back?

- Also, currently the client sends: `title`, `abstract`, `thumbnail_url` and `data` (the `blob`), when posting or patching to `/api/v2/maps/26/?include[]=data`.
    - The maplayers objects are created/updated from the data sent inside the `blob`.
    - Should the client be changed and send the `maplayers` info separately from `blob`? Or should geonode do a pre-creation/pre-update step, for extraction the maplayers from the `blob`?

**Comment by giohappy** [comment]
@italogsfernandes 

- Unfortunately the `resolve_object` has been used to ensure the assignment of some permissions, which was a very unhappy solution. We were dicsussing this right in the past days with @afabiani, but the moment I guess we need to keep it as it is. I suspect that we will have to keep using `resolve_object` until that specific permission logic isn't removed from that methos. In ayn case **don't port it inside the API**. Just use `resolve_object` for the time being. Opinions @afabiani?
- The client will pass the required data, otherwise all this refactoring was useless. GeoNode should never put its nose into the blob field.

Can you please rename the `Map.datasets` field to `Map.maplayers`? We use `datasets` for `layers.models.Dataset`, but you're using this name to refer to maps'maplayers, which is misleading.

**Comment by afabiani** [comment]
@giohappy @italogsfernandes that method is useful in particular when the advanced workflow has been enabled, it assigns some permissions accordingly to the current user status... this must be changed. There's some work in progress (for the time being on 3.3.x branch) to get rid of this approach.

Let's keep that for the moment. I would suggest to include the removal of this method on another specific PR.
