### ISSUE TITLE
API: error in accessing keyword info

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#8507]
## Actual Behavior

When requesting a resource info, we get only references to the keywords:
```bash
curl -s  https://development.demo.geonode.org/api/maps/78/ | jq . | grep -A2 '"keywords"'
```
```json
  "keywords": [
    "/api/keywords/21/"
  ],
```

If we want some more info on the keywords, we can't have any:
```bash
curl -is https://development.demo.geonode.org/api/keywords/21/ | head -n4

HTTP/1.1 401 Unauthorized
Server: nginx/1.17.2
Date: Thu, 16 Dec 2021 22:16:24 GMT
Content-Type: text/html; charset=utf-8
```

## Expected Behavior

- Since most of the info are unpacked inside the resource JSON, I expect also the keywords should be represented with their full info.
- Also, the keywords APU should be accessible without any particular permission.

## Steps to Reproduce the Problem

  1. make sure a resource exists with tags in its metadata (create one or use an existing one)
  2. perform the queries at the top of this description.

## Specifications

  - GeoNode version: 
     - 33x: yes (checked on development.demo.geonode.org)
     - 32x: to be checked
     - master: to be checked

**Comment by giohappy** [comment]
@etj do you specifically need API v1? API v2 works as expected.
In case v1 is needed we would need to override `DjangoAuthorization.read_detail` (from which [ApiLockdownAuthorization](https://github.com/GeoNode/geonode/blob/1e4bba7c2768345ffdde6c151352b5b01e44c0d8/geonode/api/authorization.py#L152). DjangoAuthorization [applies](https://django-tastypie.readthedocs.io/en/latest/authorization.html#djangoauthorization) `change` permission for read operations, that's why it blocks anauthorized GET requests.
The fix is easy:

```
def read_detail(self, object_list, bundle):
        user = bundle.request.user
        return False if (settings.API_LOCKDOWN and not user.is_authenticated) else True
```

however, this affects all the other endpoints too. The Owners and Profiles endpoints are already protected within their own `dehydrate` methods. The only endpoint too wide open is Groups. I would consider to limit it to public groups.

**Comment by giohappy** [comment]
as agreed with @etj there's no urgent need to change API v1, so I'm closing this.
