### ISSUE TITLE
Feature Templates break on new maps

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#8623]
## Expected Behavior
If I create a FeatureTemplate for a layer it will be used in maps to render the getFeatureInfo.

## Actual Behavior

The template will only get rendered if there are no other layers in the TOC or as part of the layer preview:

template:
![gft-1](https://user-images.githubusercontent.com/6172324/149749821-53a44b57-f346-4769-a75f-9bef77b621cb.PNG)

layer preview:
![gft-2](https://user-images.githubusercontent.com/6172324/149749834-ff8b47c2-dfe7-4bdd-87b9-224f7af502ee.PNG)

new map:
![gft-3](https://user-images.githubusercontent.com/6172324/149749853-181d9b63-6da4-4400-b3a1-cf2c5b030c7c.PNG)

map with additional layer:
![gft-4](https://user-images.githubusercontent.com/6172324/149749868-b671fc6f-27df-4a38-aacf-944ab0687c28.PNG)

## Steps to Reproduce the Problem

  1. create a custom template
  2. create new map with layer
  3. add same layer to map
  4. identifiy a feature

## Specifications

  - GeoNode version: 3.3.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Docker

**Comment by gannebamm** [comment]
I was not able to reproduce it again. I saved the map with a new title and the issue vanished. I will close this for now.

**Comment by giohappy** [comment]
@gannebamm just in case it was the case, if a layer is loaded from the MapStore client catalogue the featuretemplate is not applied until the map isn't saved. This is becasuse the CSW catalogue doesn't return the template so, until you don't reload save and reload the map, the client won't receive the featuretempalte for the layer.

This has changed in master branch, since we implemented a specific GeoNode MapStore catalogue, which uses the API instead of the CSW sergice.
