### ISSUE TITLE
Extend the ResourceBase metadata model with an opaque JSONField

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#8689]
## Overview/Description of the desirable
As a data owner/editor I would like to be able to extend the current metadata fieldset with some specific fields belonging to a particular concrete instance.

This use case is particularly significant with the concept of `GeoApp`; a `GeoApp` is an abstract container for any kind of generic resource which can be plugged on GeoNode other than the core ones.

However this applies also to the core resources, whenever I would like to add more custom metadata fields without necessarily being forced to change the `ResourceBase` model.

## Proposal
The technical proposal would be to add a generic `JSONField` along with a `json-schema` allowing us to be able to read/write some additional metadata fields to the `ResourceBase` without changing the model/db.

The `json-schema` will define a list of extra `metadata-fields`, each one identified by the current list of attributes:

 - The metadata field name and slug
 - The metadata field help text
 - The metadata field type
 - The metadata field occurrences

The `JSONField` will actually contain the values provided by the users.

### Constraints

- I should be able to define via conf/settings the `json-schema`, given a template, related to a specific concrete instance or GeoApp
- I should be able to allow users with permissions to read/write such parameters via the `REST API`; the input should be always validated through the provided `json-schema`
- On a legacy GeoNode, those additional fields should be dynamically rendered on a dedicated section of the `Metadata Editor` form,  both `advanced` and `wizard`
- On a legacy GeoNode I should be able to filter against those extra-parameter values via the `API V1` too 

### Edit
 - Accordingly to the [issue](https://github.com/GeoNode/geonode/issues/8690) we should probably envisage also a sort of `filter category` or `filter label` associated to each `custom metadata field` present into the opaque `json`.

**Comment by gannebamm** [comment]
I would like to echo this

> However this applies also to the core resources, whenever I would like to add more custom metadata fields without necessarily being forced to change the ResourceBase model.

We currently think about extending the RessourceBase model with metadata fields used in specific research domains, like soil science or social studies. The drafted feature would enable this 🚀

**Comment by mattiagiupponi** [comment]
@afabiani follows a brief idea of how to approach the development

### models.py:

```python
class ResourceBase
    .........
    extra_metadata = JSONField(null=True, default=list, blank=True)
```

### Settings.py:

Definition via settings the JSON schema for each resource.
We can expect to have something like:
```python
DEFAULT_EXTRA_METADATA_SCHEMA = {
  "name": None,
  "slug": None,
  "help_text": None,
  "field_type": None,
  "value": None
}

EXTRA_METADATA_SCHEMA = {
  "map": os.getenv('MAP_EXTRA_METADATA_SCHEMA', DEFAULT_EXTRA_METADATA_SCHEMA),
  "dataset": os.getenv('DATASET_EXTRA_METADATA_SCHEMA', DEFAULT_EXTRA_METADATA_SCHEMA),
  "document": os.getenv('DOCUMENT_EXTRA_METADATA_SCHEMA', DEFAULT_EXTRA_METADATA_SCHEMA),
  "geoapp": os.getenv('GEOAPP_EXTRA_METADATA_SCHEMA', DEFAULT_EXTRA_METADATA_SCHEMA),
}
```
In this way, each resource could have a different metadata JSON schema. 
Having the resource_type as a key helps GeoNode be pluggable by external apps.
apps.py
```python
from django.conf import settings
class MyAppConfig(AppConfig):
    name = "my_app"

    def ready(self):
        my_json_structure = {"a": "b"}
        settings.EXTRA_METADATA_SCHEMA['my_content_type'] = my_json_structure
        super(MyAppConfig, self).ready()
```

### API:
list:
The new field will be added to the `ResourceBase` endpoint, similar to what we did for the blob field. So by default will be added, if needed it can be retrieved via `/api/v2/geoapp?include[]=extra_metadata`
creation:
same way as to work now for the blob field

### Legacy:
For the legacy metadata editor we have two options from my POV:
- Add a text area that contains the whole JSON structure extracted. In that way, the user can `edit/add/delete` the data. On save, the `view` will evaluate the JSON structure.
**PRO**: the view needs to evaluate a single field. **CONS**: having all in a single text area is error-prone
- On the UI, we render the JSON as a table by converting each JSON row into a table row. In this way, the user can add `edit/add/delete` the data without considering the JSON structure. On save, the `view` will convert this table into the expected JSON structure and save it into the DB
**PRO**: the structure is handled by the backend. **CONS**: require important work from the UI side (new tab, form update, validations)

For the legacy API, we need to evaluate if `Tastypie` is ready to handle this.

**Comment by afabiani** [comment]
@mattiagiupponi your proposal could work, few comments below:

1. About the `jsonschema` I would use a standard one like we do as an instance [here](https://github.com/GeoNode/geonode/blob/master/geonode/security/permissions.py#L103); in that case it would be easier to validate the resulting JSON through the `jsonschema` package (e.g. [here](https://github.com/GeoNode/geonode/blob/master/geonode/security/permissions.py#L594))
2. Let's make sure the `EXTRA_METADATA_SCHEMA` can be populated from external settings too being able to get other schemas too; a common use case might be the one using a `geonode_project` instance and defining there a new `GeoApp` or `Resource` that we want to inject into GeoNode
3. About the API V2 not the best, we are forced to always write the whole JSON blob and therefore updating all the `extra_metadata` fields... but as an initial approach it's ok.
4. Legacy: for the time being let's go for the easiest one. We have `jsonschemas` so maybe we can make the `Form` being able to validate the inputs before storing them. The same applies for the API V* `write` operations.

**Comment by mattiagiupponi** [comment]
> About the jsonschema I would use a standard one like we do as an instance here; in that case, it would be easier to validate the resulting JSON through the jsonschema package (e.g. here)

As we discuss, we will try to use this [schema library](https://github.com/keleshev/schema) (we already use it in other projects) instead of that `jsonschema` package for those reasons:
- less verbose JSON schema (the schema is customizable)
- easy validation process

> 2. Let's make sure the `EXTRA_METADATA_SCHEMA` can be populated from external settings to being able to get other schemas too; a common use case might be the one using a `geonode_project` instance and defining there a new `GeoApp` or `Resource` that we want to inject into GeoNode

ok!

> 3. About the API V2, not the best, we are forced to always write the whole JSON blob and therefore update all the `extra_metadata` fields... but as an initial approach, it's ok.

I'll evaluate other approaches while working on it

> 4. Legacy: for the time being let's go for the easiest one. We have `jsonschema` so maybe we can make the `Form` being able to validate the inputs before storing them. The same applies to the API V* `write` operations.

Ok, I'll let the form use the above library to validate the input from the users

**Comment by afabiani** [comment]
@mattiagiupponi ok nice, let's proceed!

**Comment by mattiagiupponi** [comment]
> I'll evaluate other approaches while working on it

I'm working on the API v2 part of this development @afabiani.
The main issues about using the `include[]=extra_metadata` are the following:
- we must pass the whole `JSON` every time we need to update the resource
- having the whole metadata on the main page could raise some **performance issues** (imagine having 400 dynamic metadata for each resource)

I can suggest another approach to it.
The idea will be to have for each resource (layers/datasets, maps, documents and geoapp) a new `url_path` which contain the metadata, something like `/api/v2/geoapp/{resource_id}/extra_metadata`. With this approach we can:
- pass to the endpoint just the `JSON` with the extra metadata ignoring the whole structure
- The endpoint can be done in `GET/PATCH` to `retrieve/update` the metadata
- The performance issues could be reduced since we can load at-max the metadata for a single resource (we can always think about paginating them)

as an instance, is the same approach that we already follow for `MapLayer` or set the resource permissions

**Comment by afabiani** [comment]
@mattiagiupponi agree, this is what I thought too intially

**Comment by mattiagiupponi** [comment]
@afabiani , I would like to discuss a possible requirement change related to metadata storing.
`ATM` we are working on a single `JSON` stored inside a field, but since the `API` should be able to perform search and filter to that JSON, in this case, we can face a few problems:
- We need every time to extract the whole `JSON`, parse it and extract only the metadata that we need
- Most of the filtering (for extracting the metadata that we need) is not performable via `ORM`, extraction must be done via code

On the other side, I suggest changing the implementation as follow:
- Splitting the metadata concept to another table named "extra_metadata" with ID,metadata,fk_to_the_resource
in this way, we can easily use the ORM provided by Django and most of the filtering is performed on the DB.
For example, this could be a query:
`ResourceBase.object.filter(extra_metadata__animal__in=['cat', 'dog'])`

With this query, we are going to extract all single metadata `JSON` with this characteristic.
Any thoughts?

**Comment by afabiani** [comment]
@mattiagiupponi yes, that works too. As long as we can benefit of the filters by maintaining the initial requirements, that works for me too.
