### ISSUE TITLE
Cloned resource disappears from the list

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#8773]
## Expected Behavior
Cloned resources should appear on top of the resources list.

## Actual Behavior
Cloned resource disappears from the list.
 
*possible reasons:*

- A cloned resource uses `date` of the orignal resource. hence it will not be on the top but next to the orignal resource because the list is ordered by [`-date`](https://github.com/GeoNode/geonode/blob/master/geonode/base/api/views.py#L299)

- For datasets, if the original dataset doesn't have, or have invalid files, a clone is not going to be created because of the exception thrown [here](https://github.com/GeoNode/geonode/blob/master/geonode/geoserver/manager.py#L257).

## Steps to Reproduce the Problem

  1. Clone a resource from the second page on https://master.demo.geonode.org
  2. Refresh the resources page
  3. cloned resource is not listed.

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by marthamareal** [comment]
@giohappy  @afabiani 

On cloning is it a requirement that a layer should have files and must be of valid extension to be cloned?

Also, I noticed that when you delete a cloned resource, you can not clone the original one again because the files would be deleted with the delete action of the clone.(and Vice. V)

**Comment by afabiani** [comment]
@marthamareal a cloned resource should also make a copy of the files if present IMHO.

**Comment by afabiani** [comment]
@marthamareal not a strict requirement that the original resource has files, however in the case the source has files, those should be copied and then assigned back to the cloned resource.

**Comment by giohappy** [comment]
@afabiani the points raised from @marthamareal probably refer to some problems:

1. if the original resource doesn't have files, or it has invalid files, the cloning **shuldn't** fail. From what I understand at the moment the cloning fails, making the cloned resource appear initially and then disappear from the list

@afabiani regarding the "original" files:

- we are now supporitng the upload of resources without storing the original files, because the original files are not strictly required for the functionality of master
- we are even considering the idea to stop storing the original files at all, because the new direct download will use WPS (as we do inside the client).

So, IMHO, the cloned resource shouldn't have references to the original files and we shouldn't copy them.

**Comment by giohappy** [comment]
@marthamareal of course the comments above are valid for datasets.
For documents we need to clone the original file of course.
