### ISSUE TITLE
User with perms can edit approved and published resources when Advanced workflow is enabled

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#8937]
## Expected Behavior

When Advanced workflow is enabled if the resource is approved or published, the owner and users with perms should not be able to modify it. He will see a new button on the resource detail page: Request change. After clicking this, view with short form is shown. On this view, the user can write a short message about why he wants to modify the resource.

**NOTE**: `change_resouucebase` permissions should not be included in list of perms.

## Actual Behavior

 After a group manager has approved the resource or the Admin has approved and published the resource:

- Owners and users with edit perms can still see the edit option and successfully update the approved resource.
- Then the approved and is_published are automatically set to `False`.

## Steps to Reproduce the Problem

  1. Enable Advanced workflow
  2. Log in as a member of a certain group.
  3. Create a resource and assign it to a group above
  4. Login as a group manager, and approve the resource above
  5.Login as owner, You will notice that edit option is available

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
@marthamareal if users have the edit button enabled it means that users have the `change_resourcebase` (and similar) permissions granted.

@mattiagiupponi from what I see, also on 3.3.x, this permission shouldn't be available for any user where the resource is published and approved. This is what drives, for example, the hiding of the Edit button in 3.3.x. Can you confirm=

**Comment by mattiagiupponi** [comment]
When the advanced workflow is enabled (`RESOURCE_PUBLISHING` and `ADMIN_MODERATE_UPLOADS` is True), the owner has all the permission for the resource (excluding the `publish_resource` and `change_resourcebase_permissions`).

So, is correct that the user can edit/change the resource without waiting for approval from the manager.
About the `is_publish/approved` that is set to False, it looks like an issue with the template.

All the use cases related to the advanced workflow are available here -> https://github.com/GeoNode/geonode/issues/8136#issuecomment-930061349

This permissions list is widely tested here (this is 33x)
https://github.com/GeoNode/geonode/blob/2d22f8e04c660a492b503c732936c0fcb8540068/geonode/security/tests.py#L2071 where it covers almost all the possible scenarios (including promotion/demotion of a user to group manager)

**Comment by giohappy** [comment]
It's strange @mattiagiupponi. On 3.3.x, at least in its original implementation, if the advanced workflow is configured and the resource has been approved, the owner will only be able to send a [request for changes](https://github.com/GeoNode/geonode/blob/1b0a7a9cb1ea5923c160722bd3cd0a2906009bd8/geonode/layers/templates/layers/layer_detail.html#L392-L399), but not edit the resource.

From what I see inside that template, that condition is checked against the current permissions of the owner. Am I wrong?

**Comment by giohappy** [comment]
After further analysis, and considering the [implemented rules](https://github.com/GeoNode/geonode/issues/8136#issuecomment-930061349), we need to manage the transition of a resource between `APPROVED` and `NOT APPOVED`. 

When the resource is `APPROVED` owners must be assigned only the `view_resourcebase` and  `download_resourcebase` permissions. Any editing is forbidden.
If a resource returns to `NOT APPROVED` the usual permissions for the owner are restored.

The permissions cannot just be "hidden" (i.e. not returned by [ResourceBase.get_user_perms()](https://github.com/GeoNode/geonode/blob/1b0a7a9cb1ea5923c160722bd3cd0a2906009bd8/geonode/security/models.py#L668)), otherwise the Geofence rules wouldn't be updated, and the WFS-T service would be still available to the users.
We need to actually assign / unassign the permissions through the proper GeoNode methods.

While implementing this transition (on resource save) the approach followed in the [original PR](https://github.com/GeoNode/geonode/pull/8145) should be followed, to avoid implementing new ways and reinventing the wheel.

Additional tests are also expected.
