### ISSUE TITLE
Tiff display problem

### ISSUE THREAD

**Issue by bagheeraGit** [GeoNode/geonode#9012]
Hi! 

When uploading a tiff I have the following problem (I am doing this through massive console loading)

GDAL_ERROR 1: b"/home/geonode/capas_masiva/GEOTIF/ortomosaico.tif: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples."

Can someone help me with the problem and how to solve it?

Greetings.

**Comment by t-book** [comment]
Can you try to gdal_translate your image to 3 bands before uploading? My guess is gdal is trying to convert your image but is failing.

**Comment by mattiagiupponi** [comment]
closing due lack of feedbacks

**Comment by kikislater** [comment]
gdalinfo on this dataset could help solve the problem

The problem is this part is that geoserver doesn't use gdal but hardcoded in geoserver. Geoserver doesn't support geotif with jpeg and transparency. It seems to have a 4 bands channel regarding the output (most of output from drone photogrammetry software are geotif with jpeg and transparency). Doing a conversion with gdal_translate could solve import
