### ISSUE TITLE
module 'bleach.sanitizer' has no attribute 'ALLOWED_STYLES'

### ISSUE THREAD

**Issue by nicokant** [GeoNode/geonode#9263]
## Expected Behavior
Geonode starts and renders the home page

## Actual Behavior
I get a 500 error: `module 'bleach.sanitizer' has no attribute 'ALLOWED_STYLES'`

## Steps to Reproduce the Problem

  1. setup a geonode project using 3.2.x branch
  2. build and run with docker
  3. open the browser

## Specifications

  - GeoNode version: 3.2.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Geonode project using docker
  - Platform: Linux
  - Additional details: it seems that the problem is due to `django-markdownify==0.9.0` which is solved in the `0.9.1` version, see https://github.com/erwinmatijsen/django-markdownify/issues/35.

**Comment by frafra** [comment]
It looks that the results of the tests are ignored: https://github.com/GeoNode/geonode/pull/7042
I would suggest merging PRs only if tests are not failing. If tests fails because they have issues, or we fix them, or we drop them: better fewer and reliable than many half-baked and ignored in my opinion.

**Comment by afabiani** [comment]
That dependency is there since 2021 and 3.2.x works correctly

https://stable.demo.geonode.org/
