### ISSUE TITLE
GeoNode 4 + Keycloak Integration : Not redirected to the Keycloak site unless using HEAD (curl -I)

### ISSUE THREAD

**Issue by callmeott** [GeoNode/geonode#9311]
## Expected Behavior
We used to set up a GeoNode 3.3x + Keycloak site according to https://gist.github.com/t-book/0fb30804e217bdeb064dd91b5041fbc9 and things worked well.

Now as we are trying GeoNode 4.0.0rc0, following the same steps. But when clicking at the "Sign in with Keycloak" link (which is something like https://<keycloak-hostname>/account/keycloak/login/?process=login&next=%2F ), it is supposed to redirect users to the Keycloak site.

## Actual Behavior
It doesn't redirect the user to the Keycloak site, but instead got stuck at geonode.

When checking that URL, we found that if the request is made with HEAD (i.e., curl -I), the response seems to be correct (HTTP 302, redirecting users to Keycloak).
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/7716016/167453750-68ef0207-779d-4fd6-bbf0-35697bfd8888.png">

But when using browsers or normal curl (curl -v -o /dev/null "https://<geonode-hostname>/account/keycloak/login/?process=login&next=%2F", it responds with HTTP 200, which is wrong.
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/7716016/167453786-89a878aa-d9df-4237-97fa-5abcc5252485.png">

## Steps to Reproduce the Problem

  1. Click the top-right "Sign In" link
  2. Click the "Sign in with KeyClock" link.

## Specifications

  - GeoNode version: 4.0.0rc0,
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker
  - Platform: Ubuntu Linux 20.04
  - Additional details:

**Comment by callmeott** [comment]
Changing back to django-allauth 0.44.0 seems to solve the problem.

`$ git diff requirements.txt
diff --git a/requirements.txt b/requirements.txt
index 50c578230..be55ef0e8 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -27,7 +27,8 @@ rdflib==6.1.1
 smart_open==6.0.0
 
 # Django Apps
-django-allauth==0.50.0
+#django-allauth==0.50.0
+django-allauth==0.44.0
 django-appconf==1.0.5
 django-celery-results==2.3.1
 django-filter==21.1
`

**Comment by giohappy** [comment]
@callmeott looking again at the error I think it's the same thing we faced with another provider.
The issue is that the latest version of django-allauth [requires a POST request to trigger the login flow](https://github.com/pennersr/django-allauth/commit/4f9efa9e1d63e61a4f6cd067ef6c34b5343ef4fa), while GeoNode is sengins a GET request, since this was the default behaviour in previous versions of django-allauth.

Setting `SOCIALACCOUNT_LOGIN_ON_GET=True` was enough.

Of course triggering a login with a GET has its security issues (and this is why django-allauth changed its mind on this), but I think reverting to a two years old version is even more dangerous. Several (security) fixes have been applied to django-allauth in more recent versions.

**Comment by callmeott** [comment]
I confirm setting SOCIALACCOUNT_LOGIN_ON_GET=True solved the problem.

Thank you very much,
Pattara

**Comment by edwin** [comment]
hi team,
just want to let you all know that above post save my life from hours of debugging.

🥇
