### ISSUE TITLE
Time serie selection handled by the advanced metadata panel

### ISSUE THREAD

**Issue by mattiagiupponi** [GeoNode/geonode#9821]
The time selection is going to be added to the advanced metadata page in the `settings` panel. If the `has_time` is selected a new panel for the time series settings is open:
![image](https://user-images.githubusercontent.com/51856725/183856921-e564af80-c9ab-450c-b215-54cfaf0a1ca6.png)

Based on the selection of the `presentation`, two new input boxes are loaded to let the user configure the time series:
![image](https://user-images.githubusercontent.com/51856725/183857432-b5dc422e-8d48-459b-a7d4-a3fb9dd0611f.png)
The ? open a modal with some information about "how to configure" the time series
![image](https://user-images.githubusercontent.com/51856725/183857645-afbb998d-731b-4258-a93c-58c9d35da72a.png)
Internally the `dataset_metadata` view will communicate with `GeoServer` to configure the time series. If the `has_time` is removed, also the configuration in `GeoServer` is disabled.
![image](https://user-images.githubusercontent.com/51856725/183859182-2a0b1c00-5762-462b-b8a5-42d0b67b7bac.png)

**Comment by mattiagiupponi** [comment]
After some deeper analysis and work on this feature, some issues occurred.
Let's suppose that we want to upload a new dataset with a time series (in which only the year is available) geoserver save the feature type as Integer:
![image](https://user-images.githubusercontent.com/51856725/185445558-83f1cf6a-46ba-42b0-bf09-c8f4d2236677.png)

As an instance, the time series cannot be enabled since geoserver is not able to find any data type:

![image](https://user-images.githubusercontent.com/51856725/185445652-a474307c-88c8-4b36-becf-d4b93529d85b.png)

**Comment by giohappy** [comment]
@mattiagiupponi that's too bad. I suppose GeoNode importer configures the [dateformattransform](https://docs.geoserver.org/latest/en/user/extensions/importer/rest_reference.html?highlight=store#dateformattransform) transformation.

The new importer shouldn't have this problem, since we publish from the DB and the field type should be automatically recognized. Do you confirm @mattiagiupponi?

For the gs-importer case we only have two options I guess:

 - guess datetime fields (as the import procedure does now) and automatically configure the transformation
 - make the client guess datetime fields and let the user select them, once the client-side upload configuration tool will be in place

The automatic parsing of datetime fields on the BE could leverage the current [dataset_eligible_for_time_dimension](https://github.com/GeoNode/geonode/blob/master/geonode/upload/utils.py#L567). It's not very robust, since it only read the [first feature](https://github.com/GeoNode/geonode/blob/16fe0cb57ae65bd4ec8cea0741e5639f2578903f/geonode/upload/utils.py#L490) to guess the field format, but it could be probably improved a bit to make it more robust (if the first feature's value is empty try another one, maybe samples from the first 10 features).

Since we're going to adopt the new importer for all the vector formats soon, I would consider solution 1 (if it doesn't take too much)

**Comment by mattiagiupponi** [comment]
> The new importer shouldn't have this problem, since we publish from the DB and the field type should be automatically recognized. Do you confirm @mattiagiupponi?

The new importer will take the field type based on how ogr2ogr reads the dataset's schema. But I guess that we will continue to save the data as "Integer" and not as "date". I can try it on local to have an answer on this.

> * make the client guess datetime fields and let the user select them, once the client-side upload configuration tool will be in place
> Since we're going to adopt the new importer for all the vector formats soon, I would consider solution 1 (if it doesn't take too much)

I think this is not strictly needed. 
In my opinion, the dataset should be imported as is, as we already discuss the time series should be set later via the settings.
In the "Attribute" input box in the new settings panel, the user should be able to choose also the int value, then ones are selected, the BE should
- change (if possible) the feature type from INT to Datetime. If not raise an error to the user
- call GeoServer to reload the feature type schema
- set the time-series
- return the status to the user

I would avoid too much guessing from the client side. 
Is this may be related to this one https://github.com/geosolutions-it/geoserver/issues/339 @giohappy?

**Comment by afabiani** [comment]
@mattiagiupponi the selectbox should recognize Integer fields too IMHO. Consider the case when we have just the year as an instance. This should be also the current GeoServer behavior.

**Comment by mattiagiupponi** [comment]
> @mattiagiupponi the selectbox should recognize Integer fields too IMHO. Consider the case when we have just the year as an instance. This should be also the current GeoServer behavior.

Indeed @afabiani , this phrase is no longer valid:

`In the attribute and end_attribute fields, only the xsd:dateTime fields are displayed.`

**Comment by giohappy** [comment]
The final proposal is the following.

CURRENT IMPORTER:
for the moment we keep the time step during the upload.

NEW IMPORTER:
Initially, only file format with Date / DateTIme field type will be supported (ESRI Shapefile and GPKG). 
For the rest (textual formats like CSV and GeoJSON) the following will be estimated:

1. Create a new functionality in GeoNode to create **derived/computed fields**. This feature can be used to create new Time fields from existing fields. This means implementing the following:
 - add a new column to the data table
 - update the dynamic model schema accordingly
 - update the Geoserver FeatureType schema  
2. Expose this functionality inside the Metadata attributes list as well as a new dedicated API endpoint.

Once the new time field will be available in Geoserver, the field will appear inside the TIme dimension management box under the GeoNode's dataset metadata settings (already implemented).

**Comment by giohappy** [comment]
@marthamareal please test this on the development server. 

1 - Test that the configuration is correctly shown when you upload a new layer and configure it as time series
2 - Test that you can configure a time series afterward. You will have to upload a layer **without** configuring it as a time series dataset. Keep in mind that for testing this you need to upload a Shapefile having a Date field in it, otherwise the configuration panel won't find any suitable field to activate the time dimension. If you try with simple String and Number fields no field will be recognized as suitable.

These tests must be added to Cucumber.
