### ISSUE TITLE
HTML widget for identification panel

### ISSUE THREAD

**Issue by Inogeo** [GeoNode/geonode#9858]
**Is your feature request related to a problem? Please describe.**

I would like to render html content when I identify one entity on the map.

**Describe the solution you'd like**

As currently implemented in Mapstore, **allow the user to render html content inside the identification panel**.
Implementing the feature availble in mapstore would be sufficient to anwser our needs.

![image](https://user-images.githubusercontent.com/16825471/185051304-7f0a6f5b-3eab-4efd-8add-4f0334d8af74.png)
![image](https://user-images.githubusercontent.com/16825471/185051186-61c2f8db-6575-42b5-a719-31129ca71e57.png)
![image](https://user-images.githubusercontent.com/16825471/185051037-4ca01ed6-8e1c-4f73-bca4-8c002a792ff9.png)

**Describe alternatives you've considered**

Alternatively it could be proposed to the user to use an iframe to display external content.
The `<iframe></iframe>` tag could be matched with a regex and rendered inside the identification panel.

**Additional context**

(None yet)

**Comment by Inogeo** [comment]
EDIT: feature description updated (see above)

**Comment by gannebamm** [comment]
Hi @Inogeo 
Could you please check if the following solves your issue: https://docs.geonode.org/en/master/usage/managing_maps/exploring_maps/get_fetureinfo.html#advanced-template-use-a-custom-html-template

**Comment by Inogeo** [comment]
@gannebamm Yes, this feature answer my need, however I had to tweak the [TINYMCE_DEFAULT_CONFIG](https://geonode.sigdemo.egis-eau-sas.fr/geoserver/web/wicket/bookmarkable/org.geoserver.web.data.resource.ResourceConfigurationPage?name=lwsig_o_reservoir&wsName=geonode) variable in settings.py to enable the "code" menu in order to achieve this. 

In addition i also had to change the [PROXY_ALLOWED_HOSTS](https://docs.geonode.org/en/master/basic/settings/index.html?highlight=TINYMCE#proxy-allowed-hosts)

**Comment by gannebamm** [comment]
Just to clarify since your TINYMCE_DEFAULT_CONFIG URL seems off:

You shall change these settings in settings.py: https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L1629
According to this documentation: https://www.tiny.cloud/docs/plugins/opensource/code/
Whereas the plugin `code` is already enabled: https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L1632
But the toolbar `code` is currently missing: https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L1636

> The value used is the default value provided in the online documentation (actually different from the default value in settings.py)

Disabling some buttons was done as part of https://github.com/GeoNode/geonode/pull/8686

@Inogeo Do you think we can close this issue?

**Comment by Inogeo** [comment]
Before closing the issue, can the `code` toolbar be enabled by default in source code ?
